export const STATE_REDUCER_KEY = 'dfg';
export const METADATA_STORE_KEY = 'metadata';
export const SURVEY_TEMPLATE_STORE_KEY = 'survey_template';

//ORGANIZATION_SURVEY_TEMPLATE_ACTIVE_VERSION used for store active version of template for organization
export const ORGANIZATION_SURVEY_TEMPLATE_ACTIVE_VERSION = 'organization_survey_template_active';

export const QUESTION_TYPES = {
    OPTION_WITH_ICON: 'OPTION_WITH_ICON',
    TEXT: 'TEXT',
    DROPDOWN: 'DROPDOWN',
    OPTION: 'OPTION',
    TEXTAREA: 'TEXTAREA',
    CHECKBOX: 'CHECKBOX',
    IMAGE: 'IMAGE',
    QR_CODE: 'QR_CODE',
    LOCATION: 'LOCATION',
    SEARCHABLE_DROPDOWN: 'SEARCHABLE_DROPDOWN',
    DATE: 'DATE'
};

export const DYNAMIC_TYPES = {
    WARD: 'WARD',
    RESIDENTIAL_ASSOCIATION: 'RESIDENTIAL_ASSOCIATION',
    TRADING_TYPE: 'TRADING_TYPE'
};

export const DYNAMIC_TYPES_TO_QUESTION_TYPES = {
    [DYNAMIC_TYPES.WARD]: QUESTION_TYPES.DROPDOWN,
    [DYNAMIC_TYPES.RESIDENTIAL_ASSOCIATION]: QUESTION_TYPES.DROPDOWN,
    [DYNAMIC_TYPES.TRADING_TYPE]: QUESTION_TYPES.DROPDOWN
};

export const YUP_EXCLUDED_QUESTION_TYPES = [
    QUESTION_TYPES.CHECKBOX,
    QUESTION_TYPES.LOCATION
];

export const VALIDATION_TYPES = {
    IS_MANDATORY: 'IS_MANDATORY',
    IS_PHONE: 'IS_PHONE',
    IS_DIGIT: 'IS_DIGIT',
    IS_DECIMAL: 'IS_DECIMAL',
    IS_DIGIT_OR_DECIMAL: 'IS_DIGIT_OR_DECIMAL',
    IS_EMAIL: 'IS_EMAIL',
    PARENT_EQUALS_CHILD_SUM: 'PARENT_EQUALS_CHILD_SUM'
};

export const TEMPLATE_TYPES = {
    CUSTOMER_ENROLLMENT: 'CUSTOMER_ENROLLMENT',
    COMPLAINT: 'COMPLAINT',
    SERVICE_PROVIDER: 'SERVICE_PROVIDER',
    SURVEY_AGENCY: 'SURVEY_AGENCY',
    RESIDENTIAL_ASSOCIATION: 'RESIDENTIAL_ASSOCIATION',
    SERVICE_ENROLLMENT_RESIDENTIAL: 'SERVICE_ENROLLMENT_RESIDENTIAL',
    SERVICE_ENROLLMENT_NON_RESIDENTIAL: 'SERVICE_ENROLLMENT_NON_RESIDENTIAL',
    SERVICE_INOCULUM_SUPPLY: 'SERVICE_INOCULUM_SUPPLY',
    SERVICE_MANURE_COLLECTION: 'SERVICE_MANURE_COLLECTION',
    SERVICE_PLASTIC_WASTE_COLLECTION: 'SERVICE_PLASTIC_WASTE_COLLECTION',
    SERVICE_POULTRY_WASTE: 'SERVICE_POULTRY_WASTE',
    SERVICE_WET_WASTE_COLLECTION: 'SERVICE_WET_WASTE_COLLECTION',
    QR_CODE_ENROLLMENT: 'QR_CODE_ENROLLMENT'
};

export const TEMPLATE_TYPE_IDS = {
    [TEMPLATE_TYPES.CUSTOMER_ENROLLMENT]: 1,
    [TEMPLATE_TYPES.SERVICE_ENROLLMENT_RESIDENTIAL]: 2,
    [TEMPLATE_TYPES.SERVICE_ENROLLMENT_NON_RESIDENTIAL]: 7,
    [TEMPLATE_TYPES.SERVICE_INOCULUM_SUPPLY]: 8,
    [TEMPLATE_TYPES.SERVICE_MANURE_COLLECTION]: 9,
    [TEMPLATE_TYPES.SERVICE_PLASTIC_WASTE_COLLECTION]: 10,
    [TEMPLATE_TYPES.SERVICE_POULTRY_WASTE]: 11,
    [TEMPLATE_TYPES.SERVICE_WET_WASTE_COLLECTION]: 12,
    [TEMPLATE_TYPES.QR_CODE_ENROLLMENT]: 13,
    [TEMPLATE_TYPES.SERVICE_PROVIDER]: 4,
    [TEMPLATE_TYPES.RESIDENTIAL_ASSOCIATION]: 6


};

export const RESIDENCE_CATEGORIES = {
    RESIDENTIAL: 1,
    NON_RESIDENTIAL: 2
};

export const ROUTE_KEYS = {
    DYNAMICFORM: 'DynamicForm'
};

export const FILETYPES = 'image/jpeg';