const RESOURCE_MAPPING = {
    FRAGMENT: 'in.trois.common.model.entity.Fragment',
    FRAGMENT_DETAILS: 'in.trois.common.model.entity.Fragment.Details',
    FRAGMENT_ASSIGN_TITLE: 'in.trois.common.model.entity.Fragment.AssignTitle',
    FRAGMENT_QUESTION_FRAGMENT_LOOP: 'in.trois.common.model.entity.Fragment.QuestionFragmentLoop',
    FRAGMENT_CURRENT_ASSOCIATION: 'in.trois.common.model.entity.Fragment.CurrentAssociation',
    FRAGMENT_CURRENT_ASSOCIATION_QUESTION: 'in.trois.common.model.entity.Fragment.CurrentAssociation.Question',
    FRAGMENT_CURRENT_ASSOCIATION_TITLE: 'in.trois.common.model.entity.Fragment.CurrentAssociation.Title',
    FRAGMENT_CURRENT_ASSOCIATION_TEMPLATE: 'in.trois.common.model.entity.Fragment.CurrentAssociation.Template'
};

const ACTION_MAPPING = {
    FRAGMENT: {
        ACCESS_IN_WEB_NAV: 'FRAGMENT_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'FRAGMENT_READ_ONLY',
        LIST: 'FRAGMENT_LIST',
        ADD: 'FRAGMENT_ADD',
        VIEW_IN_ACTION: 'FRAGMENT_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'FRAGMENT_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'FRAGMENT_DELETE_IN_ACTION'
    },
    FRAGMENT_DETAILS: {
        ACCESS_IN_TAB: 'FRAGMENT_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_DETAILS_READ_ONLY'
    },
    FRAGMENT_ASSIGN_TITLE: {
        ACCESS_IN_TAB: 'FRAGMENT_ASSIGN_TITLE_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_ASSIGN_TITLE_READ_ONLY'
    },
    FRAGMENT_QUESTION_FRAGMENT_LOOP: {
        ACCESS_IN_TAB: 'FRAGMENT_QUESTION_FRAGMENT_LOOP_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_QUESTION_FRAGMENT_LOOP_READ_ONLY'
    },
    FRAGMENT_CURRENT_ASSOCIATION: {
        ACCESS_IN_TAB: 'FRAGMENT_CURRENT_ASSOCIATION_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_CURRENT_ASSOCIATION_READ_ONLY'
    },
    FRAGMENT_CURRENT_ASSOCIATION_QUESTION: {
        ACCESS_IN_TAB: 'FRAGMENT_CURRENT_ASSOCIATION_QUESTION_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_CURRENT_ASSOCIATION_QUESTION_READ_ONLY'
    },
    FRAGMENT_CURRENT_ASSOCIATION_TITLE: {
        ACCESS_IN_TAB: 'FRAGMENT_CURRENT_ASSOCIATION_TITLE_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_CURRENT_ASSOCIATION_TITLE_READ_ONLY'
    },
    FRAGMENT_CURRENT_ASSOCIATION_TEMPLATE: {
        ACCESS_IN_TAB: 'FRAGMENT_CURRENT_ASSOCIATION_TEMPLATE_ACCESS_IN_TAB',
        READ_ONLY: 'FRAGMENT_CURRENT_ASSOCIATION_TEMPLATE_READ_ONLY'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
