export const RESOURCE_MAPPING = {
    USER: 'in.trois.common.model.entity.User',
    ORGANIZATION: 'in.trois.common.model.entity.Organization',
    USER_GROUP: 'in.trois.common.model.entity.UserGroup',
    ROLE: 'in.trois.common.model.entity.Role',
    QUESTION: 'in.trois.common.model.entity.Question',
    TITLE: 'in.trois.common.model.entity.Title',
    FRAGMENT: 'in.trois.common.model.entity.Fragment',
    TEMPLATE: 'in.trois.common.model.entity.Template',
    RESIDENTIAL_ASSOCIATION: 'in.trois.common.model.entity.BasicConfig.ResidentialAssociation',
    SERVICE_ENROLLMENT: 'in.trois.common.model.entity.Customer.ServiceEnrollment',
    SCHEDULE: 'in.trois.common.model.entity.Schedule',
    REPORTED_BUGS: 'in.trois.common.model.entity.ReportABug',
    DASHBOARD_SURVEY: 'in.trois.common.model.entity.Dashboard.surveyDetails',
    DASHBOARD_SERVICES: 'in.trois.common.model.entity.Dashboard.servicesDetails',
    DASHBOARD_COMPLAINTS: 'in.trois.common.model.entity.Dashboard.complaintsDetails',
    DASHBOARD_PAYMENT: 'in.trois.common.model.entity.Dashboard.paymentDetails',
    DASHBOARD_SERVICE_PROVIDER: 'in.trois.common.model.entity.Dashboard.serviceProviderDetails'
};

export const ACTION_MAPPING = {
    USER: {
        ACCESS_USER_IN_NAV: 'ACCESS_USER_IN_NAV',
        EDIT_USER: 'EDIT_USER',
        DELETE_USER: 'DELETE_USER',
        LIST_USERS: 'LIST_USERS',
        ADD_USER: 'ADD_USER'
    },
    ORGANIZATION: {
        ACCESS_ORG_IN_NAV: 'ACCESS_ORG_IN_NAV',
        LIST_ORGANIZATIONS: 'LIST_ORGANIZATIONS',
        DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
        ADD_ORGANIZATION: 'ADD_ORGANIZATION',
        EDIT_ORGANIZATION: 'EDIT_ORGANIZATION'
    },

    USER_GROUP: {
        ACCESS_USERGROUP_IN_NAV: 'ACCESS_USERGROUP_IN_NAV',
        LIST_USER_GROUP: 'LIST_USERGROUP',
        DELETE_USER_GROUP: 'DELETE_USERGROUP',
        ADD_USER_GROUP: 'ADD_USERGROUP',
        EDIT_USER_GROUP: 'EDIT_USERGROUP'
    },
    USER_ROLE: {
        ACCESS_ROLE_IN_NAV: 'ACCESS_ROLE_IN_NAV',
        LIST_ROLE: 'LIST_ROLE',
        DELETE_ROLE: 'DELETE_ROLE',
        ADD_ROLE: 'ADD_ROLE',
        EDIT_ROLE: 'EDIT_ROLE',
        EDIT_ORG_ROLE: 'EDIT_ORG_ROLE',
        DELETE_ORG_ROLE: 'DELETE_ORG_ROLE'
    },
    QUESTION: {
        ACCESS_QUESTION_IN_NAV: 'ACCESS_QUESTION_IN_NAV',
        LIST_QUESTION: 'LIST_QUESTION',
        DELETE_QUESTION: 'DELETE_QUESTION',
        ADD_QUESTION: 'ADD_QUESTION',
        EDIT_QUESTION: 'EDIT_QUESTION'
    },

    TITLE: {
        ACCESS_TITLE_IN_NAV: 'ACCESS_TITLE_IN_NAV',
        LIST_TITLE: 'LIST_TITLE',
        DELETE_TITLE: 'DELETE_TITLE',
        ADD_TITLE: 'ADD_TITLE',
        EDIT_TITLE: 'EDIT_TITLE'
    },
    FRAGMENT: {
        ACCESS_FRAGMENT_IN_NAV: 'ACCESS_FRAGMENT_IN_NAV',
        LIST_FRAGMENT: 'LIST_FRAGMENT',
        DELETE_FRAGMENT: 'DELETE_FRAGMENT',
        ADD_FRAGMENT: 'ADD_FRAGMENT',
        EDIT_FRAGMENT: 'EDIT_FRAGMENT'
    },
    TEMPLATE: {
        ACCESS_TEMPLATE_IN_NAV: 'ACCESS_TEMPLATE_IN_NAV',
        LIST_TEMPLATE: 'LIST_TEMPLATE',
        DELETE_TEMPLATE: 'DELETE_TEMPLATE',
        ADD_TEMPLATE: 'ADD_TEMPLATE',
        EDIT_TEMPLATE: 'EDIT_TEMPLATE'
    },

    RESIDENTIAL_ASSOCIATION: {
        ACCESS_RESIDENTIAL_ASSOCIATION_IN_NAV: 'ACCESS_RESIDENTIAL_ASSOCIATION_IN_NAV',
        LIST_RESIDENTIAL_ASSOCIATION: 'LIST_RESIDENTIAL_ASSOCIATION',
        DELETE_RESIDENTIAL_ASSOCIATION: 'DELETE_RESIDENTIAL_ASSOCIATION',
        ADD_RESIDENTIAL_ASSOCIATION: 'ADD_RESIDENTIAL_ASSOCIATION',
        EDIT_RESIDENTIAL_ASSOCIATION: 'EDIT_RESIDENTIAL_ASSOCIATION'
    },
    SCHEDULE: {
        ACCESS_SCHEDULE_IN_NAV: 'ACCESS_SCHEDULE_IN_NAV',
        LIST_SCHEDULE: 'LIST_SCHEDULE',
        DELETE_SCHEDULE: 'DELETE_SCHEDULE',
        ADD_SCHEDULE: 'ADD_SCHEDULE',
        EDIT_SCHEDULE: 'EDIT_SCHEDULE',
        SCHEDULE_CUSTOMER_ADD: 'SCHEDULE_CUSTOMER_ADD',
        SCHEDULE_CUSTOMER_REMOVE: 'SCHEDULE_CUSTOMER_REMOVE',
        SHOW_HISTORY: 'SHOW_SCHEDULE_HISTORY',
        SHOW_ADVANCED_OPTIONS: 'SHOW_ADVANCED_OPTIONS'
    },
    DASHBOARD: {
        ACCESS_DASHBOARD_SURVEY_IN_WEB_NAV: 'ACCESS_DASHBOARD_SURVEY_IN_WEB_NAV',
        ACCESS_DASHBOARD_SERVICES_IN_WEB_NAV: 'ACCESS_DASHBOARD_SERVICES_IN_WEB_NAV',
        ACCESS_DASHBOARD_COMPLAINTS_IN_WEB_NAV: 'ACCESS_DASHBOARD_COMPLAINTS_IN_WEB_NAV',
        ACCESS_DASHBOARD_PAYMENT_IN_WEB_NAV: 'ACCESS_DASHBOARD_PAYMENT_IN_WEB_NAV',
        ACCESS_DASHBOARD_SERVICE_PROVIDER_IN_WEB_NAV: 'ACCESS_DASHBOARD_SERVICE_PROVIDER_IN_WEB_NAV'
    },
    REPORTED_BUGS: {
        ACCESS_REPORTED_BUGS_IN_WEB_NAV: 'ACCESS_REPORT_BUG_IN_WEB_NAV'
    },

    RRF_STOCK_TRANSFER: {
        ACCESS_RRF_STOCK_TRANSFER_IN_WEB_NAV: 'ACCESS_RRF_STOCK_TRANSFER_IN_WEB_NAV'
    }

};
