const RESOURCE_MAPPING = {
    ORGANIZATION: 'in.trois.common.model.entity.Organization',
    ORGANIZATION_DETAILS: 'in.trois.common.model.entity.Organization.Details',
    ORGANIZATION_ASSIGN_USER: 'in.trois.common.model.entity.Organization.AssignUser',
    ORGANIZATION_ASSIGN_ROLE: 'in.trois.common.model.entity.Organization.AssignRole',
    ORGANIZATION_ASSIGN_MODULE: 'in.trois.common.model.entity.Organization.AssignModule',
    ORGANIZATION_ASSIGN_MODULE_MODULES: 'in.trois.common.model.entity.Organization.AssignModule.Modules',
    ORGANIZATION_ASSIGN_MODULE_ASSIGN_ROLE: 'in.trois.common.model.entity.Organization.AssignModule.AssignRole',
    ORGANIZATION_SERVICE_PROVIDER: 'in.trois.common.model.entity.Organization.ServiceProvider',
    ORGANIZATION_SERVICE_PROVIDER_DETAILS: 'in.trois.common.model.entity.Organization.ServiceProvider.Details',
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_LOCATION: 'in.trois.common.model.entity.Organization.ServiceProvider.AssignLocation',
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER: 'in.trois.common.model.entity.Organization.ServiceProvider.AssignWorker',
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_LOCATION: 'in.trois.common.model.entity.Organization.ServiceProvider.AssignWorkerLocation',
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_TO_SUPERVISOR: 'in.trois.common.model.entity.Organization.ServiceProvider.AssignWorkerToSupervisor',
    ORGANIZATION_SERVICE_PROVIDER_SERVICE: 'in.trois.common.model.entity.Organization.ServiceProvider.Service',
    ORGANIZATION_SERVICE_PROVIDER_SERVICE_DETAILS: 'in.trois.common.model.entity.Organization.ServiceProvider.Service.Details',
    ORGANIZATION_SERVICE_PROVIDER_CONTACT: 'in.trois.common.model.entity.Organization.ServiceProvider.Contact',
    ORGANIZATION_SERVICE_PROVIDER_REASSIGN_SUPERVISOR: 'in.trois.common.model.entity.Organization.ServiceProvider.ReassignSupervisor',
    ORGANIZATION_SERVICE_PROVIDER_REASSIGN_WORKER: 'in.trois.common.model.entity.Organization.ServiceProvider.ReassignWorker',
    ORGANIZATION_API_PROVIDER: 'in.trois.common.model.entity.Organization.ApiProvider',
    ORGANIZATION_API_PROVIDER_EMAIL: 'in.trois.common.model.entity.Organization.ApiProvider.Email',
    ORGANIZATION_API_PROVIDER_NOTIFICATION: 'in.trois.common.model.entity.Organization.ApiProvider.Notification',
    ORGANIZATION_API_PROVIDER_PAYMENT_GATEWAY: 'in.trois.common.model.entity.Organization.ApiProvider.PaymentGateway',
    ORGANIZATION_ASSIGN_TEMPLATE: 'in.trois.common.model.entity.Organization.AssignTemplate',
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER: 'in.trois.common.model.entity.Organization.AssignCustomerServiceWorker',
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_UNDER_CURRENT_SERVICE_PROVIDER: 'in.trois.common.model.entity.Organization.AssignCustomerServiceWorker.CustomersUnderCurrentServiceProvider',
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_NOT_UNDER_CURRENT_SERVICE_PROVIDER: 'in.trois.common.model.entity.Organization.AssignCustomerServiceWorker.CustomersNotUnderCurrentServiceProvider',
    ORGANIZATION_COMPLAINT_ESCALATION_MATRIX: 'in.trois.common.model.entity.Organization.ComplaintEscalationMatrix',
    ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_DETAILS: 'in.trois.common.model.entity.Organization.ComplaintEscalationMatrix.Details',
    ORGANIZATION_ASSIGN_VENDOR_ITEM: 'in.trois.common.model.entity.Organization.AssignVendorItem',
    ORGANIZATION_ADDITIONAL_DETAILS: 'in.trois.common.model.entity.Organization.AdditionalDetails',
    ORGANIZATION_ASSIGN_ORGANIZATION: 'in.trois.common.model.entity.Organization.AssignOrganization'
};

const ACTION_MAPPING = {
    ORGANIZATION: {
        ACCESS_IN_WEB_NAV: 'ORGANIZATION_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'ORGANIZATION_READ_ONLY',
        LIST: 'ORGANIZATION_LIST',
        ADD: 'ORGANIZATION_ADD',
        VIEW_IN_ACTION: 'ORGANIZATION_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ORGANIZATION_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ORGANIZATION_DELETE_IN_ACTION'
    },
    ORGANIZATION_DETAILS: {
        ACCESS_IN_TAB: 'ORGANIZATION_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_DETAILS_READ_ONLY'
    },
    ORGANIZATION_ASSIGN_ORGANIZATION: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_ORGANIZATION_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_ORGANIZATION_READ_ONLY',
        LIST: 'ORGANIZATION_ASSIGN_ORGANIZATION_LIST',
        BELONG_TO_CURRENT_ORGANIZATION: 'ORGANIZATION_ASSIGN_ORGANIZATION_BELONG_TO_CURRENT_ORGANIZATION',
        DONT_HAVE_ANY_ORGANIZATION_ASSOCIATION: 'ORGANIZATION_ASSIGN_ORGANIZATION_DONT_HAVE_ANY_ORGANIZATION_ASSOCIATION'
    },
    ORGANIZATION_ASSIGN_USER: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_USER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_USER_READ_ONLY',
        LIST: 'ORGANIZATION_ASSIGN_USER_LIST',
        USERS_BELONG_TO_CURRENT_ORGANIZATION: 'ORGANIZATION_ASSIGN_USER_USERS_BELONG_TO_CURRENT_ORGANIZATION',
        USERS_DONT_HAVE_ANY_ORGANIZATION_ASSOCIATION: 'ORGANIZATION_ASSIGN_USER_USERS_DONT_HAVE_ANY_ORGANIZATION_ASSOCIATION'
    },
    ORGANIZATION_ASSIGN_ROLE: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_ROLE_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_ROLE_READ_ONLY',
        LIST: 'ORGANIZATION_ASSIGN_ROLE_LIST',
        USERS_BELONG_TO_CURRENT_ROLE: 'ORGANIZATION_ASSIGN_ROLE_USERS_BELONG_TO_CURRENT_ROLE',
        USERS_DONT_HAVE_ANY_ROLE: 'ORGANIZATION_ASSIGN_ROLE_USERS_DONT_HAVE_ANY_ROLE'
    },
    ORGANIZATION_ASSIGN_VENDOR_ITEM: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_READ_ONLY',
        LIST: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_LIST',
        ADD: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_ADD',
        VIEW_IN_ACTION: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ORGANIZATION_ASSIGN_VENDOR_ITEM_DELETE_IN_ACTION'
    },
    ORGANIZATION_ASSIGN_MODULE: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_MODULE_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_MODULE_READ_ONLY'
    },
    ORGANIZATION_ASSIGN_MODULE_MODULES: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_MODULE_MODULES_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_MODULE_MODULES_READ_ONLY'
    },
    ORGANIZATION_ASSIGN_MODULE_ASSIGN_ROLE: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_MODULE_ASSIGN_ROLE_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_MODULE_ASSIGN_ROLE_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_READ_ONLY',
        LIST: 'ORGANIZATION_SERVICE_PROVIDER_LIST',
        ADD: 'ORGANIZATION_SERVICE_PROVIDER_ADD',
        VIEW_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_DELETE_IN_ACTION'
    },
    ORGANIZATION_SERVICE_PROVIDER_DETAILS: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_DETAILS_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_LOCATION: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_LOCATION_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_LOCATION_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_LOCATION: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_LOCATION_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_LOCATION_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_TO_SUPERVISOR: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_TO_SUPERVISOR_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_ASSIGN_WORKER_TO_SUPERVISOR_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_SERVICE: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_READ_ONLY',
        LIST: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_LIST',
        ADD: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_ADD',
        VIEW_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_DELETE_IN_ACTION',
        INACTIVE_IN_ACTION: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_INACTIVE_IN_ACTION'
    },
    ORGANIZATION_SERVICE_PROVIDER_SERVICE_DETAILS: {
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_DETAILS_READ_ONLY',
        SPECIAL_SERVICE: 'ORGANIZATION_SERVICE_PROVIDER_SERVICE_DETAILS_SPECIAL_SERVICE'
    },
    ORGANIZATION_SERVICE_PROVIDER_CONTACT: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_CONTACT_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_CONTACT_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_REASSIGN_SUPERVISOR: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_REASSIGN_SUPERVISOR_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_REASSIGN_SUPERVISOR_READ_ONLY'
    },
    ORGANIZATION_SERVICE_PROVIDER_REASSIGN_WORKER: {
        ACCESS_IN_TAB: 'ORGANIZATION_SERVICE_PROVIDER_REASSIGN_WORKER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_SERVICE_PROVIDER_REASSIGN_WORKER_READ_ONLY'
    },
    ORGANIZATION_API_PROVIDER: {
        ACCESS_IN_TAB: 'ORGANIZATION_API_PROVIDER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_API_PROVIDER_READ_ONLY'
    },
    ORGANIZATION_API_PROVIDER_EMAIL: {
        ACCESS_IN_TAB: 'ORGANIZATION_API_PROVIDER_EMAIL_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_API_PROVIDER_EMAIL_READ_ONLY'
    },
    ORGANIZATION_API_PROVIDER_NOTIFICATION: {
        ACCESS_IN_TAB: 'ORGANIZATION_API_PROVIDER_NOTIFICATION_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_API_PROVIDER_NOTIFICATION_READ_ONLY'
    },
    ORGANIZATION_API_PROVIDER_PAYMENT_GATEWAY: {
        ACCESS_IN_TAB: 'ORGANIZATION_API_PROVIDER_PAYMENT_GATEWAY_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_API_PROVIDER_PAYMENT_GATEWAY_READ_ONLY'
    },
    ORGANIZATION_ASSIGN_TEMPLATE: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_TEMPLATE_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_TEMPLATE_READ_ONLY',
        LIST: 'ORGANIZATION_ASSIGN_TEMPLATE_LIST'
    },
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_READ_ONLY'
    },
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_UNDER_CURRENT_SERVICE_PROVIDER: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_UNDER_CURRENT_SERVICE_PROVIDER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_UNDER_CURRENT_SERVICE_PROVIDER_READ_ONLY',
        SELECT_ALL: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_UNDER_CURRENT_SERVICE_PROVIDER_SELECT_ALL'
    },
    ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_NOT_UNDER_CURRENT_SERVICE_PROVIDER: {
        ACCESS_IN_TAB: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_NOT_UNDER_CURRENT_SERVICE_PROVIDER_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_NOT_UNDER_CURRENT_SERVICE_PROVIDER_READ_ONLY',
        SELECT_ALL: 'ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_CUSTOMERS_NOT_UNDER_CURRENT_SERVICE_PROVIDER_SELECT_ALL'
    },
    ORGANIZATION_COMPLAINT_ESCALATION_MATRIX: {
        ACCESS_IN_TAB: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_READ_ONLY',
        LIST: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_LIST',
        ADD: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_ADD',
        VIEW_IN_ACTION: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_DELETE_IN_ACTION'
    },
    ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_DETAILS: {
        ACCESS_IN_TAB: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_COMPLAINT_ESCALATION_MATRIX_DETAILS_READ_ONLY'
    },
    ORGANIZATION_ADDITIONAL_DETAILS: {
        ACCESS_IN_TAB: 'ORGANIZATION_ADDITIONAL_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ORGANIZATION_ADDITIONAL_DETAILS_READ_ONLY',
        LIST: 'ORGANIZATION_ADDITIONAL_DETAILS_LIST'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
