const RESOURCE_MAPPING = {
    // 1. Reported Bugs
    REPORTED_BUGS: 'in.trois.common.model.entity.ReportedBugs',
    CUSTOMER: 'in.trois.common.model.entity.Customer',
    SERVICE: 'in.trois.common.model.entity.Service',
    SUBSCRIPTION: 'in.trois.common.model.entity.Subscription',
    PAYMENT: 'in.trois.common.model.entity.Payment',
    COMPLAINT: 'in.trois.common.model.entity.Complaint',
    INCIDENTS: 'in.trois.common.model.entity.Incident',
    SPECIAL_SERVICE: 'in.trois.common.model.entity.SpecialServiceRequest',
    SUBSCRIPTION_REQUEST: 'in.trois.common.model.entity.SubscriptionRequest',
    QRCODE: 'in.trois.common.model.entity.QRCode',
    BASIC_CONFIG: 'in.trois.common.model.entity.BasicConfig',
    MCF: 'in.trois.common.model.entity.MCF',
    MCF_STOCK_IN: 'in.trois.common.model.entity.MCF.StockIn',
    MCF_SEGGREGATION: 'in.trois.common.model.entity.MCF.Segregation',

    MCF_STOCK_TRANSFER: 'in.trois.common.model.entity.MCF.StockTransfer',
    MCF_STOCK_SALE: 'in.trois.common.model.entity.MCF.Sale',
    RRF: 'in.trois.common.model.entity.RRF',
    RRF_SALES: 'in.trois.common.model.entity.RRF.Sale',
    RRF_SHREDDED: 'in.trois.common.model.entity.RRF.Shredded',

    RRF_STOCK_IN: 'in.trois.common.model.entity.RRF.StockIn',
    CKC: 'in.trois.common.model.entity.CKC',
    CKC_PICKUP: 'in.trois.common.model.entity.CKC.Pickup',
    CKC_SALES: 'in.trois.common.model.entity.CKC.Sale',
    STATE: 'in.trois.common.model.entity.BasicConfig.State',
    ITEM: 'in.trois.common.model.entity.BasicConfig.ItemConfig',
    DISTRICT: 'in.trois.common.model.entity.BasicConfig.District',
    LSGI: 'in.trois.common.model.entity.BasicConfig.LSGI',
    BLOCK_PANCHAYATH: 'in.trois.common.model.entity.BasicConfig.BlockPanchayath',
    DISTRICT_PANCHAYATH: 'in.trois.common.model.entity.BasicConfig.DistrictPanchayath',
    RESIDENCE_CATEGORY: 'in.trois.common.model.entity.BasicConfig.ResidenceCategory',
    WARD: 'in.trois.common.model.entity.BasicConfig.Ward',
    TRADING_TYPE: 'in.trois.common.model.entity.BasicConfig.TradingType',
    BUILDING_TYPE: 'in.trois.common.model.entity.BasicConfig.BuildingType',
    SHOP_TYPE: 'in.trois.common.model.entity.BasicConfig.ShopType',
    ASSOCIATION_TYPE: 'in.trois.common.model.entity.BasicConfig.AssociationType',
    SERVICE_CHARGE_SLAB: 'in.trois.common.model.entity.BasicConfig.ServiceChargeSlab',
    PUBLIC_GATHERING_METHOD: 'in.trois.common.model.entity.BasicConfig.PublicGatheringMethod',
    TERRACE_FARMING: 'in.trois.common.model.entity.BasicConfig.TerraceFarmingHelpType',
    ORGANIZATION_TYPE: 'in.trois.common.model.entity.BasicConfig.OrganizationType',
    ADMINISTRATION_TYPE: 'in.trois.common.model.entity.BasicConfig.AdministrationType',
    SERVICE_CONFIG: 'in.trois.common.model.entity.BasicConfig.ServiceConfig',
    BUNDLED_SERVICE_CONFIG: 'in.trois.common.model.entity.BasicConfig.BundledServiceConfig',
    COMPLAINT_CONFIG: 'in.trois.common.model.entity.BasicConfig.ComplaintConfig',
    INCIDENT_CONFIG: 'in.trois.common.model.entity.BasicConfig.IncidentConfig',
    ITEM_SUB_CATEGORY: 'in.trois.common.model.entity.BasicConfig.ItemSubcategory'

};

const ACTION_MAPPING = {
    REPORTED_BUGS: {
        ACCESS_IN_WEB_NAV: 'REPORTED_BUGS_ACCESS_IN_WEB_NAV'
    },
    CUSTOMER: {
        ACCESS_CUSTOMER_IN_NAV: 'ACCESS_CUSTOMER_IN_NAV',
        LIST_CUSTOMER: 'LIST_CUSTOMER',
        DELETE_CUSTOMER: 'DELETE_CUSTOMER',
        ADD_CUSTOMER: 'ADD_CUSTOMER',
        EDIT_CUSTOMER: 'EDIT_CUSTOMER',
        EDIT_SERVICE_ENROLLMENT: 'EDIT_SERVICE_ENROLLMENT',
        ACCESS_CUSTOMER_DATA_CORRECTION_IN_WEB_NAV: 'ACCESS_CUSTOMER_DATA_CORRECTION_IN_WEB_NAV',
        LIST_CUSTOMER_DATA_CORRECTION: 'LIST_CUSTOMER_DATA_CORRECTION',
        VIEW_CUSTOMER_DATA_CORRECTION: 'VIEW_CUSTOMER_DATA_CORRECTION',
        VIEW_CUSTOMER: 'VIEW_CUSTOMER',
        DO_CUSTOMER_QR_ENROLLMENT: 'DO_CUSTOMER_QR_ENROLLMENT'

    },
    SERVICE: {
        ACCESS_SERVICE_IN_WEB_NAV: 'ACCESS_SERVICE_IN_WEB_NAV',
        LIST_SERVICE: 'LIST_SERVICE',
        ACCESS_SERVICE_HISTORY_IN_WEB_NAV: 'ACCESS_SERVICE_HISTORY_IN_WEB_NAV',
        LIST_SERVICE_HISTORY: 'LIST_SERVICE_HISTORY',
        VIEW_SERVICE: 'VIEW_SERVICE',
        EDIT_SERVICE_HISTORY: 'EDIT_SERVICE_HISTORY'
    },
    SUBSCRIPTION: {
        ACCESS_SUBSCRIPTION_IN_WEB_NAV: 'ACCESS_SUBSCRIPTION_IN_WEB_NAV',
        LIST_SUBSCRIPTION: 'LIST_SUBSCRIPTION'
    },
    PAYMENT: {
        ACCESS_PAYMENT_IN_NAV: 'ACCESS_PAYMENT_IN_WEB_NAV',
        LIST_PAYMENT: 'LIST_PAYMENT'
    },
    COMPLAINT: {
        ACCESS_COMPLAINT_IN_WEB_NAV: 'ACCESS_COMPLAINT_IN_WEB_NAV',
        LIST_COMPLAINT: 'LIST_COMPLAINT'
    },
    INCIDENTS: {
        ACCESS_INCIDENT_IN_WEB_NAV: 'ACCESS_INCIDENT_IN_WEB_NAV',
        ACCESS_INCIDENT_CONFIG_IN_WEB_NAV: 'ACCESS_INCIDENT_CONFIG_IN_WEB_NAV',
        LIST_INCIDENT_CONFIG: 'LIST_INCIDENT_CONFIG',
        ADD_INCIDENT_CONFIG: 'ADD_INCIDENT_CONFIG',
        EDIT_INCIDENT_CONFIG: 'EDIT_INCIDENT_CONFIG',
        DELETE_INCIDENT_CONFIG: 'DELETE_INCIDENT_CONFIG'
    },
    SPECIAL_SERVICE: {
        ACCESS_SPECIAL_SERVICE_IN_NAV: 'ACCESS_SPECIAL_SERVICE_IN_NAV',
        APPROVE: 'APPROVE_SPECIAL_SERVICE',
        REJECT: 'DECLINE_SPECIAL_SERVICE',
        CREATE_SCHEDULE: 'CREATE_SCHEDULE_SPECIAL_SERVICE'
    },
    SUBSCRIPTION_REQUEST: {
        ACCESS_SUBSCRIPTION_REQUEST_IN_WEB_NAV: 'ACCESS_SUBSCRIPTION_REQUEST_IN_WEB_NAV',
        LIST_SUBSCRIPTION_REQUEST: 'LIST_SUBSCRIPTION_REQUEST',
        APPROVE: 'APPROVE_SUBSCRIPTION_REQUEST',
        DECLINE: 'DECLINE_SUBSCRIPTION_REQUEST'
    },
    QRCODE: {
        ACCESS_QRCODE_IN_NAV: 'ACCESS_QRCODE_IN_NAV'
    },
    MCF: {
        ACCESS_IN_WEB_NAV: 'MCF_ACCESS_IN_WEB_NAV',
        ACCESS_MCF_STOCK_IN_IN_WEB_NAV: 'ACCESS_MCF_STOCK_IN_IN_WEB_NAV',
        ACCESS_MCF_STOCK_TRANSFER_IN_WEB_NAV: 'ACCESS_MCF_STOCK_TRANSFER_IN_WEB_NAV',
        ACCESS_MCF_SALE_IN_WEB_NAV: 'ACCESS_MCF_SALE_IN_WEB_NAV',
        ACCESS_MCF_SEGGREGATION_IN_WEB_NAV: 'ACCESS_MCF_SEGGREGATION_IN_WEB_NAV'
    },

    RRF_PLASTIC_SHREDDED: {
        ACCESS_IN_WEB_NAV: 'RRF_PLASTIC_SHREDDED_ACCESS_IN_WEB_NAV',
        LIST: 'RRF_PLASTIC_SHREDDED_LIST',
        VIEW_IN_ACTION: 'RRF_PLASTIC_SHREDDED_VIEW_IN_ACTION'
    },

    MCF_SEGREGATION: {
        ACCESS_IN_WEB_NAV: 'MCF_SEGREGATION_ACCESS_IN_WEB_NAV',
        LIST: 'MCF_SEGREGATION_LIST',
        VIEW_IN_ACTION: 'MCF_SEGREGATION_VIEW_IN_ACTION'
    },

    RRF: {
        ACCESS_IN_WEB_NAV: 'RRF_ACCESS_IN_WEB_NAV',
        ACCESS_RRF_SHREDDED_IN_WEB_NAV: 'ACCESS_RRF_SHREDDED_IN_WEB_NAV'

    },
    RRF_SALES: {
        ACCESS_RRF_SALES_IN_NAV: 'ACCESS_RRF_SALE_IN_WEB_NAV'
    },
    RRF_STOCK_IN: {
        ACCESS_RRF_STOCK_IN_NAV: 'ACCESS_RRF_STOCK_IN_IN_WEB_NAV'
    },
    CKC: {
        ACCESS_IN_WEB_NAV: 'CKC_ACCESS_IN_WEB_NAV'
    },
    CKC_PICKUP: {
        ACCESS_CKC_PICKUP_IN_NAV: 'ACCESS_CKC_PICKUP_IN_WEB_NAV'
    },
    CKC_SALES: {
        ACCESS_CKC_SALE_IN_NAV: 'ACCESS_CKC_SALE_IN_WEB_NAV'
    },

    STATE: {
        ACCESS_STATE_IN_NAV: 'ACCESS_STATE_IN_NAV',
        LIST_STATE: 'LIST_STATE',
        DELETE_STATE: 'DELETE_STATE',
        ADD_STATE: 'ADD_STATE',
        EDIT_STATE: 'EDIT_STATE'
    },
    ITEM: {
        ACCESS_ITEM_CONFIG_IN_WEB_NAV: 'ACCESS_ITEM_CONFIG_IN_WEB_NAV',
        LIST_ITEM_CONFIG: 'LIST_ITEM_CONFIG',
        DELETE_ITEM_CONFIG: 'DELETE_ITEM_CONFIG',
        ADD_ITEM_ITEM_CONFIG: 'ADD_ITEM_CONFIG',
        EDIT_ITEM_CONFIG: 'EDIT_ITEM_CONFIG',
        ASSIGN_SUBCATEGORY_ITEM_CONFIG: 'ITEM_ASSIGN_SUBCATEGORY_IN_ACTION'
    },
    ITEM_SUB_CATEGORY_DETAILS: {
        READ_ONLY: 'ITEM_SUBCATEGORY_DETAILS_READ_ONLY'
    },
    ITEM_SUB_CATEGORY: {
        ACCESS_IN_WEB_NAV: 'ITEM_SUBCATEGORY_ACCESS_IN_WEB_NAV',
        LIST: 'ITEM_SUBCATEGORY_LIST',
        ADD: 'ITEM_SUBCATEGORY_ADD',
        VIEW_IN_ACTION: 'ITEM_SUBCATEGORY_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ITEM_SUBCATEGORY_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ITEM_SUBCATEGORY_DELETE_IN_ACTION'
    },
    DISTRICT: {
        ACCESS_DISTRICT_IN_NAV: 'ACCESS_DISTRICT_IN_NAV',
        LIST_DISTRICT: 'LIST_DISTRICT',
        DELETE_DISTRICT: 'DELETE_DISTRICT',
        ADD_DISTRICT: 'ADD_DISTRICT',
        EDIT_DISTRICT: 'EDIT_DISTRICT'
    },
    LSGI: {
        ACCESS_LSGI_IN_NAV: 'ACCESS_LSGI_IN_NAV',
        LIST_LSGI: 'LIST_LSGI',
        DELETE_LSGI: 'DELETE_LSGI',
        ADD_LSGI: 'ADD_LSGI',
        EDIT_LSGI: 'EDIT_LSGI'
    },
    BLOCK_PANCHAYATH: {
        ACCESS_BLOCK_PANCHAYATH_IN_NAV: 'ACCESS_BLOCK_PANCHAYATH_IN_NAV',
        LIST_BLOCK_PANCHAYATH: 'LIST_BLOCK_PANCHAYATH',
        DELETE_BLOCK_PANCHAYATH: 'DELETE_BLOCK_PANCHAYATH',
        ADD_BLOCK_PANCHAYATH: 'ADD_BLOCK_PANCHAYATH',
        EDIT_BLOCK_PANCHAYATH: 'EDIT_BLOCK_PANCHAYATH'
    },
    DISTRICT_PANCHAYATH: {
        ACCESS_DISTRICT_PANCHAYATH_IN_NAV: 'ACCESS_DISTRICT_PANCHAYATH_IN_NAV',
        LIST_DISTRICT_PANCHAYATH: 'LIST_DISTRICT_PANCHAYATH',
        DELETE_DISTRICT_PANCHAYATH: 'DELETE_DISTRICT_PANCHAYATH',
        ADD_DISTRICT_PANCHAYATH: 'ADD_DISTRICT_PANCHAYATH',
        EDIT_DISTRICT_PANCHAYATH: 'EDIT_DISTRICT_PANCHAYATH'
    },
    RESIDENCE_CATEGORY: {
        ACCESS_RESIDENCE_CATEGORY_IN_NAV: 'ACCESS_RESIDENCE_CATEGORY_IN_NAV',
        LIST_RESIDENCE_CATEGORY: 'LIST_RESIDENCE_CATEGORY',
        DELETE_RESIDENCE_CATEGORY: 'DELETE_RESIDENCE_CATEGORY',
        ADD_RESIDENCE_CATEGORY: 'ADD_RESIDENCE_CATEGORY',
        EDIT_RESIDENCE_CATEGORY: 'EDIT_RESIDENCE_CATEGORY'
    },

    WARD: {
        ACCESS_WARD_IN_NAV: 'ACCESS_WARD_IN_NAV',
        LIST_WARD: 'LIST_WARD',
        DELETE_WARD: 'DELETE_WARD',
        ADD_WARD: 'ADD_WARD',
        EDIT_WARD: 'EDIT_WARD'
    },
    TRADING_TYPE: {
        ACCESS_TRADING_TYPE_IN_NAV: 'ACCESS_TRADING_TYPE_IN_NAV',
        LIST_TRADING_TYPE: 'LIST_TRADING_TYPE',
        DELETE_TRADING_TYPE: 'DELETE_TRADING_TYPE',
        ADD_TRADING_TYPE: 'ADD_TRADING_TYPE',
        EDIT_TRADING_TYPE: 'EDIT_TRADING_TYPE'
    },
    BUILDING_TYPE: {
        ACCESS_BUILDING_TYPE_IN_NAV: 'ACCESS_BUILDING_TYPE_IN_NAV',
        LIST_BUILDING_TYPE: 'LIST_BUILDING_TYPE',
        DELETE_BUILDING_TYPEE: 'DELETE_BUILDING_TYPE',
        ADD_BUILDING_TYPE: 'ADD_BUILDING_TYPE',
        EDIT_BUILDING_TYPE: 'EDIT_BUILDING_TYPE'
    },
    SHOP_TYPE: {
        ACCESS_SHOP_TYPE_IN_NAV: 'ACCESS_SHOP_TYPE_IN_NAV',
        LIST_SHOP_TYPE: 'LIST_SHOP_TYPE',
        DELETE_SHOP_TYPE: 'DELETE_SHOP_TYPE',
        ADD_SHOP_TYPE: 'ADD_SHOP_TYPE',
        EDIT_SHOP_TYPE: 'EDIT_SHOP_TYPE'
    },
    ASSOCIATION_TYPE: {
        ACCESS_ASSOCIATION_TYPE_IN_NAV: 'ACCESS_ASSOCIATION_TYPE_IN_NAV',
        LIST_ASSOCIATION_TYPE: 'LIST_ASSOCIATION_TYPE',
        DELETE_ASSOCIATION_TYPE: 'DELETE_ASSOCIATION_TYPE',
        ADD_ASSOCIATION_TYPE: 'ADD_ASSOCIATION_TYPE',
        EDIT_ASSOCIATION_TYPE: 'EDIT_ASSOCIATION_TYPE'
    },
    SERVICE_CHARGE_SLAB: {
        ACCESS_SERVICE_CHARGE_SLAB_IN_NAV: 'ACCESS_SERVICE_CHARGE_SLAB_IN_NAV',
        LIST_SERVICE_CHARGE_SLAB: 'LIST_SERVICE_CHARGE_SLAB',
        DELETE_SERVICE_CHARGE_SLAB: 'DELETE_SERVICE_CHARGE_SLAB',
        ADD_SERVICE_CHARGE_SLAB: 'ADD_SERVICE_CHARGE_SLAB',
        EDIT_SERVICE_CHARGE_SLAB: 'EDIT_SERVICE_CHARGE_SLAB'
    },
    PUBLIC_GATHERING_METHOD: {
        ACCESS_PUBLIC_GATHERING_METHOD_IN_NAV: 'ACCESS_PUBLIC_GATHERING_METHOD_IN_NAV',
        LIST_PUBLIC_GATHERING_METHOD: 'LIST_PUBLIC_GATHERING_METHOD',
        DELETE_PUBLIC_GATHERING_METHOD: 'DELETE_PUBLIC_GATHERING_METHOD',
        ADD_PUBLIC_GATHERING_METHOD: 'ADD_PUBLIC_GATHERING_METHOD',
        EDIT_PUBLIC_GATHERING_METHOD: 'EDIT_PUBLIC_GATHERING_METHOD'
    },
    TERRACE_FARMING: {
        ACCESS_TERRACE_FARMING_HELP_TYPE_IN_NAV: 'ACCESS_TERRACE_FARMING_HELP_TYPE_IN_NAV',
        LIST_TERRACE_FARMING: 'LIST_TERRACE_FARMING_HELP_TYPE',
        DELETE_TERRACE_FARMING: 'DELETE_TERRACE_FARMING_HELP_TYPE',
        ADD_TERRACE_FARMING: 'ADD_TERRACE_FARMING_HELP_TYPE',
        EDIT_TERRACE_FARMING: 'EDIT_TERRACE_FARMING_HELP_TYPE'
    },
    ORGANIZATION_TYPE: {
        ACCESS_ORGANIZATION_TYPE_IN_NAV: 'ACCESS_ORGANIZATION_TYPE_IN_NAV',
        LIST_ORGANIZATIONS_TYPE: 'LIST_ORGANIZATIONS_TYPE',
        DELETE_ORGANIZATION_TYPE: 'DELETE_ORGANIZATION_TYPE',
        ADD_ORGANIZATION_TYPE: 'ADD_ORGANIZATION_TYPE',
        EDIT_ORGANIZATION_TYPE: 'EDIT_ORGANIZATION_TYPE'
    },
    ADMINISTRATION_TYPE: {
        ACCESS_ADMINISTRATION_TYPE_IN_NAV: 'ACCESS_ADMINISTRATION_TYPE_IN_NAV',
        LIST_ADMINISTRATION_TYPE: 'LIST_ADMINISTRATION_TYPE',
        DELETE_AADMINISTRATION_TYPE: 'DELETE_ADMINISTRATION_TYPE',
        ADD_ADMINISTRATION_TYPE: 'ADD_ADMINISTRATION_TYPE',
        EDIT_ADMINISTRATION_TYPE: 'EDIT_ADMINISTRATION_TYPE'
    },
    SERVICE_CONFIG: {
        ACCESS_SERVICE_CONFIG_IN_NAV: 'ACCESS_SERVICE_CONFIG_IN_NAV',
        LIST_SERVICE_CONFIG: 'LIST_SERVICE_CONFIG',
        DELETE_SERVICE_CONFIG: 'DELETE_SERVICE_CONFIG',
        ADD_SERVICE_CONFIG: 'ADD_SERVICE_CONFIG',
        EDIT_SERVICE_CONFIG: 'EDIT_SERVICE_CONFIG'
    },
    BUNDLED_SERVICE_CONFIG: {
        ACCESS_BUNDLED_SERVICE_CONFIG_IN_NAV: 'ACCESS_BUNDLED_SERVICE_CONFIG_IN_NAV',
        LIST_BUNDLED_SERVICE_CONFIG: 'LIST_BUNDLED_SERVICE_CONFIG',
        DELETE_BUNDLED_SERVICE_CONFIG: 'DELETE_BUNDLED_SERVICE_CONFIG',
        ADD_BUNDLED_SERVICE_CONFIG: 'ADD_BUNDLED_SERVICE_CONFIG',
        EDIT_BUNDLED_SERVICE_CONFIG: 'EDIT_BUNDLED_SERVICE_CONFIG'
    },
    COMPLAINT_CONFIG: {
        ACCESS_COMPLAINT_IN_WEB_NAV: 'ACCESS_COMPLAINT_CONFIG_IN_WEB_NAV',
        LIST_COMPLAINT_CONFIG: 'LIST_COMPLAINT_CONFIG',
        ADD_COMPLAINT_CONFIG: 'ADD_COMPLAINT_CONFIG',
        EDIT_COMPLAINT_CONFIG: 'EDIT_COMPLAINT_CONFIG',
        DELETE_COMPLAINT_CONFIG: 'DELETE_COMPLAINT_CONFIG',
        ACCESS_INCIDENT_IN_WEB_NAV: 'ACCESS_INCIDENT_IN_WEB_NAV'
    },
    BASIC_CONFIG: {
        ACCESS_IN_WEB_NAV: 'BASIC_CONFIG_ACCESS_IN_WEB_NAV'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
