const RESOURCE_MAPPING = {
    QUESTION: 'in.trois.common.model.entity.Question',
    QUESTION_DETAILS: 'in.trois.common.model.entity.Question.Details',
    QUESTION_CURRENT_ASSOCIATION: 'in.trois.common.model.entity.Question.CurrentAssociation',
    QUESTION_CURRENT_ASSOCIATION_TITLE: 'in.trois.common.model.entity.Question.CurrentAssociation.Title',
    QUESTION_CURRENT_ASSOCIATION_FRAGMENT: 'in.trois.common.model.entity.Question.CurrentAssociation.Fragment',
    QUESTION_CURRENT_ASSOCIATION_TEMPLATE: 'in.trois.common.model.entity.Question.CurrentAssociation.Template'
};

const ACTION_MAPPING = {
    QUESTION: {
        ACCESS_IN_WEB_NAV: 'QUESTION_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'QUESTION_READ_ONLY',
        LIST: 'QUESTION_LIST',
        ADD: 'QUESTION_ADD',
        VIEW_IN_ACTION: 'QUESTION_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'QUESTION_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'QUESTION_DELETE_IN_ACTION'
    },
    QUESTION_DETAILS: {
        ACCESS_IN_TAB: 'QUESTION_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'QUESTION_DETAILS_READ_ONLY'
    },
    QUESTION_CURRENT_ASSOCIATION: {
        ACCESS_IN_TAB: 'QUESTION_CURRENT_ASSOCIATION_ACCESS_IN_TAB',
        READ_ONLY: 'QUESTION_CURRENT_ASSOCIATION_READ_ONLY'
    },
    QUESTION_CURRENT_ASSOCIATION_TITLE: {
        ACCESS_IN_TAB: 'QUESTION_CURRENT_ASSOCIATION_TITLE_ACCESS_IN_TAB',
        READ_ONLY: 'QUESTION_CURRENT_ASSOCIATION_TITLE_READ_ONLY'
    },
    QUESTION_CURRENT_ASSOCIATION_FRAGMENT: {
        ACCESS_IN_TAB: 'QUESTION_CURRENT_ASSOCIATION_FRAGMENT_ACCESS_IN_TAB',
        READ_ONLY: 'QUESTION_CURRENT_ASSOCIATION_FRAGMENT_READ_ONLY'
    },
    QUESTION_CURRENT_ASSOCIATION_TEMPLATE: {
        ACCESS_IN_TAB: 'QUESTION_CURRENT_ASSOCIATION_TEMPLATE_ACCESS_IN_TAB',
        READ_ONLY: 'QUESTION_CURRENT_ASSOCIATION_TEMPLATE_READ_ONLY'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
