const RESOURCE_MAPPING = {
    REPORT: 'in.trois.common.model.entity.Report',
    REPORT_DOOR_STATUS: 'in.trois.common.model.entity.Report.DoorStatus',
    REPORT_DOOR_STATUS_EXPORT: 'in.trois.common.model.entity.Report.DoorStatus.Export',
    REPORT_SURVEY_COUNT: 'in.trois.common.model.entity.Report.SurveyCount',
    REPORT_SURVEY_COUNT_EXPORT: 'in.trois.common.model.entity.Report.SurveyCount.Export',
    REPORT_ADVANCE_STATUS: 'in.trois.common.model.entity.Report.AdvanceStatus',
    REPORT_ADVANCE_STATUS_EXPORT: 'in.trois.common.model.entity.Report.AdvanceStatus.Export',

    REPORT_SERVICE_COMPLETION_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServiceCompletionResidential',
    REPORT_SERVICE_COMPLETION_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServiceCompletionResidential.Export',
    REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServiceCompletionNonResidential',
    REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServiceCompletionNonResidential.Export',
    REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServiceCountEscalatedResidential',
    REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServiceCountEscalatedResidential.Export',
    REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServiceCountEscalatedNonResidential',
    REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServiceCountEscalatedNonResidential.Export',
    REPORT_SERVICE_PENDING_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServicePendingResidential',
    REPORT_SERVICE_PENDING_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServicePendingResidential.Export',
    REPORT_SERVICE_PENDING_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ServicePendingNonResidential',
    REPORT_SERVICE_PENDING_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ServicePendingNonResidential.Export',


    REPORT_PLAN_ENABLED_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlanEnabledResidential',
    REPORT_PLAN_ENABLED_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlanEnabledResidential.Export',
    REPORT_PLAN_ENABLED_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlanEnabledNonResidential',
    REPORT_PLAN_ENABLED_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlanEnabledNonResidential.Export',
    REPORT_PLAN_DISABLED_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlanDisabledResidential',
    REPORT_PLAN_DISABLED_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlanDisabledResidential.Export',
    REPORT_PLAN_DISABLED_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlanDisabledNonResidential',
    REPORT_PLAN_DISABLED_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlanDisabledNonResidential.Export',

    REPORT_PAYMENT_COLLECTED_RESIDENTIAL: 'in.trois.common.model.entity.Report.PaymentCollectedResidential',
    REPORT_PAYMENT_COLLECTED_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PaymentCollectedResidential.Export',
    REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PaymentCollectedNonResidential',
    REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PaymentCollectedNonResidential.Export',
    REPORT_PAYMENT_DUE_RESIDENTIAL: 'in.trois.common.model.entity.Report.PaymentDueResidential',
    REPORT_PAYMENT_DUE_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PaymentDueResidential.Export',
    REPORT_PAYMENT_DUE_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PaymentDueNonResidential',
    REPORT_PAYMENT_DUE_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PaymentDueNonResidential.Export',

    REPORT_ITEM_WISE_MCF: 'in.trois.common.model.entity.Report.ItemWiseMCF',
    REPORT_ITEM_WISE_MCF_EXPORT: 'in.trois.common.model.entity.Report.ItemWiseMCF.Export',
    REPORT_ITEM_WISE_RRF: 'in.trois.common.model.entity.Report.ItemWiseRRF',
    REPORT_ITEM_WISE_RRF_EXPORT: 'in.trois.common.model.entity.Report.ItemWiseRRF.Export',
    REPORT_ITEM_WISE_SALE: 'in.trois.common.model.entity.Report.ItemWiseSale',
    REPORT_ITEM_WISE_SALE_EXPORT: 'in.trois.common.model.entity.Report.ItemWiseSale.Export',
    REPORT_ITEM_WISE_STOCK: 'in.trois.common.model.entity.Report.ItemWiseStock',
    REPORT_ITEM_WISE_STOCK_EXPORT: 'in.trois.common.model.entity.Report.ItemWiseStock.Export',


    REPORT_REVENUE: 'in.trois.common.model.entity.Report.Revenue',
    REPORT_REVENUE_EXPORT: 'in.trois.common.model.entity.Report.Revenue.Export',

    REPORT_COMPLAINT_COMPLETION_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintCompletionResidential',
    REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintCompletionResidential.Export',
    REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintCompletionNonResidential',
    REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintCompletionNonResidential.Export',
    REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintCountEscalatedResidential',
    REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintCountEscalatedResidential.Export',
    REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintCountEscalatedNonResidential',
    REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintCountEscalatedNonResidential.Export',
    REPORT_COMPLAINT_PENDING_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintPendingResidential',
    REPORT_COMPLAINT_PENDING_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintPendingResidential.Export',
    REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.ComplaintPendingNonResidential',
    REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.ComplaintPendingNonResidential.Export',

    REPORT_PLASTIC_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlasticResidential',
    REPORT_PLASTIC_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlasticResidential.Export',
    REPORT_GLASS_RESIDENTIAL: 'in.trois.common.model.entity.Report.GlassResidential',
    REPORT_GLASS_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.GlassResidential.Export',
    REPORT_LEATHER_RESIDENTIAL: 'in.trois.common.model.entity.Report.LeatherResidential',
    REPORT_LEATHER_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.LeatherResidential.Export',
    REPORT_E_WASTE_RESIDENTIAL: 'in.trois.common.model.entity.Report.EWasteResidential',
    REPORT_E_WASTE_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.EWasteResidential.Export',

    REPORT_PLASTIC_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PlasticNonResidential',
    REPORT_PLASTIC_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PlasticNonResidential.Export',
    REPORT_GLASS_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.GlassNonResidential',
    REPORT_GLASS_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.GlassNonResidential.Export',
    REPORT_LEATHER_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.LeatherNonResidential',
    REPORT_LEATHER_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.LeatherNonResidential.Export',
    REPORT_E_WASTE_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.EWasteNonResidential',
    REPORT_E_WASTE_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.EWasteNonResidential.Export',
    REPORT_POULTRY_NON_RESIDENTIAL: 'in.trois.common.model.entity.Report.PoultryNonResidential',
    REPORT_POULTRY_NON_RESIDENTIAL_EXPORT: 'in.trois.common.model.entity.Report.PoultryNonResidential.Export'
};

const ACTION_MAPPING = {
    REPORT: {
        ACCESS_IN_WEB_NAV: 'REPORT_ACCESS_IN_WEB_NAV'
    },
    REPORT_DOOR_STATUS: {
        ACCESS_IN_WEB_NAV: 'REPORT_DOOR_STATUS_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_DOOR_STATUS_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_DOOR_STATUS_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_DOOR_STATUS_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_DOOR_STATUS_EXPORT: {
        PDF: 'REPORT_DOOR_STATUS_EXPORT_AS_PDF',
        EXCEL: 'REPORT_DOOR_STATUS_EXPORT_AS_EXCEL'
    },
    REPORT_SURVEY_COUNT: {
        ACCESS_IN_WEB_NAV: 'REPORT_SURVEY_COUNT_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SURVEY_COUNT_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SURVEY_COUNT_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SURVEY_COUNT_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SURVEY_COUNT_EXPORT: {
        PDF: 'REPORT_SURVEY_COUNT_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SURVEY_COUNT_EXPORT_AS_EXCEL'
    },
    REPORT_ADVANCE_STATUS: {
        ACCESS_IN_WEB_NAV: 'REPORT_ADVANCE_STATUS_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_ADVANCE_STATUS_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_ADVANCE_STATUS_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_ADVANCE_STATUS_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_ADVANCE_STATUS_EXPORT: {
        PDF: 'REPORT_ADVANCE_STATUS_EXPORT_AS_PDF',
        EXCEL: 'REPORT_ADVANCE_STATUS_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_COMPLETION_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_COMPLETION_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_COMPLETION_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_COMPLETION_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_COUNT_ESCALATED_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_PENDING_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_PENDING_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_PENDING_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_PENDING_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_PENDING_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_SERVICE_PENDING_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_SERVICE_PENDING_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_SERVICE_PENDING_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PLAN_ENABLED_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLAN_ENABLED_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLAN_ENABLED_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLAN_ENABLED_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLAN_ENABLED_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLAN_ENABLED_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLAN_ENABLED_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLAN_ENABLED_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PLAN_ENABLED_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLAN_ENABLED_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLAN_ENABLED_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PLAN_DISABLED_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLAN_DISABLED_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLAN_DISABLED_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLAN_DISABLED_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLAN_DISABLED_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLAN_DISABLED_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLAN_DISABLED_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLAN_DISABLED_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PLAN_DISABLED_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLAN_DISABLED_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLAN_DISABLED_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PAYMENT_COLLECTED_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PAYMENT_COLLECTED_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PAYMENT_COLLECTED_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PAYMENT_COLLECTED_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PAYMENT_DUE_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PAYMENT_DUE_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PAYMENT_DUE_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PAYMENT_DUE_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PAYMENT_DUE_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PAYMENT_DUE_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PAYMENT_DUE_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PAYMENT_DUE_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PAYMENT_DUE_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PAYMENT_DUE_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PAYMENT_DUE_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_ITEM_WISE_MCF: {
        ACCESS_IN_WEB_NAV: 'REPORT_ITEM_WISE_MCF_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_ITEM_WISE_MCF_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_ITEM_WISE_MCF_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_ITEM_WISE_MCF_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_ITEM_WISE_MCF_EXPORT: {
        PDF: 'REPORT_ITEM_WISE_MCF_EXPORT_AS_PDF',
        EXCEL: 'REPORT_ITEM_WISE_MCF_EXPORT_AS_EXCEL'
    },
    REPORT_ITEM_WISE_RRF: {
        ACCESS_IN_WEB_NAV: 'REPORT_ITEM_WISE_RRF_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_ITEM_WISE_RRF_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_ITEM_WISE_RRF_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_ITEM_WISE_RRF_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_ITEM_WISE_RRF_EXPORT: {
        PDF: 'REPORT_ITEM_WISE_RRF_EXPORT_AS_PDF',
        EXCEL: 'REPORT_ITEM_WISE_RRF_EXPORT_AS_EXCEL'
    },
    REPORT_ITEM_WISE_SALE: {
        ACCESS_IN_WEB_NAV: 'REPORT_ITEM_WISE_SALE_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_ITEM_WISE_SALE_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_ITEM_WISE_SALE_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_ITEM_WISE_SALE_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_ITEM_WISE_SALE_EXPORT: {
        PDF: 'REPORT_ITEM_WISE_SALE_EXPORT_AS_PDF',
        EXCEL: 'REPORT_ITEM_WISE_SALE_EXPORT_AS_EXCEL'
    },
    REPORT_ITEM_WISE_STOCK: {
        ACCESS_IN_WEB_NAV: 'REPORT_ITEM_WISE_STOCK_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_ITEM_WISE_STOCK_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_ITEM_WISE_STOCK_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_ITEM_WISE_STOCK_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_ITEM_WISE_STOCK_EXPORT: {
        PDF: 'REPORT_ITEM_WISE_STOCK_EXPORT_AS_PDF',
        EXCEL: 'REPORT_ITEM_WISE_STOCK_EXPORT_AS_EXCEL'
    },
    REPORT_REVENUE: {
        ACCESS_IN_WEB_NAV: 'REPORT_REVENUE_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_REVENUE_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_REVENUE_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_REVENUE_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_REVENUE_EXPORT: {
        PDF: 'REPORT_REVENUE_EXPORT_AS_PDF',
        EXCEL: 'REPORT_REVENUE_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_COMPLETION_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_COMPLETION_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_COMPLETION_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_COUNT_ESCALATED_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_COUNT_ESCALATED_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_PENDING_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_PENDING_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_PENDING_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_COMPLAINT_PENDING_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_PLASTIC_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLASTIC_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLASTIC_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLASTIC_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLASTIC_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLASTIC_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLASTIC_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLASTIC_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_GLASS_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_GLASS_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_GLASS_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_GLASS_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_GLASS_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_GLASS_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_GLASS_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_GLASS_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_LEATHER_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_LEATHER_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_LEATHER_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_LEATHER_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_LEATHER_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_LEATHER_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_LEATHER_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_LEATHER_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_E_WASTE_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_E_WASTE_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_E_WASTE_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_E_WASTE_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_E_WASTE_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_E_WASTE_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_E_WASTE_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_E_WASTE_RESIDENTIAL_EXPORT_AS_EXCEL'
    },

    REPORT_PLASTIC_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_PLASTIC_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_PLASTIC_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_PLASTIC_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_PLASTIC_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_PLASTIC_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_PLASTIC_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_PLASTIC_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_GLASS_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_GLASS_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_GLASS_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_GLASS_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_GLASS_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_GLASS_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_GLASS_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_GLASS_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_LEATHER_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_LEATHER_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_LEATHER_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_LEATHER_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_LEATHER_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_LEATHER_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_LEATHER_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_LEATHER_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_E_WASTE_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_E_WASTE_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_E_WASTE_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_E_WASTE_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_E_WASTE_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_E_WASTE_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_E_WASTE_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_E_WASTE_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    },
    REPORT_POULTRY_NON_RESIDENTIAL: {
        ACCESS_IN_WEB_NAV: 'REPORT_POULTRY_NON_RESIDENTIAL_ACCESS_IN_WEB_NAV',
        TABLE_COLUMN: 'REPORT_POULTRY_NON_RESIDENTIAL_ACCESS_IN_TABLE_COLUMN',
        TABLE_FILTER: 'REPORT_POULTRY_NON_RESIDENTIAL_ACCESS_IN_TABLE_FILTER',
        TABLE_EXPORT: 'REPORT_POULTRY_NON_RESIDENTIAL_ACCESS_IN_TABLE_EXPORT'
    },
    REPORT_POULTRY_NON_RESIDENTIAL_EXPORT: {
        PDF: 'REPORT_POULTRY_NON_RESIDENTIAL_EXPORT_AS_PDF',
        EXCEL: 'REPORT_POULTRY_NON_RESIDENTIAL_EXPORT_AS_EXCEL'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
