const RESOURCE_MAPPING = {
    ROLES: 'in.trois.common.model.entity.Roles',
    ROLES_REGULAR: 'in.trois.common.model.entity.Roles.RegularRole',
    ROLES_REGULAR_DETAILS: 'in.trois.common.model.entity.Roles.RegularRole.Details',
    ROLES_REGULAR_PERMISSION: 'in.trois.common.model.entity.Roles.RegularRole.Permission',
    ROLES_REGULAR_ASSIGNEE: 'in.trois.common.model.entity.Roles.RegularRole.Assignee',
    ROLES_REGULAR_DATA_ACCESS: 'in.trois.common.model.entity.Roles.RegularRole.DataAccess',
    ROLES_ORGANIZATIONAL: 'in.trois.common.model.entity.Roles.OrganizationalRole',
    ROLES_ORGANIZATIONAL_DETAILS: 'in.trois.common.model.entity.Roles.OrganizationalRole.Details',
    ROLES_ORGANIZATIONAL_PERMISSION: 'in.trois.common.model.entity.Roles.OrganizationalRole.Permission',
    ROLES_ORGANIZATIONAL_ASSIGNEE: 'in.trois.common.model.entity.Roles.OrganizationalRole.Assignee',
    ROLES_ORGANIZATIONAL_DATA_ACCESS: 'in.trois.common.model.entity.Roles.OrganizationalRole.DataAccess'
};

const ACTION_MAPPING = {
    ROLES: {
        ACCESS_IN_WEB_NAV: 'ROLES_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'ROLES_READ_ONLY'
    },
    ROLES_REGULAR: {
        ACCESS_IN_TAB: 'ROLES_REGULAR_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_REGULAR_READ_ONLY',
        LIST: 'ROLES_REGULAR_LIST',
        ADD: 'ROLES_REGULAR_ADD',
        VIEW_IN_ACTION: 'ROLES_REGULAR_LIST_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ROLES_REGULAR_LIST_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ROLES_REGULAR_LIST_DELETE_IN_ACTION'
    },
    ROLES_REGULAR_DETAILS: {
        ACCESS_IN_TAB: 'ROLES_REGULAR_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_REGULAR_DETAILS_READ_ONLY'
    },
    ROLES_REGULAR_PERMISSION: {
        ACCESS_IN_TAB: 'ROLES_REGULAR_PERMISSION_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_REGULAR_PERMISSION_READ_ONLY'
    },
    ROLES_REGULAR_ASSIGNEE: {
        ACCESS_IN_TAB: 'ROLES_REGULAR_ASSIGNEE_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_REGULAR_ASSIGNEE_READ_ONLY',
        USER_BELONG_TO_CURRENT_ROLE: 'ROLES_REGULAR_ASSIGNEE_USER_BELONG_TO_CURRENT_ROLE',
        USER_DONT_HAVE_ANY_ROLE_ASSOCIATION: 'ROLES_REGULAR_ASSIGNEE_USER_DONT_HAVE_ANY_ROLE_ASSOCIATION'
    },
    ROLES_REGULAR_DATA_ACCESS: {
        ACCESS_IN_TAB: 'ROLES_REGULAR_DATA_ACCESS_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_REGULAR_DATA_ACCESS_READ_ONLY'
    },
    ROLES_ORGANIZATIONAL: {
        ACCESS_IN_TAB: 'ROLES_ORGANIZATIONAL_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_ORGANIZATIONAL_READ_ONLY',
        LIST: 'ROLES_ORGANIZATIONAL_LIST',
        ADD: 'ROLES_ORGANIZATIONAL_ADD',
        VIEW_IN_ACTION: 'ROLES_ORGANIZATIONAL_LIST_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'ROLES_ORGANIZATIONAL_LIST_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'ROLES_ORGANIZATIONAL_LIST_DELETE_IN_ACTION'
    },
    ROLES_ORGANIZATIONAL_DETAILS: {
        ACCESS_IN_TAB: 'ROLES_ORGANIZATIONAL_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_ORGANIZATIONAL_DETAILS_READ_ONLY'
    },
    ROLES_ORGANIZATIONAL_PERMISSION: {
        ACCESS_IN_TAB: 'ROLES_ORGANIZATIONAL_PERMISSION_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_ORGANIZATIONAL_PERMISSION_READ_ONLY'
    },
    ROLES_ORGANIZATIONAL_ASSIGNEE: {
        ACCESS_IN_TAB: 'ROLES_ORGANIZATIONAL_ASSIGNEE_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_ORGANIZATIONAL_ASSIGNEE_READ_ONLY',
        USER_BELONG_TO_CURRENT_ROLE: 'ROLES_ORGANIZATIONAL_ASSIGNEE_USER_BELONG_TO_CURRENT_ROLE',
        USER_DONT_HAVE_ANY_ROLE_ASSOCIATION: 'ROLES_ORGANIZATIONAL_ASSIGNEE_USER_DONT_HAVE_ANY_ROLE_ASSOCIATION'

    },
    ROLES_ORGANIZATIONAL_DATA_ACCESS: {
        ACCESS_IN_TAB: 'ROLES_ORGANIZATIONAL_DATA_ACCESS_ACCESS_IN_TAB',
        READ_ONLY: 'ROLES_ORGANIZATIONAL_DATA_ACCESS_READ_ONLY'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
