const RESOURCE_MAPPING = {
    SCHEDULE: 'in.trois.common.model.entity.Schedule',
    SCHEDULE_CREATE_SCHEDULE: 'in.trois.common.model.entity.Schedule.CreateSchedule',
    SCHEDULE_LIST_SCHEDULE: 'in.trois.common.model.entity.Schedule.ListSchedule',
    SCHEDULE_LIST_SCHEDULE_DETAILS: 'in.trois.common.model.entity.Schedule.ListSchedule.Details',
    SCHEDULE_LIST_SCHEDULE_ADD_CUSTOMER: 'in.trois.common.model.entity.Schedule.ListSchedule.AddCustomer',
    SCHEDULE_LIST_SCHEDULE_REMOVE_CUSTOMER: 'in.trois.common.model.entity.Schedule.ListSchedule.RemoveCustomer',
    SCHEDULE_LIST_SCHEDULE_SHOW_HISTORY: 'in.trois.common.model.entity.Schedule.ListSchedule.ShowHistory'
};

const ACTION_MAPPING = {
    SCHEDULE: {
        ACCESS_IN_WEB_NAV: 'SCHEDULE_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'SCHEDULE_READ_ONLY'
    },
    SCHEDULE_CREATE_SCHEDULE: {
        ACCESS_IN_TAB: 'SCHEDULE_CREATE_SCHEDULE_ACCESS_IN_TAB',
        READ_ONLY: 'SCHEDULE_CREATE_SCHEDULE_READ_ONLY',
        SHOW_ADVANCED_FILTER: 'SCHEDULE_CREATE_SCHEDULE_SHOW_ADVANCED_FILTER'
    },
    SCHEDULE_LIST_SCHEDULE: {
        ACCESS_IN_TAB: 'SCHEDULE_LIST_SCHEDULE_ACCESS_IN_TAB',
        READ_ONLY: 'SCHEDULE_LIST_SCHEDULE_READ_ONLY',
        LIST: 'SCHEDULE_LIST_SCHEDULE_LIST',
        VIEW_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_DELETE_IN_ACTION',
        ADD_CUSTOMER_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_ADD_CUSTOMER_IN_ACTION',
        REMOVE_CUSTOMER_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_REMOVE_CUSTOMER_IN_ACTION',
        SHOW_HISTORY_IN_ACTION: 'SCHEDULE_LIST_SCHEDULE_SHOW_HISTORY_IN_ACTION'
    },
    SCHEDULE_LIST_SCHEDULE_DETAILS: {
        READ_ONLY: 'SCHEDULE_LIST_SCHEDULE_DETAILS_READ_ONLY',
        SHOW_ADVANCED_FILTER: 'SCHEDULE_LIST_SCHEDULE_DETAILS_SHOW_ADVANCED_FILTER'
    },
    SCHEDULE_LIST_SCHEDULE_ADD_CUSTOMER: {
        READ_ONLY: 'SCHEDULE_LIST_SCHEDULE_ADD_CUSTOMER_READ_ONLY',
        ALL_SELECTED: 'SCHEDULE_LIST_SCHEDULE_ADD_CUSTOMER_ALL_SELECTED'
    },
    SCHEDULE_LIST_SCHEDULE_REMOVE_CUSTOMER: {
        READ_ONLY: 'SCHEDULE_LIST_SCHEDULE_REMOVE_CUSTOMER_READ_ONLY',
        ALL_SELECTED: 'SCHEDULE_LIST_SCHEDULE_REMOVE_CUSTOMER_ALL_SELECTED'
    },
    SCHEDULE_LIST_SCHEDULE_SHOW_HISTORY: {
        LIST: 'SCHEDULE_LIST_SCHEDULE_SHOW_HISTORY_LIST'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
