const RESOURCE_MAPPING = {
    TEMPLATE: 'in.trois.common.model.entity.Template',
    TEMPLATE_DETAILS: 'in.trois.common.model.entity.Template.Details',
    TEMPLATE_FRAGMENT: 'in.trois.common.model.entity.Template.Fragment',
    TEMPLATE_FRAGMENT_DETAILS: 'in.trois.common.model.entity.Template.Fragment.Details',
    TEMPLATE_ROUTE: 'in.trois.common.model.entity.Template.Route',
    TEMPLATE_ROUTE_DETAILS: 'in.trois.common.model.entity.Template.Route.Details',
    TEMPLATE_CURRENT_ASSOCIATION: 'in.trois.common.model.entity.Template.CurrentAssociation',
    TEMPLATE_CURRENT_ASSOCIATION_QUESTION: 'in.trois.common.model.entity.Template.CurrentAssociation.Question',
    TEMPLATE_CURRENT_ASSOCIATION_FRAGMENT: 'in.trois.common.model.entity.Template.CurrentAssociation.Fragment',
    TEMPLATE_CURRENT_ASSOCIATION_TITLE: 'in.trois.common.model.entity.Template.CurrentAssociation.Title'
};

const ACTION_MAPPING = {
    TEMPLATE: {
        ACCESS_IN_WEB_NAV: 'TEMPLATE_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'TEMPLATE_READ_ONLY',
        LIST: 'TEMPLATE_LIST',
        ADD: 'TEMPLATE_ADD',
        VIEW_IN_ACTION: 'TEMPLATE_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'TEMPLATE_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'TEMPLATE_DELETE_IN_ACTION'
    },
    TEMPLATE_DETAILS: {
        ACCESS_IN_TAB: 'TEMPLATE_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_DETAILS_READ_ONLY'
    },
    TEMPLATE_FRAGMENT: {
        ACCESS_IN_TAB: 'TEMPLATE_FRAGMENT_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_FRAGMENT_READ_ONLY',
        LIST: 'TEMPLATE_FRAGMENT_LIST',
        ADD: 'TEMPLATE_FRAGMENT_ADD',
        VIEW_IN_ACTION: 'TEMPLATE_FRAGMENT_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'TEMPLATE_FRAGMENT_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'TEMPLATE_FRAGMENT_DELETE_IN_ACTION'
    },
    TEMPLATE_FRAGMENT_DETAILS: {
        ACCESS_IN_TAB: 'TEMPLATE_FRAGMENT_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_FRAGMENT_DETAILS_READ_ONLY'
    },
    TEMPLATE_ROUTE: {
        ACCESS_IN_TAB: 'TEMPLATE_ROUTE_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_ROUTE_READ_ONLY',
        LIST: 'TEMPLATE_ROUTE_LIST',
        VIEW_IN_ACTION: 'TEMPLATE_ROUTE_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'TEMPLATE_ROUTE_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'TEMPLATE_ROUTE_DELETE_IN_ACTION'
    },
    TEMPLATE_ROUTE_DETAILS: {
        ACCESS_IN_TAB: 'TEMPLATE_ROUTE_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_ROUTE_DETAILS_READ_ONLY'
    },
    TEMPLATE_CURRENT_ASSOCIATION: {
        ACCESS_IN_TAB: 'TEMPLATE_CURRENT_ASSOCIATION_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_CURRENT_ASSOCIATION_READ_ONLY'
    },
    TEMPLATE_CURRENT_ASSOCIATION_QUESTION: {
        ACCESS_IN_TAB: 'TEMPLATE_CURRENT_ASSOCIATION_QUESTION_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_CURRENT_ASSOCIATION_QUESTION_READ_ONLY'
    },
    TEMPLATE_CURRENT_ASSOCIATION_FRAGMENT: {
        ACCESS_IN_TAB: 'TEMPLATE_CURRENT_ASSOCIATION_FRAGMENT_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_CURRENT_ASSOCIATION_FRAGMENT_READ_ONLY'
    },
    TEMPLATE_CURRENT_ASSOCIATION_TITLE: {
        ACCESS_IN_TAB: 'TEMPLATE_CURRENT_ASSOCIATION_TITLE_ACCESS_IN_TAB',
        READ_ONLY: 'TEMPLATE_CURRENT_ASSOCIATION_TITLE_READ_ONLY'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
