const RESOURCE_MAPPING = {
    TITLE: 'in.trois.common.model.entity.Title',
    TITLE_DETAILS: 'in.trois.common.model.entity.Title.Details',
    TITLE_QUESTION: 'in.trois.common.model.entity.Title.Question',
    TITLE_QUESTION_VALIDATION: 'in.trois.common.model.entity.Title.QuestionValidation',
    TITLE_QUESTION_OPTION_ASSOCIATION: 'in.trois.common.model.entity.Title.QuestionOptionAssociation',
    TITLE_CURRENT_ASSOCIATION: 'in.trois.common.model.entity.Title.CurrentAssociation',
    TITLE_CURRENT_ASSOCIATION_QUESTION: 'in.trois.common.model.entity.Title.CurrentAssociation.Question',
    TITLE_CURRENT_ASSOCIATION_FRAGMENT: 'in.trois.common.model.entity.Title.CurrentAssociation.Fragment',
    TITLE_CURRENT_ASSOCIATION_TEMPLATE: 'in.trois.common.model.entity.Title.CurrentAssociation.Template'
};

const ACTION_MAPPING = {
    TITLE: {
        ACCESS_IN_WEB_NAV: 'TITLE_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'TITLE_READ_ONLY',
        LIST: 'TITLE_LIST',
        ADD: 'TITLE_ADD',
        VIEW_IN_ACTION: 'TITLE_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'TITLE_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'TITLE_DELETE_IN_ACTION'
    },
    TITLE_DETAILS: {
        ACCESS_IN_TAB: 'TITLE_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_DETAILS_READ_ONLY'
    },
    TITLE_QUESTION: {
        ACCESS_IN_TAB: 'TITLE_QUESTION_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_QUESTION_READ_ONLY'
    },
    TITLE_QUESTION_VALIDATION: {
        ACCESS_IN_TAB: 'TITLE_QUESTION_VALIDATION_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_QUESTION_VALIDATION_READ_ONLY'
    },
    TITLE_QUESTION_OPTION_ASSOCIATION: {
        ACCESS_IN_TAB: 'TITLE_QUESTION_OPTION_ASSOCIATION_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_QUESTION_OPTION_ASSOCIATION_READ_ONLY'
    },
    TITLE_CURRENT_ASSOCIATION: {
        ACCESS_IN_TAB: 'TITLE_CURRENT_ASSOCIATION_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_CURRENT_ASSOCIATION_READ_ONLY'
    },
    TITLE_CURRENT_ASSOCIATION_QUESTION: {
        ACCESS_IN_TAB: 'TITLE_CURRENT_ASSOCIATION_QUESTION_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_CURRENT_ASSOCIATION_QUESTION_READ_ONLY'
    },
    TITLE_CURRENT_ASSOCIATION_FRAGMENT: {
        ACCESS_IN_TAB: 'TITLE_CURRENT_ASSOCIATION_FRAGMENT_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_CURRENT_ASSOCIATION_FRAGMENT_READ_ONLY'
    },
    TITLE_CURRENT_ASSOCIATION_TEMPLATE: {
        ACCESS_IN_TAB: 'TITLE_CURRENT_ASSOCIATION_TEMPLATE_ACCESS_IN_TAB',
        READ_ONLY: 'TITLE_CURRENT_ASSOCIATION_TEMPLATE_READ_ONLY'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
