const RESOURCE_MAPPING = {
    USER_GROUP: 'in.trois.common.model.entity.UserGroup',
    USER_GROUP_DETAILS: 'in.trois.common.model.entity.UserGroup.Details',
    USER_GROUP_ASSIGN_USER: 'in.trois.common.model.entity.UserGroup.AssignUser'
};

const ACTION_MAPPING = {
    USER_GROUP: {
        ACCESS_IN_WEB_NAV: 'USER_GROUP_ACCESS_IN_WEB_NAV',
        READ_ONLY: 'USER_GROUP_READ_ONLY',
        LIST: 'USER_GROUP_LIST',
        ADD: 'USER_GROUP_ADD',
        VIEW_IN_ACTION: 'USER_GROUP_LIST_VIEW_IN_ACTION',
        EDIT_IN_ACTION: 'USER_GROUP_LIST_EDIT_IN_ACTION',
        DELETE_IN_ACTION: 'USER_GROUP_LIST_DELETE_IN_ACTION'
    },
    USER_GROUP_DETAILS: {
        ACCESS_IN_TAB: 'USER_GROUP_DETAILS_ACCESS_IN_TAB',
        READ_ONLY: 'USER_GROUP_DETAILS_READ_ONLY'
    },
    USER_GROUP_ASSIGN_USER: {
        ACCESS_IN_TAB: 'USER_GROUP_ASSIGN_USER_ACCESS_IN_TAB',
        USER_BELONG_TO_CURRENT_USER_GROUP: 'USER_GROUP_ASSIGN_USER_USER_BELONG_TO_CURRENT_USER_GROUP',
        USER_DONT_HAVE_ANY_USER_GROUP_ASSOCIATION: 'USER_GROUP_ASSIGN_USER_USER_DONT_HAVE_ANY_USER_GROUP_ASSOCIATION'
    }
};

export default { RESOURCE_MAPPING, ACTION_MAPPING };
