import { action } from '../../common';
export const types = {
    FETCH_ORGANIZATION_DETAILS: 'GenQR/FETCH_ORGANIZATION_DETAILS',
    FETCH_ORGANIZATION_DETAILS_REQUEST: 'GenQR/FETCH_ORGANIZATION_DETAILS_REQUEST',
    FETCH_ORGANIZATION_DETAILS_SUCCESS: 'GenQR/FETCH_ORGANIZATION_DETAILS_SUCCESS',
    FETCH_ORGANIZATION_DETAILS_FAILURE: 'GenQR/FETCH_ORGANIZATION_DETAILS_FAILURE',

    GENERATE_QR_CODE_DATA: 'GenQR/GENERATE_QR_CODE_DATA',
    GENERATE_QR_CODE_DATA_REQUEST: 'GenQR/GENERATE_QR_CODE_DATA_REQUEST',
    GENERATE_QR_CODE_DATA_SUCCESS: 'GenQR/GENERATE_QR_CODE_DATA_SUCCESS',
    GENERATE_QR_CODE_DATA_FAILURE: 'GenQR/GENERATE_QR_CODE_DATA_FAILURE',

    CLEAR_GENERATED_QR_CODE_DATA: 'GenQR/CLEAR_GENERATED_QR_CODE_DATA'
};
export const fetchOrganizationDetails = () => action(types.FETCH_ORGANIZATION_DETAILS);
export const generateQRCodeData = (data) => action(types.GENERATE_QR_CODE_DATA, { data });
export const clearGeneratedQRCodeData = () => action(types.CLEAR_GENERATED_QR_CODE_DATA);
