const STATE_REDUCER_KEY = 'ServiceChargeSlab';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };

export const TABLE_IDS = {
    LIST_SERVICE_CHARGE_SLAB: 'LIST_SERVICE_CHARGE_SLAB'
};
