import { action } from '../../common';
export const types = {
    FETCH_SERVICE_DETAILS: 'FETCH_SERVICE_DETAILS',
    FETCH_SERVICE_DETAILS_REQUEST: 'FETCH_SERVICE_DETAILS_REQUEST',
    FETCH_SERVICE_DETAILS_SUCCESS: 'FETCH_SERVICE_DETAILS_SUCCESS',
    FETCH_SERVICE_DETAILS_FAILURE: 'FETCH_SERVICE_DETAILS_FAILURE',

    CLEAR_SERVICE_DETAILS_REDUCER: 'CLEAR_SERVICE_DETAILS_REDUCER'

};
export const fetchServiceDetails = (data) => action(types.FETCH_SERVICE_DETAILS, { data });
export const clearServiceReducer = () => action(types.CLEAR_SERVICE_DETAILS_REDUCER);

