import { action } from '../../common';
export const types = {
    FETCH_CKC_PICKUP_DETAILS: 'CKC/FETCH_PICKUP_DETAILS',
    FETCH_CKC_PICKUP_DETAILS_REQUEST: 'CKC/FETCH_PICKUP_DETAILS_REQUEST',
    FETCH_CKC_PICKUP_DETAILS_SUCCESS: 'CKC/FETCH_PICKUP_DETAILS_SUCCESS',
    FETCH_CKC_PICKUP_DETAILS_FAILURE: 'CKC/FETCH_PICKUP_DETAILS_FAILURE',

    FETCH_CKC_SALES_DETAILS: 'CKC/FETCH_SALES_DETAILS',
    FETCH_CKC_SALES_DETAILS_REQUEST: 'CKC/FETCH_SALES_DETAILS_REQUEST',
    FETCH_CKC_SALES_DETAILS_SUCCESS: 'CKC/FETCH_SALES_DETAILS_SUCCESS',
    FETCH_CKC_SALES_DETAILS_FAILURE: 'CKC/FETCH_SALES_DETAILS_FAILURE',

    FETCH_CKC_ITEMS: 'CKC/FETCH_ITEMS',
    FETCH_CKC_ITEMS_REQUEST: 'CKC/FETCH_ITEMS_REQUEST',
    FETCH_CKC_ITEMS_SUCCESS: 'CKC/FETCH_ITEMS_SUCCESS',
    FETCH_CKC_ITEMS_FAILURE: 'CKC/FETCH_ITEMS_FAILURE'
};
export const fetchSalesDetails = (data) => action(types.FETCH_CKC_SALES_DETAILS, { data });

export const fetchPickupDetails = (data) => action(types.FETCH_CKC_PICKUP_DETAILS, { data });

export const fetchCKCItems = (data) => action(types.FETCH_CKC_ITEMS, { data });
