const STATE_REDUCER_KEY = 'complaintConfig';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_COMPLAINT_CONFIG: 'LIST_COMPLAINT_CONFIG'
};
