import { action } from '../../common';
export const types = {
    FETCH_ITEM_DETAILS: 'BasicConfig/FETCH_ITEM_DETAILS',
    FETCH_ITEM_DETAILS_REQUEST: 'BasicConfig/FETCH_ITEM_DETAILS_REQUEST',
    FETCH_ITEM_DETAILS_SUCCESS: 'BasicConfig/FETCH_ITEM_DETAILS_SUCCESS',
    FETCH_ITEM_DETAILS_FAILURE: 'BasicConfig/FETCH_ITEM_DETAILS_FAILURE',

    FETCH_ITEM_DETAILS_BY_ID: 'BasicConfig/FETCH_ITEM_DETAILS_BY_ID',
    FETCH_ITEM_DETAILS_BY_ID_REQUEST: 'BasicConfig/FETCH_ITEM_DETAILS_BY_ID_REQUEST',
    FETCH_ITEM_DETAILS_BY_ID_SUCCESS: 'BasicConfig/FETCH_ITEM_DETAILS_BY_ID_SUCCESS',
    FETCH_ITEM_DETAILS_BY_ID_FAILURE: 'BasicConfig/FETCH_ITEM_DETAILS_BY_ID_FAILURE',

    SAVE_ITEM_DETAILS: 'BasicConfig/SAVE_ITEM_DETAILS',
    SAVE_ITEM_DETAILS_REQUEST: 'BasicConfig/SAVE_ITEM_DETAILS_REQUEST',
    SAVE_ITEM_DETAILS_SUCCESS: 'BasicConfig/SAVE_ITEM_DETAILS_SUCCESS',
    SAVE_ITEM_DETAILS_FAILURE: 'BasicConfig/SAVE_ITEM_DETAILS_FAILURE',

    UPDATE_ITEM_DETAILS: 'BasicConfig/UPDATE_ITEM_DETAILS',
    UPDATE_ITEM_DETAILS_REQUEST: 'BasicConfig/UPDATE_ITEM_DETAILS_REQUEST',
    UPDATE_ITEM_DETAILS_SUCCESS: 'BasicConfig/UPDATE_ITEM_DETAILS_SUCCESS',
    UPDATE_ITEM_DETAILS_FAILURE: 'BasicConfig/UPDATE_ITEM_DETAILS_FAILURE',

    DELETE_ITEM_DETAILS: 'BasicConfig/DELETE_ITEM_DETAILS',
    DELETE_ITEM_DETAILS_REQUEST: 'BasicConfig/DELETE_ITEM_DETAILS_REQUEST',
    DELETE_ITEM_DETAILS_SUCCESS: 'BasicConfig/DELETE_ITEM_DETAILS_SUCCESS',
    DELETE_ITEM_DETAILS_FAILURE: 'BasicConfig/DELETE_ITEM_DETAILS_FAILURE',

    CLEAR_ITEM_DETAILS_REDUCER: 'BasicConfig/CLEAR_ITEM_DETAILS_REDUCER',

    //fetch sub category item details
    FETCH_SUB_CATEGORY_ITEM_DETAILS: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_DETAILS',
    FETCH_SUB_CATEGORY_ITEM_DETAILS_REQUEST: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_DETAILS_REQUEST',
    FETCH_SUB_CATEGORY_ITEM_DETAILS_SUCCESS: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_DETAILS_SUCCESS',
    FETCH_SUB_CATEGORY_ITEM_DETAILS_FAILURE: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_DETAILS_FAILURE',

    //save sub category item details
    SAVE_SUB_CATEGORY_ITEM_DETAILS: 'BasicConfig/SAVE_SUB_CATEGORY_ITEM_DETAILS',
    SAVE_SUB_CATEGORY_ITEM_DETAILS_REQUEST: 'BasicConfig/SAVE_SUB_CATEGORY_ITEM_DETAILS_REQUEST',
    SAVE_SUB_CATEGORY_ITEM_DETAILS_SUCCESS: 'BasicConfig/SAVE_SUB_CATEGORY_ITEM_DETAILS_SUCCESS',
    SAVE_SUB_CATEGORY_ITEM_DETAILS_FAILURE: 'BasicConfig/SAVE_SUB_CATEGORY_ITEM_DETAILS_FAILURE',

    //fetch sub category item by id details
    FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS',
    FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_REQUEST: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_REQUEST',
    FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_SUCCESS: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_SUCCESS',
    FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_FAILURE: 'BasicConfig/FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS_FAILURE',

    //delete sub category item by id details
    DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS: 'BasicConfig/DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS',
    DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_REQUEST: 'BasicConfig/DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_REQUEST',
    DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_SUCCESS: 'BasicConfig/DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_SUCCESS',
    DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_FAILURE: 'BasicConfig/DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS_FAILURE'

};
export const fetchItemDetails = (data) => action(types.FETCH_ITEM_DETAILS, { data });
export const saveItemData = (data) => action(types.SAVE_ITEM_DETAILS, { data });
export const updatesItemData = (id, data) => action(types.UPDATE_ITEM_DETAILS, { id, data });
export const deleteItemData = (data, size, page) => action(types.DELETE_ITEM_DETAILS, { data, size, page });
export const fetchItemById = (data) => action(types.FETCH_ITEM_DETAILS_BY_ID, { data });
export const clearItemReducer = () => action(types.CLEAR_ITEM_DETAILS_REDUCER);
//fetch sub category item details
export const fetchSubCategoryItems = () => action(types.FETCH_SUB_CATEGORY_ITEM_DETAILS);
//save sub category item details
export const saveSubCategoryItems = (id, itemSubCatId) => action(types.SAVE_SUB_CATEGORY_ITEM_DETAILS, { id, itemSubCatId });
//fetch sub category item by id details
export const fetchSubCategoryItemsById = (id) => action(types.FETCH_SUB_CATEGORY_ITEM_BY_ID_DETAILS, { id });
//delete sub category item by id details
export const deleteItemSubCategoryById = (id, itemSubCategoryId) => action(types.DELETE_SUB_CATEGORY_ITEM_BY_ID_DETAILS, { id, itemSubCategoryId });
