import { action } from '../../common';
export const types = {
    FETCH_REPORTED_BUGS_DETAILS: 'FETCH_REPORTED_BUGS_DETAILS',
    FETCH_REPORTED_BUGS_DETAILS_REQUEST: 'FETCH_REPORTED_BUGS_DETAILS_REQUEST',
    FETCH_REPORTED_BUGS_DETAILS_SUCCESS: 'FETCH_REPORTED_BUGS_DETAILS_SUCCESS',
    FETCH_REPORTED_BUGS_DETAILS_FAILURE: 'FETCH_REPORTED_BUGS_DETAILS_FAILURE'

};
export const fetchReportedBugsDetails = (data) => action(types.FETCH_REPORTED_BUGS_DETAILS, { data });
