import { action } from '../../common';

export const types = {
    CHANGE_CHART_CONFIGURATION: 'Dashboard/CHANGE_CHART_CONFIGURATION',
    SET_CHART_DATA: 'Dashboard/SET_CHART_DATA',
    CHANGE_FILTER: 'Dashboard/CHANGE_FILTER',
    CUSTOMER_CARD_COUNT: 'Dashboard/CUSTOMER_CARD_COUNT',
    CUSTOMER_CARD_COUNT_REQUEST: 'Dashboard/CUSTOMER_CARD_COUNT_REQUEST',
    CUSTOMER_CARD_COUNT_SUCCESS: 'Dashboard/CUSTOMER_CARD_COUNT_SUCCESS',
    CUSTOMER_CARD_COUNT_FAILURE: 'Dashboard/CUSTOMER_CARD_COUNT_FAILURE',
    RESET_DASHBOARD: 'Dashboard/RESET_DASHBOARD',

    SERVICE_CARD_COUNT: 'Dashboard/SERVICE_CARD_COUNT',
    SERVICE_CARD_COUNT_REQUEST: 'Dashboard/SERVICE_CARD_COUNT_REQUEST',
    SERVICE_CARD_COUNT_SUCCESS: 'Dashboard/SERVICE_CARD_COUNT_SUCCESS',
    SERVICE_CARD_COUNT_FAILURE: 'Dashboard/SERVICE_CARD_COUNT_FAILURE',

    TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS: 'Dashboard/TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS',
    TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_REQUEST: 'Dashboard/TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_REQUEST',
    TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_SUCCESS: 'Dashboard/TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_SUCCESS',
    TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_FAILURE: 'Dashboard/TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS_FAILURE',

    SERVICE_CREATED_VS_SERVICE_EXECUTED: 'Dashboard/SERVICE_CREATED_VS_SERVICE_EXECUTED',
    SERVICE_CREATED_VS_SERVICE_EXECUTED_REQUEST: 'Dashboard/SERVICE_CREATED_VS_SERVICE_EXECUTED_REQUEST',
    SERVICE_CREATED_VS_SERVICE_EXECUTED_SUCCESS: 'Dashboard/SERVICE_CREATED_VS_SERVICE_EXECUTED_SUCCESS',
    SERVICE_CREATED_VS_SERVICE_EXECUTED_FAILURE: 'Dashboard/SERVICE_CREATED_VS_SERVICE_EXECUTED_FAILURE',

    CHART_PIE_CUSTOMERS_REGISTERED: 'Dashboard/CHART_PIE_CUSTOMERS_REGISTERED',
    CHART_PIE_CUSTOMERS_REGISTERED_REQUEST: 'Dashboard/CHART_PIE_CUSTOMERS_REGISTERED_REQUEST',
    CHART_PIE_CUSTOMERS_REGISTERED_SUCCESS: 'Dashboard/CHART_PIE_CUSTOMERS_REGISTERED_SUCCESS',
    CHART_PIE_CUSTOMERS_REGISTERED_FAILURE: 'Dashboard/CHART_PIE_CUSTOMERS_REGISTERED_FAILURE',

    TOTAL_WASTE_PER_CATEGORY: 'Dashboard/TOTAL_WASTE_PER_CATEGORY',
    TOTAL_WASTE_PER_CATEGORY_REQUEST: 'Dashboard/TOTAL_WASTE_PER_CATEGORY_REQUEST',
    TOTAL_WASTE_PER_CATEGORY_SUCCESS: 'Dashboard/TOTAL_WASTE_PER_CATEGORY_SUCCESS',
    TOTAL_WASTE_PER_CATEGORY_FAILURE: 'Dashboard/TOTAL_WASTE_PER_CATEGORY_FAILURE',

    TIME_TAKEN_TO_SERVICE: 'Dashboard/TIME_TAKEN_TO_SERVICE',
    TIME_TAKEN_TO_SERVICE_REQUEST: 'Dashboard/TIME_TAKEN_TO_SERVICE_REQUEST',
    TIME_TAKEN_TO_SERVICE_SUCCESS: 'Dashboard/TIME_TAKEN_TO_SERVICE_SUCCESS',
    TIME_TAKEN_TO_SERVICE_FAILURE: 'Dashboard/TIME_TAKEN_TO_SERVICE_FAILURE',

    TIME_TAKEN_TO_SERVICE_PER_CUSTOMER: 'Dashboard/TIME_TAKEN_TO_SERVICE_PER_CUSTOMER',
    TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_REQUEST: 'Dashboard/TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_REQUEST',
    TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_SUCCESS: 'Dashboard/TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_SUCCESS',
    TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_FAILURE: 'Dashboard/TIME_TAKEN_TO_SERVICE_PER_CUSTOMER_FAILURE'
};

export const changeChartConfiguration = (data) => action(types.CHANGE_CHART_CONFIGURATION, { data });
export const changeFilter = (data) => action(types.CHANGE_FILTER, { data });
export const setChartData = (data) => action(types.SET_CHART_DATA, { data });
export const getCustomerCount = (data) => action(types.CUSTOMER_CARD_COUNT, { data });
export const getServiceCount = (data) => action(types.SERVICE_CARD_COUNT, { data });
export const getTotalAndPlanEnabledCustomers = (data) => action(types.TOTAL_CUSTOMERS_VS_PLAN_ENABLED_CUSTOMERS, { data });
export const getServiceCreatedAndRegistered = (data) => action(types.SERVICE_CREATED_VS_SERVICE_EXECUTED, { data });
export const getCustomersRegistered = (data) => action(types.CHART_PIE_CUSTOMERS_REGISTERED, { data });
export const getTotalWastePerCategory = (data) => action(types.TOTAL_WASTE_PER_CATEGORY, { data });
export const getTimeTakenToService = (data) => action(types.TIME_TAKEN_TO_SERVICE, { data });
export const getTimeTakenToServicePerCustomer = (data) => action(types.TIME_TAKEN_TO_SERVICE_PER_CUSTOMER, { data });
export const resetDashboard = () => action(types.RESET_DASHBOARD);
