
const STATE_REDUCER_KEY = 'userGroup';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
const TABLE_IDS = {
    LIST_USER_GROUP: 'LIST_USER_GROUP',
    ASSIGN_USERS_IN_USER_GROUP: 'ASSIGN_USERS_IN_USER_GROUP'
};

export { STATE_REDUCER_KEY, REQUEST_STATUS, TABLE_IDS };

