export default {
    PROFILE: '/admin/index/profile',
    USER: '/admin/index/user',
    LANDING_PAGE: '/admin/index',

    ORGANIZATION: '/admin/index/organization',
    USER_GROUP: '/admin/index/user-group',
    ROLE: '/admin/index/role',
    REG_ROLE: '/admin/index/regular-role',
    ORG_ROLE: '/admin/index/organization-role',
    MODULE: '/admin/index/module',
    DYNAMIC_QUESTION: '/admin/index/dynamic-forms',
    DYNAMIC_TITLE: '/admin/index/title',
    DYNAMIC_FRAGMENT: '/admin/index/fragment',
    DYNAMIC_TEMPLATE: '/admin/index/dynamic-template',
    CUSTOMER_DATA: '/admin/index/customers',
    GENERATE_QR_CODE: '/admin/index/generate-QR-code',
    SCHEDULE: '/admin/index/schedule',
    SPECIAL_SERVICE_REQUEST: '/admin/index/specialServiceRequest',
    BASIC_CONFIG_MCF: '/admin/index/mcf',
    SUBSCRIPTION_REQUEST: '/admin/index/subscriptionRequest',
    CUSTOMER_DATA_CORRECTION: '/admin/index/customerDataCorrection',
    VIEW_CUSTOMER_DATA_CORRECTION: '/admin/index/customerDataCorrection/view',
    PAYMENT: '/admin/index/Payment',
    SUBSCRIPTION: '/admin/index/subscription',
    SERVICE: '/admin/index/service',
    SERVICE_HISTORY: '/admin/index/serviceHistory',
    COMPLAINT: '/admin/index/Complaint',
    REPORTED_BUGS: '/admin/index/reportedBugs',
    INCIDENTS: '/admin/index/incidents',
    RRF_SALES: '/admin/index/RRF-sales',
    RRF_SHREDDED: '/admin/index/RRF-shredded',

    RRF_STOCK_IN: '/admin/index/RRF-stockIn',
    CKC_SALES: '/admin/index/CKC-sales',
    CKC_PICKUP: '/admin/index/CKC-pickup',
    MCF_STOCK_IN: '/admin/index/stockIn',
    MCF_SEGGREGATION: '/admin/index/mcf-seggregation',

    MCF_STOCK_TRANSFER: '/admin/index/stockTransfer',
    MCF_STOCK_SALE: '/admin/index/stockSale',
    COMPLAINT_CONFIG: '/admin/index/complaintConfig',
    INCIDENT_CONFIG: '/admin/index/incidentConfig',
    MAP_ROUTING: '/admin/index/map-routing',
    MAP_LIVE_TRACING: '/admin/index/map-live-tracking',
    MAP_GEO_FENCE_TRACKING: '/admin/index/geo-fence-live-tracking'

};
