const STATE_REDUCER_KEY = 'role';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
const ORGANIZATION_ROLE = 0;
const REGULAR_ROLE = 1;

const TABLE_IDS = {
    LIST_REGULAR_ROLE: 'LIST_REGULAR_ROLE',
    LIST_ORGANIZATIONAL_ROLE: 'LIST_ORGANIZATIONAL_ROLE',
    LIST_ASSIGN_ROLE_TO_USER: 'LIST_ASSIGN_ROLE_TO_USER'


};

export { STATE_REDUCER_KEY, REQUEST_STATUS, ORGANIZATION_ROLE, REGULAR_ROLE, TABLE_IDS };
