const STATE_REDUCER_KEY = 'terraceFarmingType';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_TERRACE_FARMING: 'LIST_TERRACE_FARMING'
};
