import { action } from '../../common';

export const types = {
    FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION: 'DataAccess/FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION',
    FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_REQUEST: 'DataAccess/FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_REQUEST',
    FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_SUCCESS: 'DataAccess/FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_SUCCESS',
    FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_FAILURE: 'DataAccess/FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_FAILURE',

    SET_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION: 'DataAccess/SET_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION',
    REMOVE_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM: 'DataAccess/REMOVE_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM',
    ADD_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM: 'DataAccess/ADD_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM',
    REMOVE_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM: 'DataAccess/REMOVE_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM',
    ADD_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM: 'DataAccess/ADD_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM',
    SET_USER_ROLE_DATA_ACCESS_PERMISSION: 'DataAccess/SET_USER_ROLE_DATA_ACCESS_PERMISSION',

    FETCH_USER_ROLE_DATA_ACCESS_PERMISSION: 'DataAccess/FETCH_USER_ROLE_DATA_ACCESS_PERMISSION',
    FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_REQUEST: 'DataAccess/FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_REQUEST',
    FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_SUCCESS: 'DataAccess/FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_SUCCESS',
    FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_FAILURE: 'DataAccess/FETCH_USER_ROLE_DATA_ACCESS_PERMISSION_FAILURE',

    FETCH_ALL_LOCAL_BODIES: 'DataAccess/FETCH_ALL_LOCAL_BODIES',
    FETCH_ALL_LOCAL_BODIES_REQUEST: 'DataAccess/FETCH_ALL_LOCAL_BODIES_REQUEST',
    FETCH_ALL_LOCAL_BODIES_SUCCESS: 'DataAccess/FETCH_ALL_LOCAL_BODIES_SUCCESS',
    FETCH_ALL_LOCAL_BODIES_FAILURE: 'DataAccess/FETCH_ALL_LOCAL_BODIES_FAILURE',

    FETCH_ALL_WARDS: 'DataAccess/FETCH_ALL_WARDS',
    FETCH_ALL_WARDS_REQUEST: 'DataAccess/FETCH_ALL_WARDS_REQUEST',
    FETCH_ALL_WARDS_SUCCESS: 'DataAccess/FETCH_ALL_WARDS_SUCCESS',
    FETCH_ALL_WARDS_FAILURE: 'DataAccess/FETCH_ALL_WARDS_FAILURE',

    FETCH_ALL_RESIDENCE_CATEGORY: 'DataAccess/FETCH_ALL_RESIDENCE_CATEGORY',
    FETCH_ALL_RESIDENCE_CATEGORY_REQUEST: 'DataAccess/FETCH_ALL_RESIDENCE_CATEGORY_REQUEST',
    FETCH_ALL_RESIDENCE_CATEGORY_SUCCESS: 'DataAccess/FETCH_ALL_RESIDENCE_CATEGORY_SUCCESS',
    FETCH_ALL_RESIDENCE_CATEGORY_FAILURE: 'DataAccess/FETCH_ALL_RESIDENCE_CATEGORY_FAILURE'
};

export const fetchRoleAssigneeDataAccessPermissions = (data) => action(types.FETCH_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION, { data });

export const fetchUserRoleDataAccessPermissions = (data) => action(types.FETCH_USER_ROLE_DATA_ACCESS_PERMISSION, { data });

export const setRoleAssigneeDataAccessPermissionResponse = (data) => action(types.SET_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION, { data });

export const setUserRoleDataAccessPermissionResponse = (data) => action(types.SET_USER_ROLE_DATA_ACCESS_PERMISSION, { data });

export const removeDataAccessPermissionItem = (data) => action(types.REMOVE_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM, { data });

export const addDataAccessPermissionItem = (data) => action(types.ADD_ROLE_ASSIGNEE_DATA_ACCESS_PERMISSION_ITEM, { data });

export const fetchAllLocalBodies = (data) => action(types.FETCH_ALL_LOCAL_BODIES, { data });

export const fetchWards = (data) => action(types.FETCH_ALL_WARDS, { data });

export const fetchResidenceCategories = (data) => action(types.FETCH_ALL_RESIDENCE_CATEGORY, { data });

export const removeUserDataAccessPermissionItem = (data) => action(types.REMOVE_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM, { data });

export const addUserDataAccessPermissionItem = (data) => action(types.ADD_USER_ROLE_DATA_ACCESS_PERMISSION_ITEM, { data });
