const STATE_REDUCER_KEY = 'incidentConfig';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };

export const TABLE_IDS = {
    LIST_INCIDENT: 'LIST_INCIDENT_CONFIG'
};
