import { action } from '../../common';

export const types = {
    LIST_PUBLIC_GATHERING_METHOD: 'ServiceCategory/LIST_PUBLIC_GATHERING_METHOD',
    LIST_PUBLIC_GATHERING_METHOD_REQUEST: 'ServiceCategory/LIST_PUBLIC_GATHERING_METHOD_REQUEST',
    LIST_PUBLIC_GATHERING_METHOD_SUCCESS: 'ServiceCategory/LIST_PUBLIC_GATHERING_METHOD_SUCCESS',
    LIST_PUBLIC_GATHERING_METHOD_FAILURE: 'ServiceCategory/LIST_PUBLIC_GATHERING_METHOD_FAILURE',

    SENT_PUBLIC_GATHERING_METHOD: 'ServiceCategory/SENT_PUBLIC_GATHERING_METHOD',
    SENT_PUBLIC_GATHERING_METHOD_REQUEST: 'ServiceCategory/SENT_PUBLIC_GATHERING_METHOD_REQUEST',
    SENT_PUBLIC_GATHERING_METHOD_SUCCESS: 'ServiceCategory/SENT_PUBLIC_GATHERING_METHOD_SUCCESS',
    SENT_PUBLIC_GATHERING_METHOD_FAILURE: 'ServiceCategory/SENT_PUBLIC_GATHERING_METHOD_FAILURE',

    EDIT_PUBLIC_GATHERING_METHOD: 'ServiceCategory/EDIT_PUBLIC_GATHERING_METHOD',
    EDIT_PUBLIC_GATHERING_METHOD_REQUEST: 'ServiceCategory/EDIT_PUBLIC_GATHERING_METHOD_REQUEST',
    EDIT_PUBLIC_GATHERING_METHOD_SUCCESS: 'ServiceCategory/EDIT_PUBLIC_GATHERING_METHOD_SUCCESS',
    EDIT_PUBLIC_GATHERING_METHOD_FAILURE: 'ServiceCategory/EDIT_PUBLIC_GATHERING_METHOD_FAILURE',

    GET_PUBLIC_GATHERING_METHOD_BY_ID: 'ServiceCategory/GET_PUBLIC_GATHERING_METHOD_BY_ID',
    GET_PUBLIC_GATHERING_METHOD_BY_ID_REQUEST: 'ServiceCategory/GET_PUBLIC_GATHERING_METHOD_BY_ID_REQUEST',
    GET_PUBLIC_GATHERING_METHOD_BY_ID_SUCCESS: 'ServiceCategory/GET_PUBLIC_GATHERING_METHOD_BY_ID_SUCCESS',
    GET_PUBLIC_GATHERING_METHOD_BY_ID_FAILURE: 'ServiceCategory/GET_PUBLIC_GATHERING_METHOD_BY_ID_FAILRUE',
    DELETE_PUBLIC_GATHERING_METHOD: 'ServiceCategory/DELETE_PUBLIC_GATHERING_METHOD',
    DELETE_PUBLIC_GATHERING_METHOD_REQUEST: 'ServiceCategory/DELETE_PUBLIC_GATHERING_METHOD_REQUEST',
    DELETE_PUBLIC_GATHERING_METHOD_SUCCESS: 'ServiceCategory/DELETE_PUBLIC_GATHERING_METHOD_SUCCESS',
    DELETE_PUBLIC_GATHERING_METHOD_FAILURE: 'ServiceCategory/DELETE_PUBLIC_GATHERING_METHOD_FAILURE',
    RESET_SERVICE_FORM: 'ServiceCategory/RESET_SERVICE_FORM'

};

export const listPublicGatheringMethod = (data) => action(types.LIST_PUBLIC_GATHERING_METHOD, { data });

export const sentPublicGatheringMethod = (data) => action(types.SENT_PUBLIC_GATHERING_METHOD, { data });
export const editPublicGatheringMethod = (id, data) => action(types.EDIT_PUBLIC_GATHERING_METHOD, { id, data });


export const getPublicGatheringMethodById = (id) => action(types.GET_PUBLIC_GATHERING_METHOD_BY_ID, { id });

export const deletePublicGatheringMethod = (data, page, size, count) => action(types.DELETE_PUBLIC_GATHERING_METHOD, { data, page, size, count });

export const resetPublicGatheringMethodForm = () => action(types.RESET_SERVICE_FORM);

