const STATE_REDUCER_KEY = 'PublicGatheringMethod';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_PUBLIC_GATHERING_METHOD: 'LIST_PUBLIC_GATHERING_METHOD'
};
