import { action } from '../../common';
export const types = {
    FETCH_SERVICE_HISTORY_DETAILS: 'FETCH_SERVICE_HISTORY_DETAILS',
    FETCH_SERVICE_HISTORY_DETAILS_REQUEST: 'FETCH_SERVICE_HISTORY_DETAILS_REQUEST',
    FETCH_SERVICE_HISTORY_DETAILS_SUCCESS: 'FETCH_SERVICE_HISTORY_DETAILS_SUCCESS',
    FETCH_SERVICE_HISTORY_DETAILS_FAILURE: 'FETCH_SERVICE_HISTORY_DETAILS_FAILURE',

    CLEAR_SERVICE_HISTORY_DETAILS_REDUCER: 'CLEAR_SERVICE_HISTORY_DETAILS_REDUCER',
    SET_FILTER_VALUES: 'SET_FILTER_VALUES',
    RESET_FILTER_VALUES: 'RESET_FILTER_VALUES',

    LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER: 'LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER',
    LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_REQUEST: 'LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_REQUEST',
    LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_SUCCESS: 'LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_SUCCESS',
    LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_FAILURE: 'LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER_FAILURE',
    STORE_JSON_DATA_FOR_SERVICE_HISTORY: 'STORE_JSON_DATA_FOR_SERVICE_HISTORY',

    FETCH_SERVICE_HISTORY_DETAILS_BY_ID: 'FETCH_SERVICE_HISTORY_DETAILS_BY_ID',
    FETCH_SERVICE_HISTORY_DETAILS_BY_ID_REQUEST: 'FETCH_SERVICE_HISTORY_DETAILS_BY_ID_REQUEST',
    FETCH_SERVICE_HISTORY_DETAILS_BY_ID_SUCCESS: 'FETCH_SERVICE_HISTORY_DETAILS_BY_ID_SUCCESS',
    FETCH_SERVICE_HISTORY_DETAILS_BY_ID_FAILURE: 'FETCH_SERVICE_HISTORY_DETAILS_BY_ID_FAILURE',

    EDIT_SERVICE_HISTORY: 'ServiceHistory/EDIT_SERVICE_HISTORY'

};
export const fetchServiceHistoryDetails = () => action(types.FETCH_SERVICE_HISTORY_DETAILS);
export const clearServiceHistoryReducer = () => action(types.CLEAR_SERVICE_HISTORY_DETAILS_REDUCER);

export const setFilter = (data) => action(types.SET_FILTER_VALUES, { data });
export const resetFilter = () => action(types.RESET_FILTER_VALUES);
export const listJsonDataForServiceHistory = (searchValue, searchKey, columnName) => action(types.LIST_JSON_DATA_FOR_SERVICE_HISTORY_FILTER, { searchValue, searchKey, columnName });
export const storeJsonDataForServiceHistory = (data) => action(types.STORE_JSON_DATA_FOR_SERVICE_HISTORY, { data });

export const fetchServiceHistoryDetailsById = (data) => action(types.FETCH_SERVICE_HISTORY_DETAILS_BY_ID, { data });

export const editServiceHistory = (data) => action(types.EDIT_SERVICE_HISTORY, { data });

