export const STATE_REDUCER_KEY = 'listServiceHistory';

export const TEMPLATE_FOR_API = [
    1
];
export const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export const TABLE_IDS = {
    LIST_SERVICE_HISTORY: 'LIST_SERVICE_HISTORY'
};

export const EMPTY_VALUE = '-';

export const QUESTION_TYPES = {
    DROPDOWN: 'DROPDOWN',
    MULTI_DROPDOWN: 'MULTI_DROPDOWN',
    OPTION: 'OPTION',
    IMAGE: 'IMAGE',
    QR_CODE: 'QR_CODE',
    LOCATION: 'LOCATION',
    WARD: 'WARD',
    RESIDENTIAL_ASSOCIATION: 'RESIDENTIAL_ASSOCIATION',
    TRADING_TYPE: 'TRADING_TYPE',
    SHOP_TYPE: 'SHOP_TYPE',
    BUILDING_TYPE: 'BUILDING_TYPE',
    OPTION_WITH_ICON: 'OPTION_WITH_ICON',
    DATE_TIME: 'DATETIME',
    ASSOCIATION_TYPE: 'ASSOCIATION_TYPE'
};

export const DROPDOWN_TYPES = [
    QUESTION_TYPES.DROPDOWN,
    QUESTION_TYPES.MULTI_DROPDOWN,
    QUESTION_TYPES.OPTION,
    QUESTION_TYPES.OPTION_WITH_ICON,
    QUESTION_TYPES.WARD,
    QUESTION_TYPES.RESIDENTIAL_ASSOCIATION,
    QUESTION_TYPES.TRADING_TYPE,
    QUESTION_TYPES.ASSOCIATION_TYPE
];

export const IMAGE_TYPES = [QUESTION_TYPES.IMAGE];

