import { action } from '../../common';


export const types = {
    LOAD_LANGUAGES_FOR_TITLE: 'LOAD_LANGUAGES_FOR_TITLE',
    LOAD_LANGUAGES_FOR_TITLE_REQUEST: 'LOAD_LANGUAGES_FOR_TITLE_REQUEST',
    LOAD_LANGUAGES_FOR_TITLE_SUCCESS: 'LOAD_LANGUAGES_FOR_TITLE_SUCCESS',
    LOAD_LANGUAGES_FOR_TITLE_FAILURE: 'LOAD_LANGUAGES_FOR_TITLE_FAILURE',

    SENT_LABEL_FOR_TITLE: 'SENT_LABEL_FOR_TITLE',
    SENT_LABEL_FOR_TITLE_REQUEST: 'SENT_LABEL_FOR_TITLE_REQUEST',
    SENT_LABEL_FOR_TITLE_SUCCESS: 'SENT_LABEL_FOR_TITLE_SUCCESS',
    SENT_LABEL_FOR_TITLE_FAILURE: 'SENT_LABEL_FOR_TITLE_FAILURE',

    LIST_QUESTION_TYPE: 'LIST_QUESTION_TYPE',
    LIST_QUESTION_TYPE_REQUEST: 'LIST_QUESTION_TYPE_REQUEST',
    LIST_QUESTION_TYPE_SUCCESS: 'LIST_QUESTION_TYPE_REQUEST_SUCCESS',
    LIST_QUESTION_TYPE_FAILURE: 'LIST_QUESTION_TYPE_FAILURE',

    SENT_QUESTION_WITH_SORT_ORDER: 'SENT_QUESTION_WITH_SORT_ORDER',
    SENT_QUESTION_WITH_SORT_ORDER_REQUEST: 'SENT_QUESTION_WITH_SORT_ORDER_REQUEST',
    SENT_QUESTION_WITH_SORT_ORDER_SUCCESS: 'SENT_QUESTION_WITH_SORT_ORDER_SUCCESS',
    SENT_QUESTION_WITH_SORT_ORDER_FAILURE: 'SENT_QUESTION_WITH_SORT_ORDER_FAILURE',

    LIST_TITLE_PAGEBALE: 'LIST_TITLE_PAGEBALE',
    LIST_TITLE_PAGEBALE_REQUEST: 'LIST_TITLE_PAGEBALE_REQUEST',
    LIST_TITLE_PAGEBALE_SUCCESS: 'LIST_TITLE_PAGEBALE_SUCCESS',
    LIST_TITLE_PAGEBALE_FAILURE: 'LIST_TITLE_PAGEBALE_FAILURE',

    DELETE_TITLE: 'DELETE_TITLE',
    DELETE_TITLE_REQUEST: 'DELETE_TITLE_RREQUEST',
    DELETE_TITLE_SUCCCESS: 'DELETE_TITLE_SUCCESS',
    DELETE_TITLE_FAILURE: 'DELETE_TITLE_FAILURE',


    GET_LABELS_WITH_ID: 'GET_LABELS_WITH_ID',
    GET_LABELS_WITH_ID_REQUEST: 'GET_LABELS_WITH_ID_REQUEST',
    GET_LABELS_WITH_ID_SUCCESS: 'GET_LABELS_WITH_ID_SUCCESS',
    GET_LABELS_WITH_ID_FAILURE: 'GET_LABELS_WITH_ID_FAILURE',

    SENT_LABELS_FOR_EDIT: 'SENT_LABELS_FOR_EDIT',
    SENT_LABELS_FOR_EDIT_REQUEST: 'SENT_LABELS_FOR_EDIT_REQUEST',
    SENT_LABELS_FOR_EDIT_SUCCESS: 'SENT_LABELS_FOR_EDIT_SUCCESS',
    SENT_LABELS_FOR_EDIT_FAILURE: 'SENT_LABELS_FOR_EDIT_FAILURE',

    GET_QUESTIONS_FOR_TITLE: 'GET_QUESTIONS_FOR_TITLE',
    GET_QUESTIONS_FOR_TITLE_REQUEST: 'GET_QUESTIONS_FOR_TITLE_REQUEST',
    GET_QUESTIONS_FOR_TITLE_SUCCESS: 'GET_QUESTIONS_FOR_TITLE_SUCCESS',
    GET_QUESTIONS_FOR_TITLE_FAILURE: 'GET_QUESTIONS_FOR_TITLE_FAILURE',

    GET_QUESTION_VALIDATION_TYPE: 'GET_QUESTION_VALIDATION_TYPE',
    GET_QUESTION_VALIDATION_TYPE_REQUEST: 'GET_QUESTION_VALIDATION_TYPE_REQUEST',
    GET_QUESTION_VALIDATION_TYPE_SUCCESS: 'GET_QUESTION_VALIDATION_TYPE_SUCCESS',
    GET_QUESTION_VALIDATION_TYPE_FAILURE: 'GET_QUESTION_VALIDATION_TYPE_FAILURE',

    SENT_QUESTION_VALIDATION: 'SENT_QUESTION_VALIDATION',
    SENT_QUESTION_VALIDATION_REQUEST: 'SENT_QUESTION_VALIDATION_REQUEST',
    SENT_QUESTION_VALIDATION_SUCCESS: 'SENT_QUESTION_VALIDATION_SUCCESS',
    SENT_QUESTION_VALIDATION_FAILURE: 'SENT_QUESTION_VALIDATION_FAILURE',

    GET_QUESTION_VALIDATION: 'GET_QUESTION_VALIDATION',
    GET_QUESTION_VALIDATION_REQUEST: 'GET_QUESTION_VALIDATION_REQUEST',
    GET_QUESTION_VALIDATION_SUCCESS: 'GET_QUESTION_VALIDATION_SUCCESS',
    GET_QUESTION_VALIDATION_FAILURE: 'GET_QUESTION_VALIDATION_FAILURE',

    GET_OPTION_WITH_QUESTION_ID: 'GET_OPTION_WITH_QUESTION_ID',
    GET_OPTION_WITH_QUESTION_ID_REQUEST: 'GET_OPTION_WITH_QUESTION_ID_REQUEST',
    GET_OPTION_WITH_QUESTION_ID_SUCCESS: 'GET_OPTION_WITH_QUESTION_ID_SUCCESS',
    GET_OPTION_WITH_QUESTION_ID_FAILURE: 'GET_OPTION_WITH_QUESTION_ID_FAILURE',

    SENT_QUESTION_OPTION_FOR_EDIT: 'SENT_QUESTION_OPTION_FOR_EDIT',
    SENT_QUESTION_OPTION_FOR_EDIT_REQUEST: 'SENT_QUESTION_OPTION_FOR_EDIT_REQUEST',
    SENT_QUESTION_OPTION_FOR_EDIT_SUCCESS: 'SENT_QUESTION_OPTION_FOR_EDIT_SUCCESS',
    SENT_QUESTION_OPTION_FOR_EDIT_FAILURE: 'SENT_QUESTION_OPTION_FOR_EDIT_FAILURE',

    GET_QUESTION_OPTION_VALIDATION: 'GET_QUESTION_OPTION_VALIDATION',
    GET_QUESTION_OPTION_VALIDATION_REQUEST: 'GET_QUESTION_OPTION_VALIDATION_REQUEST',
    GET_QUESTION_OPTION_VALIDATION_SUCCESS: 'GET_QUESTION_OPTION_VALIDATION_SUCCESS',
    GET_QUESTION_OPTION_VALIDATION_FAILURE: 'GET_QUESTION_OPTION_VALIDATION_FAILURE',


    GET_OPTION_QUESTIONS: 'dfgTitles/GET_OPTION_QUESTIONS',
    GET_OPTION_QUESTIONS_REQUEST: 'GET_OPTION_QUESTIONS_REQUEST',
    GET_OPTION_QUESTIONS_SUCCESS: 'GET_OPTION_QUESTIONS_SUCCESS',
    GET_OPTION_QUESTIONS_FAILURE: 'GET_OPTION_QUESTIONS_FAILURE',

    GET_TITLE_QUESTION_ONLY: 'dfgTitles/GET_TITLE_QUESTION_ONLY',
    GET_TITLE_QUESTION_ONLY_REQUEST: 'dfgTitles/GET_TITLE_QUESTION_ONLY_REQUEST',
    GET_TITLE_QUESTION_ONLY_SUCCESS: 'dfgTitles/GET_TITLE_QUESTION_ONLY_SUCCESS',
    GET_TITLE_QUESTION_ONLY_FAILURE: 'dfgTitles/GET_TITLE_QUESTION_ONLY_FAILURE',

    FETCH_TITLE_WITH_RESETTED_PAGINATION: 'dfgTitles/FETCH_TITLE_WITH_RESETTED_PAGINATION',
    FETCH_TITLE_WITH_RESETTED_PAGINATION_REQUEST: 'dfgTitles/FETCH_TITLE_WITH_RESETTED_PAGINATION_REQUEST',
    FETCH_TITLE_WITH_RESETTED_PAGINATION_SUCCESS: 'dfgTitles/FETCH_TITLE_WITH_RESETTED_PAGINATION_SUCCESS',
    FETCH_TITLE_WITH_RESETTED_PAGINATION_FAILURE: 'dfgTitles/FETCH_TITLE_WITH_RESETTED_PAGINATION_FAILURE',

    FETCH_TITLE_CURRENT_ASSOCIATION: 'dfgTitles/FETCH_TITLE_CURRENT_ASSOCIATION',
    FETCH_TITLE_CURRENT_ASSOCIATION_REQUEST: 'dfgTitles/FETCH_TITLE_CURRENT_ASSOCIATION_REQUEST',
    FETCH_TITLE_CURRENT_ASSOCIATION_SUCCESS: 'dfgTitles/FETCH_TITLE_CURRENT_ASSOCIATION_SUCCESS',
    FETCH_TITLE_CURRENT_ASSOCIATION_FAILURE: 'dfgTitles/FETCH_TITLE_CURRENT_ASSOCIATION_FAILURE',

    RESET_QUESTION_LIST: 'RESET_QUESTION_LIST',


    CLEAR_TITLE_DETAILS_REDUCER: 'dfgTitles/CLEAR_TITLE_DETAILS_REDUCER',
    STORE_JSON_DATA_FOR_TITLE: 'dfgTitles/STORE_JSON_DATA_FOR_TITLE',
    SET_TITLE_TAB_INDEX: 'DynamicForm/SET_TITLE_TAB_INDEX'


};

export const fetchQuestionValidationTypes = () => action(types.FETCH_QUESTION_VALIDATION_TYPES);
export const loadLanguagesForTitle = () => action(types.LOAD_LANGUAGES_FOR_TITLE);
export const sentTitleLabel = (data) => action(types.SENT_LABEL_FOR_TITLE, { data });
export const loadQuestions = (languageId, questionType) => action(types.LIST_QUESTION_TYPE, { languageId, questionType });
export const sentQuestionAndSortOrder = (titleId, questionArray) => action(types.SENT_QUESTION_WITH_SORT_ORDER, { titleId, questionArray });

export const listTitle = (data) => action(types.LIST_TITLE_PAGEBALE, { data });
export const deleteTitle = (id, page, size, count) => action(types.DELETE_TITLE, { id, page, size, count });
export const getLabelsForTitleWithId = (id) => action(types.GET_LABELS_WITH_ID, { id });
export const sentTitleLabelForEdit = (id, data) => action(types.SENT_LABELS_FOR_EDIT, { id, data });
export const getQuestionForTitle = (id) => action(types.GET_QUESTIONS_FOR_TITLE, { id });
export const getQuestionTitleValidation = () => action(types.GET_QUESTION_VALIDATION_TYPE);
export const sentQuestionValidation = (id, validationObject) => action(types.SENT_QUESTION_VALIDATION, { id, validationObject });
export const getQuestionValidationById = (id) => action(types.GET_QUESTION_VALIDATION, { id });
export const getOptionWitQuestionId = (id) => action(types.GET_OPTION_WITH_QUESTION_ID, { id });
export const sentQuestionOptionForEdit = (id, questionOptionObject) => action(types.SENT_QUESTION_OPTION_FOR_EDIT, { id, questionOptionObject });
export const getQuestionOptionValidationForTitle = (id) => action(types.GET_QUESTION_OPTION_VALIDATION, { id });

export const resetQuestion = () => action(types.RESET_QUESTION_LIST);
export const loadOptionQuestions = (id, typeId) => action(types.GET_OPTION_QUESTIONS, { id, typeId });

export const getTitleQuestions = (id, type) => action(types.GET_TITLE_QUESTION_ONLY, { id, type });
export const listTitleWithResettedPagination = () => action(types.FETCH_TITLE_WITH_RESETTED_PAGINATION);

export const fetchTitleCurrentAssociation = (id) => action(types.FETCH_TITLE_CURRENT_ASSOCIATION, { id });

export const clearStateReducer = () => action(types.CLEAR_TITLE_DETAILS_REDUCER);
export const setTabIndex = (data) => action(types.SET_TITLE_TAB_INDEX, { data });


