import { action } from '../../common';

export const types = {
    FETCH_SCHEDULE_BY_ID: 'schedule/FETCH_SCHEDULE_BY_ID',
    FETCH_SCHEDULE_BY_ID_REQUEST: 'schedule/FETCH_SCHEDULE_BY_ID_REQUEST',
    FETCH_SCHEDULE_BY_ID_SUCCESS: 'schedule/FETCH_SCHEDULE_BY_ID_SUCCESS',
    FETCH_SCHEDULE_BY_ID_FAILURE: 'schedule/FETCH_SCHEDULE_BY_ID_FAILURE',

    CLEAR_SCHEDULE_BY_ID: 'schedule/CLEAR_SCHEDULE_BY_ID',

    FETCH_ALL_CUSTOMERS: 'schedule/FETCH_ALL_CUSTOMERS',
    FETCH_ALL_CUSTOMERS_REQUEST: 'schedule/FETCH_ALL_CUSTOMERS_REQUEST',
    FETCH_ALL_CUSTOMERS_SUCCESS: 'schedule/FETCH_ALL_CUSTOMERS_SUCCESS',
    FETCH_ALL_CUSTOMERS_FAILURE: 'schedule/FETCH_ALL_CUSTOMERS_FAILURE',

    FETCH_ALL_ORGANIZATIONS: 'schedule/FETCH_ALL_ORGANIZATIONS',
    FETCH_ALL_ORGANIZATIONS_REQUEST: 'schedule/FETCH_ALL_ORGANIZATIONS_REQUEST',
    FETCH_ALL_ORGANIZATIONS_SUCCESS: 'schedule/FETCH_ALL_ORGANIZATIONS_SUCCESS',
    FETCH_ALL_ORGANIZATIONS_FAILURE: 'schedule/FETCH_ALL_ORGANIZATIONS_FAILURE',

    FETCH_SERVICE_PROVIDERS: 'schedule/FETCH_SERVICE_PROVIDERS',
    FETCH_SERVICE_PROVIDERS_REQUEST: 'schedule/FETCH_SERVICE_PROVIDERS_REQUEST',
    FETCH_SERVICE_PROVIDERS_SUCCESS: 'schedule/FETCH_SERVICE_PROVIDERS_SUCCESS',
    FETCH_SERVICE_PROVIDERS_FAILURE: 'schedule/FETCH_SERVICE_PROVIDERS_FAILURE',


    FETCH_SERVICE_WORKERS: 'schedule/FETCH_SERVICE_WORKERS',
    FETCH_SERVICE_WORKERS_REQUEST: 'schedule/FETCH_SERVICE_WORKERS_REQUEST',
    FETCH_SERVICE_WORKERS_SUCCESS: 'schedule/FETCH_SERVICE_WORKERS_SUCCESS',
    FETCH_SERVICE_WORKERS_FAILURE: 'schedule/FETCH_SERVICE_WORKERS_FAILURE',

    FETCH_WARDS: 'schedule/FETCH_WARDS',
    FETCH_WARDS_REQUEST: 'schedule/FETCH_WARDS_REQUEST',
    FETCH_WARDS_SUCCESS: 'schedule/FETCH_WARDS_SUCCESS',
    FETCH_WARDS_FAILURE: 'schedule/FETCH_WARDS_FAILURE',

    FETCH_SERVICE: 'schedule/FETCH_SERVICE_',
    FETCH_SERVICE_REQUEST: 'schedule/FETCH_SERVICE_REQUEST',
    FETCH_SERVICE_SUCCESS: 'schedule/FETCH_SERVICE_SUCCESS',
    FETCH_SERVICE_FAILURE: 'schedule/FETCH_SERVICE_FAILURE',

    FETCH_SERVICE_INTERVALS: 'schedule/FETCH_SERVICE_INTERVALS_',
    FETCH_SERVICE_INTERVALS_REQUEST: 'schedule/FETCH_SERVICE_INTERVALS_REQUEST',
    FETCH_SERVICE_INTERVALS_SUCCESS: 'schedule/FETCH_SERVICE_INTERVALS_SUCCESS',
    FETCH_SERVICE_INTERVALS_FAILURE: 'schedule/FETCH_SERVICE_INTERVALS_FAILURE',

    SET_SERVICE_PROVIDER: 'schedule/SET_SERVICE_PROVIDER',
    SET_WARDS: 'schedule/SET_WARDS',
    SET_SERVICE_WORKERS: 'schedule/SET_SERVICE_WORKERS',
    SET_SERVICES: 'schedule/SET_SERVICES',
    SET_SERVICE_INTERVALS: 'schedule/SET_SERVICE_INTERVALS',
    SET_RESIDENTIAL_ASSOCIATIONS: 'schedule/SET_RESIDENTIAL_ASSOCIATIONS',

    FETCH_ALL_SCHEDULE: 'schedule/FETCH_ALL_SCHEDULE',
    FETCH_ALL_SCHEDULE_REQUEST: 'schedule/FETCH_ALL_SCHEDULE_REQUEST',
    FETCH_ALL_SCHEDULE_SUCCESS: 'schedule/FETCH_ALL_SCHEDULE_SUCCESS',
    FETCH_ALL_SCHEDULE_FAILURE: 'schedule/FETCH_ALL_SCHEDULE_FAILURE',

    FETCH_RESIDENTIAL_ASSOCIATION: 'schedule/FETCH_RESIDENTIAL_ASSOCIATION',
    FETCH_RESIDENTIAL_ASSOCIATION_REQUEST: 'schedule/FETCH_RESIDENTIAL_ASSOCIATION_REQUEST',
    FETCH_RESIDENTIAL_ASSOCIATION_SUCCESS: 'schedule/FETCH_RESIDENTIAL_ASSOCIATION_SUCCESS',
    FETCH_RESIDENTIAL_ASSOCIATION_FAILURE: 'schedule/FETCH_RESIDENTIAL_ASSOCIATION_FAILURE',

    FETCH_TRADING_TYPE: 'schedule/FETCH_TRADING_TYPE',
    FETCH_TRADING_TYPE_REQUEST: 'schedule/FETCH_TRADING_TYPE_REQUEST',
    FETCH_TRADING_TYPE_SUCCESS: 'schedule/FETCH_TRADING_TYPE_SUCCESS',
    FETCH_TRADING_TYPE_FAILURE: 'schedule/FETCH_TRADING_TYPE_FAILURE',

    DELETE_SCHEDULE: 'schedule/DELETE_SCHEDULE',
    DELETE_SCHEDULE_REQUEST: 'schedule/DELETE_SCHEDULE_REQUEST',
    DELETE_SCHEDULE_SUCCESS: 'schedule/DELETE_SCHEDULE_SUCCESS',
    DELETE_SCHEDULE_FAILURE: 'schedule/DELETE_SCHEDULE_FAILURE',

    SUBMIT_SCHEDULED_CUSTOMER: 'schedule/SUBMIT_SCHEDULED_CUSTOMER',
    SUBMIT_SCHEDULED_CUSTOMER_REQUEST: 'schedule/SUBMIT_SCHEDULED_CUSTOMER_REQUEST',
    SUBMIT_SCHEDULED_CUSTOMER_SUCCESS: 'schedule/SUBMIT_SCHEDULED_CUSTOMER_SUCCESS',
    SUBMIT_SCHEDULED_CUSTOMER_FAILURE: 'schedule/SUBMIT_SCHEDULED_CUSTOMER_FAILURE',

    POST_SCHEDULE: 'schedule/POST_SCHEDULE',
    POST_SCHEDULE_REQUEST: 'schedule/POST_SCHEDULE_REQUEST',
    POST_SCHEDULE_SUCCESS: 'schedule/POST_SCHEDULE_SUCCESS',
    POST_SCHEDULE_FAILURE: 'schedule/POST_SCHEDULE_FAILURE',

    UPDATE_SCHEDULE: 'schedule/UPDATE_SCHEDULE',
    UPDATE_SCHEDULE_REQUEST: 'schedule/UPDATE_SCHEDULE_REQUEST',
    UPDATE_SCHEDULE_SUCCESS: 'schedule/UPDATE_SCHEDULE_SUCCESS',
    UPDATE_SCHEDULE_FAILURE: 'schedule/UPDATE_SCHEDULE_FAILURE',

    FETCH_CUSTOMERS_BY_SCHEDULE_ID: 'schedule/FETCH_CUSTOMERS_BY_SCHEDULE_ID',
    FETCH_CUSTOMERS_BY_SCHEDULE_ID_REQUEST: 'schedule/FETCH_CUSTOMERS_BY_SCHEDULE_ID_REQUEST',
    FETCH_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS: 'schedule/FETCH_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS',
    FETCH_CUSTOMERS_BY_SCHEDULE_ID_FAILURE: 'schedule/FETCH_CUSTOMERS_BY_SCHEDULE_ID_FAILURE',

    REMOVE_CUSTOMERS_BY_SCHEDULE_ID: 'schedule/REMOVE_CUSTOMERS_BY_SCHEDULE_ID',
    REMOVE_CUSTOMERS_BY_SCHEDULE_ID_REQUEST: 'schedule/REMOVE_CUSTOMERS_BY_SCHEDULE_ID_REQUEST',
    REMOVE_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS: 'schedule/REMOVE_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS',
    REMOVE_CUSTOMERS_BY_SCHEDULE_ID_FAILURE: 'schedule/REMOVE_CUSTOMERS_BY_SCHEDULE_ID_FAILURE',

    ADD_CUSTOMERS_BY_SCHEDULE_ID: 'schedule/ADD_CUSTOMERS_BY_SCHEDULE_ID',
    ADD_CUSTOMERS_BY_SCHEDULE_ID_REQUEST: 'schedule/ADD_CUSTOMERS_BY_SCHEDULE_ID_REQUEST',
    ADD_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS: 'schedule/ADD_CUSTOMERS_BY_SCHEDULE_ID_SUCCESS',
    ADD_CUSTOMERS_BY_SCHEDULE_ID_FAILURE: 'schedule/ADD_CUSTOMERS_BY_SCHEDULE_ID_FAILURE',

    FETCH_SCHEDULE_HISTORY: 'schedule/FETCH_SCHEDULE_HISTORY',
    FETCH_SCHEDULE_HISTORY_REQUEST: 'schedule/FETCH_SCHEDULE_HISTORY_REQUEST',
    FETCH_SCHEDULE_HISTORY_SUCCESS: 'schedule/FETCH_SCHEDULE_HISTORY_SUCCESS',
    FETCH_SCHEDULE_HISTORY_FAILURE: 'schedule/FETCH_SCHEDULE_HISTORY_FAILURE',

    FETCH_ALL_RESIDENCE_CATEGORIES: 'schedule/FETCH_ALL_RESIDENCE_CATEGORIES',
    FETCH_ALL_RESIDENCE_CATEGORIES_REQUEST: 'schedule/FETCH_ALL_RESIDENCE_CATEGORIES_REQUEST',
    FETCH_ALL_RESIDENCE_CATEGORIES_SUCCESS: 'schedule/FETCH_ALL_RESIDENCE_CATEGORIES_SUCCESS',
    FETCH_ALL_RESIDENCE_CATEGORIES_FAILURE: 'schedule/FETCH_ALL_RESIDENCE_CATEGORIES_FAILURE',

    SET_USER_ROLE_EDIT_TAB_INDEX: 'UserRole/SET_USER_ROLE_EDIT_TAB_INDEX'
};

export const serviceTypes = {
    FETCH_SPECIAL_SERVICE_LIST: 'SpecialService/FETCH_SPECIAL_SERVICE_LIST',
    FETCH_SPECIAL_SERVICE_LIST_REQUEST: 'SpecialService/FETCH_SPECIAL_SERVICE_LIST_REQUEST',
    FETCH_SPECIAL_SERVICE_LIST_SUCCESS: 'SpecialService/FETCH_SPECIAL_SERVICE_LIST_SUCCESS',
    FETCH_SPECIAL_SERVICE_LIST_FAILURE: 'SpecialService/FETCH_SPECIAL_SERVICE_LIST_FAILURE',

    PROCESS_SPECIAL_SERVICE: 'SpecialService/PROCESS_SPECIAL_SERVICE',
    PROCESS_SPECIAL_SERVICE_REQUEST: 'SpecialService/PROCESS_SPECIAL_SERVICE_REQUEST',
    PROCESS_SPECIAL_SERVICE_SUCCESS: 'SpecialService/PROCESS_SPECIAL_SERVICE_SUCCESS',
    PROCESS_SPECIAL_SERVICE_FAILURE: 'SpecialService/PROCESS_SPECIAL_SERVICE_FAILURE',

    FETCH_SPECIAL_SERVICE_SCHEDULE_DATA: 'SpecialService/FETCH_SPECIAL_SERVICE_SCHEDULE_DATA',
    FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_REQUEST: 'SpecialService/FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_REQUEST',
    FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_SUCCESS: 'SpecialService/FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_SUCCESS',
    FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_FAILURE: 'SpecialService/FETCH_SPECIAL_SERVICE_SCHEDULE_DATA_FAILURE',

    PROCESS_SPECIAL_SERVICE_SCHEDULE: 'SpecialService/PROCESS_SPECIAL_SERVICE_SCHEDULE',
    PROCESS_SPECIAL_SERVICE_SCHEDULE_REQUEST: 'SpecialService/PROCESS_SPECIAL_SERVICE_SCHEDULE_REQUEST',
    PROCESS_SPECIAL_SERVICE_SCHEDULE_SUCCESS: 'SpecialService/PROCESS_SPECIAL_SERVICE_SCHEDULE_SUCCESS',
    PROCESS_SPECIAL_SERVICE_SCHEDULE_FAILURE: 'SpecialService/PROCESS_SPECIAL_SERVICE_SCHEDULE_FAILURE',

    ASSIGN_SERVICE_WORKER: 'SpecialService/ASSIGN_SERVICE_WORKER',
    ASSIGN_SERVICE_WORKER_REQUEST: 'SpecialService/ASSIGN_SERVICE_WORKER_REQUEST',
    ASSIGN_SERVICE_WORKER_SUCCESS: 'SpecialService/ASSIGN_SERVICE_WORKER_SUCCESS',
    ASSIGN_SERVICE_WORKER_FAILURE: 'SpecialService/ASSIGN_SERVICE_WORKER_FAILURE',

    SET_CHIPS: 'SpecialService/SET_CHIPS',
    SET_PAGE_PROPS: 'SpecialService/SET_PAGE_PROPS'

};

export const fetchScheduleById = (id) => action(types.FETCH_SCHEDULE_BY_ID, { id });
export const clearSchedule = () => action(types.CLEAR_SCHEDULE_BY_ID);
export const fetchCustomers = (data) => action(types.FETCH_ALL_CUSTOMERS, { data });
export const fetchSchedules = (data) => action(types.FETCH_ALL_SCHEDULE, { data });
export const loadScheduleHistory = (data) => action(types.FETCH_SCHEDULE_HISTORY, { data });
export const deleteScheduleData = (data, loadData) => action(types.DELETE_SCHEDULE, { data, loadData });

export const fetchOrganizationsList = () => action(types.FETCH_ALL_ORGANIZATIONS);
export const fetchServiceProvidersList = (data) => action(types.FETCH_SERVICE_PROVIDERS, { data });
export const setServiceProvider = (data) => action(types.SET_SERVICE_PROVIDER, { data });
export const fetchWards = (data) => action(types.FETCH_WARDS, { data });
export const setWards = (data) => action(types.SET_WARDS, { data });
export const fetchServiceWorkers = (data) => action(types.FETCH_SERVICE_WORKERS, { data });
export const setServiceWorkers = (data) => action(types.SET_SERVICE_WORKERS, { data });
export const fetchServiceDetails = (data) => action(types.FETCH_SERVICE, { data });
export const setServices = (data) => action(types.SET_SERVICES, { data });
export const fetchServiceIntervals = (data) => action(types.FETCH_SERVICE_INTERVALS, { data });
export const setServiceIntervals = (data) => action(types.SET_SERVICE_INTERVALS, { data });
export const fetchResidentialAssociations = (data) => action(types.FETCH_RESIDENTIAL_ASSOCIATION, { data });
export const setResidentialAssociations = (data) => action(types.SET_RESIDENTIAL_ASSOCIATIONS, { data });
export const fetchTradingType = () => action(types.FETCH_TRADING_TYPE);
export const submitScheduledCustomer = (data) => action(types.SUBMIT_SCHEDULED_CUSTOMER, { data });
export const postSchedule = (data) => action(types.POST_SCHEDULE, { data });
export const updateSchedule = (data) => action(types.UPDATE_SCHEDULE, { data });
export const fetchCustomerDataByScheduleId = (data) => action(types.FETCH_CUSTOMERS_BY_SCHEDULE_ID, { data });
export const addCustomerDataByScheduleId = (data, id) => action(types.ADD_CUSTOMERS_BY_SCHEDULE_ID, { data, id });
export const removeCustomerDataByScheduleId = (data, id) => action(types.REMOVE_CUSTOMERS_BY_SCHEDULE_ID, { data, id });
export const fetchAllResidenceCategories = () => action(types.FETCH_ALL_RESIDENCE_CATEGORIES);
export const setEditTabIndex = (data) => action(types.SET_USER_ROLE_EDIT_TAB_INDEX, { data });

//Special ServiceRequest Actions
export const fetchSpecialServices = (data) => action(serviceTypes.FETCH_SPECIAL_SERVICE_LIST, { data });
export const processSpecialServiceRequest = (data) => action(serviceTypes.PROCESS_SPECIAL_SERVICE, { data });
export const fetchSpecialServiceScheduleData = (data) => action(serviceTypes.FETCH_SPECIAL_SERVICE_SCHEDULE_DATA, { data });
export const processSpecialServiceSchedule = (data) => action(serviceTypes.PROCESS_SPECIAL_SERVICE_SCHEDULE, { data });
export const setChips = (data) => action(serviceTypes.SET_CHIPS, { data });
export const setPageProps = (data) => action(serviceTypes.SET_PAGE_PROPS, { data });
export const assignSpecialServiceRequestsServiceWorker = (data) => action(serviceTypes.ASSIGN_SERVICE_WORKER, { data });
