import { action } from '../../common';
export const types = {
    FETCH_RRF_STOCK_IN_DETAILS: 'RRF/FETCH_STOCK_IN_DETAILS',
    FETCH_RRF_STOCK_IN_DETAILS_REQUEST: 'RRF/FETCH_STOCK_IN_DETAILS_REQUEST',
    FETCH_RRF_STOCK_IN_DETAILS_SUCCESS: 'RRF/FETCH_STOCK_IN_DETAILS_SUCCESS',
    FETCH_RRF_STOCK_IN_DETAILS_FAILURE: 'RRF/FETCH_STOCK_IN_DETAILS_FAILURE',

    FETCH_RRF_SALES_DETAILS: 'RRF/FETCH_SALES_DETAILS',
    FETCH_RRF_SALES_DETAILS_REQUEST: 'RRF/FETCH_SALES_DETAILS_REQUEST',
    FETCH_RRF_SALES_DETAILS_SUCCESS: 'RRF/FETCH_SALES_DETAILS_SUCCESS',
    FETCH_RRF_SALES_DETAILS_FAILURE: 'RRF/FETCH_SALES_DETAILS_FAILURE',

    FETCH_RRF_ITEMS: 'RRF/FETCH_ITEMS',
    FETCH_RRF_ITEMS_REQUEST: 'RRF/FETCH_ITEMS_REQUEST',
    FETCH_RRF_ITEMS_SUCCESS: 'RRF/FETCH_ITEMS_SUCCESS',
    FETCH_RRF_ITEMS_FAILURE: 'RRF/FETCH_ITEMS_FAILURE',

    FETCH_RRF_SHREDDED: 'RRF/FETCH_RRF_SHREDDED',
    FETCH_RRF_SHREDDED_REQUEST: 'RRF/FETCH_RRF_SHREDDED_REQUEST',
    FETCH_RRF_SHREDDED_SUCCESS: 'RRF/FETCH_RRF_SHREDDED_SUCCESS',
    FETCH_RRF_SHREDDED_FAILURE: 'RRF/FETCH_RRF_SHREDDED_FAILURE'

};
export const fetchLStockInDetails = (data) => action(types.FETCH_RRF_STOCK_IN_DETAILS, { data });
export const fetchSalesDetails = (data) => action(types.FETCH_RRF_SALES_DETAILS, { data });

export const fetchRRFItems = (data) => action(types.FETCH_RRF_ITEMS, { data });

export const fetchRrfShreddedDetails = (data) => action(types.FETCH_RRF_SHREDDED, { data });


