import { action } from '../../common';

export const types = {
    //ListTemplate
    FETCH_TEMPLATES: 'Template/FETCH_TEMPLATES',
    FETCH_TEMPLATES_REQUEST: 'Template/FETCH_TEMPLATES_REQUEST',
    FETCH_TEMPLATES_SUCCESS: 'Template/FETCH_TEMPLATES_SUCCESS',
    FETCH_TEMPLATES_FAILURE: 'Template/FETCH_TEMPLATES_FAILURE',

    DELETE_TEMPLATE: 'Template/DELETE_TEMPLATE',
    DELETE_TEMPLATE_REQUEST: 'Template/DELETE_TEMPLATE_REQUEST',
    DELETE_TEMPLATE_SUCCESS: 'Template/DELETE_TEMPLATE_SUCCESS',
    DELETE_TEMPLATE_FAILURE: 'Template/DELETE_TEMPLATE_FAILURE',

    //Add/UpdateTemplate
    SAVE_TEMPLATE: 'Template/SAVE_TEMPLATE',
    SAVE_TEMPLATE_REQUEST: 'Template/SAVE_TEMPLATE_REQUEST',
    SAVE_TEMPLATE_SUCCESS: 'Template/SAVE_TEMPLATE_SUCCESS',
    SAVE_TEMPLATE_FAILURE: 'Template/SAVE_TEMPLATE_FAILURE',

    UPDATE_TEMPLATE: 'Template/UPDATE_TEMPLATE',
    UPDATE_TEMPLATE_REQUEST: 'Template/UPDATE_TEMPLATE_REQUEST',
    UPDATE_TEMPLATE_SUCCESS: 'Template/UPDATE_TEMPLATE_SUCCESS',
    UPDATE_TEMPLATE_FAILURE: 'Template/UPDATE_TEMPLATE_FAILURE',

    FETCH_TEMPLATE_TYPE: 'Template/FETCH_TEMPLATE_TYPE',
    FETCH_TEMPLATE_TYPE_REQUEST: 'Template/FETCH_TEMPLATE_TYPE_REQUEST',
    FETCH_TEMPLATE_TYPE_SUCCESS: 'Template/FETCH_TEMPLATE_TYPE_SUCCESS',
    FETCH_TEMPLATE_TYPE_FAILURE: 'Template/FETCH_TEMPLATE_TYPE_FAILURE',

    FETCH_TEMPLATE_BY_ID: 'Template/FETCH_TEMPLATE_BY_ID',
    FETCH_TEMPLATE_BY_ID_REQUEST: 'Template/FETCH_TEMPLATE_BY_ID_REQUEST',
    FETCH_TEMPLATE_BY_ID_SUCCESS: 'Template/FETCH_TEMPLATE_BY_ID_SUCCESS',
    FETCH_TEMPLATE_BY_ID_FAILURE: 'Template/FETCH_TEMPLATE_BY_ID_FAILURE',

    //Assign Fragment to Template
    ASSIGN_FRAGMENT_TEMPLATE: 'Template/ASSIGN_FRAGMENT_TEMPLATE',
    ASSIGN_FRAGMENT_TEMPLATE_REQUEST: 'Template/ASSIGN_FRAGMENT_TEMPLATE_REQUEST',
    ASSIGN_FRAGMENT_TEMPLATE_SUCCESS: 'Template/ASSIGN_FRAGMENT_TEMPLATE_SUCCESS',
    ASSIGN_FRAGMENT_TEMPLATE_FAILURE: 'Template/ASSIGN_FRAGMENT_TEMPLATE_FAILURE',

    FETCH_ALL_FRAGMENTS: 'Template/FETCH_ALL_FRAGMENTS',
    FETCH_ALL_FRAGMENTS_REQUEST: 'Template/FETCH_ALL_FRAGMENTS_REQUEST',
    FETCH_ALL_FRAGMENTS_SUCCESS: 'Template/FETCH_ALL_FRAGMENTS_SUCCESS',
    FETCH_ALL_FRAGMENTS_FAILURE: 'Template/FETCH_ALL_FRAGMENTS_FAILURE',

    FETCH_ALL_FRAGMENTS_DROPDOWN_REQUEST: 'Template/FETCH_ALL_FRAGMENTS_DROPDOWN_REQUEST',
    FETCH_ALL_FRAGMENTS_DROPDOWN_SUCCESS: 'Template/FETCH_ALL_FRAGMENTS_DROPDOWN_SUCCESS',
    FETCH_ALL_FRAGMENTS_DROPDOWN_FAILURE: 'Template/FETCH_ALL_FRAGMENTS_DROPDOWN_FAILURE',

    FETCH_FRAGMENTS_BY_TEMPLATE: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE',
    FETCH_FRAGMENTS_BY_TEMPLATE_REQUEST: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_REQUEST',
    FETCH_FRAGMENTS_BY_TEMPLATE_SUCCESS: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_SUCCESS',
    FETCH_FRAGMENTS_BY_TEMPLATE_FAILURE: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_FAILURE',

    FETCH_ROUTES_BY_TEMPLATE: 'Template/FETCH_ROUTES_BY_TEMPLATE',
    FETCH_ROUTES_BY_TEMPLATE_REQUEST: 'Template/FETCH_ROUTES_BY_TEMPLATE_REQUEST',
    FETCH_ROUTES_BY_TEMPLATE_SUCCESS: 'Template/FETCH_ROUTES_BY_TEMPLATE_SUCCESS',
    FETCH_ROUTES_BY_TEMPLATE_FAILURE: 'Template/FETCH_ROUTES_BY_TEMPLATE_FAILURE',

    FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_REQUEST: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_REQUEST',
    FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_SUCCESS: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_SUCCESS',
    FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_FAILURE: 'Template/FETCH_FRAGMENTS_BY_TEMPLATE_DROPDOWN_FAILURE',

    DELETE_ASSIGNED_FRAGMENT: 'Template/DELETE_ASSIGNED_FRAGMENT',
    DELETE_ASSIGNED_FRAGMENT_REQUEST: 'Template/DELETE_ASSIGNED_FRAGMENT_REQUEST',
    DELETE_ASSIGNED_FRAGMENT_SUCCESS: 'Template/DELETE_ASSIGNED_FRAGMENT_SUCCESS',
    DELETE_ASSIGNED_FRAGMENT_FAILURE: 'Template/DELETE_ASSIGNED_FRAGMENT_FAILURE',

    //Routes Tab
    SAVE_TEMPLATE_ROUTES: 'Template/SAVE_TEMPLATE_ROUTES',
    SAVE_TEMPLATE_ROUTES_REQUEST: 'Template/SAVE_TEMPLATE_ROUTES_REQUEST',
    SAVE_TEMPLATE_ROUTES_SUCCESS: 'Template/SAVE_TEMPLATE_ROUTES_SUCCESS',
    SAVE_TEMPLATE_ROUTES_FAILURE: 'Template/SAVE_TEMPLATE_ROUTES_FAILURE',

    UPDATE_TEMPLATE_ROUTE_REQUEST: 'Template/UPDATE_TEMPLATE_ROUTE_REQUEST',
    UPDATE_TEMPLATE_ROUTE_SUCCESS: 'Template/UPDATE_TEMPLATE_ROUTE_SUCCESS',
    UPDATE_TEMPLATE_ROUTE_FAILURE: 'Template/UPDATE_TEMPLATE_ROUTE_FAILURE',

    FETCH_ROUTES_FROM_TEMPLATE: 'Templates/FETCH_ROUTES_FROM_TEMPLATE',
    FETCH_ROUTES_FROM_TEMPLATE_REQUEST: 'Templates/FETCH_ROUTES_FROM_TEMPLATE_REQUEST',
    FETCH_ROUTES_FROM_TEMPLATE_SUCCESS: 'Templates/FETCH_ROUTES_FROM_TEMPLATE_SUCCESS',
    FETCH_ROUTES_FROM_TEMPLATE_FAILURE: 'Templates/FETCH_ROUTES_FROM_TEMPLATE_FAILURE',

    FETCH_FRAGMENTS_BY_FRAGMENT_ID: 'Templates/FETCH_FRAGMENTS_BY_FRAGMENT_ID',
    FETCH_FRAGMENTS_BY_FRAGMENT_ID_REQUEST: 'Templates/FETCH_FRAGMENTS_BY_FRAGMENT_ID_REQUEST',
    FETCH_FRAGMENTS_BY_FRAGMENT_ID_SUCCESS: 'Templates/FETCH_FRAGMENTS_BY_FRAGMENT_ID_SUCCESS',
    FETCH_FRAGMENTS_BY_FRAGMENT_ID_FAILURE: 'Templates/FETCH_FRAGMENTS_BY_FRAGMENT_ID_FAILURE',

    FETCH_ASSIGNED_FRAGMENT: 'Templates/FETCH_ASSIGNED_FRAGMENT',
    FETCH_ASSIGNED_FRAGMENT_REQUEST: 'Templates/FETCH_ASSIGNED_FRAGMENT_REQUEST',
    FETCH_ASSIGNED_FRAGMENT_SUCCESS: 'Templates/FETCH_ASSIGNED_FRAGMENT_SUCCESS',
    FETCH_ASSIGNED_FRAGMENT_FAILURE: 'Templates/FETCH_ASSIGNED_FRAGMENT_FAILURE',

    UPDATE_ASSIGNED_FRAGMENT: 'Templates/UPDATE_ASSIGNED_FRAGMENT',
    UPDATE_ASSIGNED_FRAGMENT_REQUEST: 'Templates/UPDATE_ASSIGNED_FRAGMENT_REQUEST',
    UPDATE_ASSIGNED_FRAGMENT_SUCCESS: 'Templates/UPDATE_ASSIGNED_FRAGMENT_SUCCESS',
    UPDATE_ASSIGNED_FRAGMENT_FAILURE: 'Templates/UPDATE_ASSIGNED_FRAGMENT_FAILURE',

    //Resetting Forms
    RESET_ADD_TEMPLATE_FORM: 'Template/RESET_ADD_TEMPLATE_FORM',
    RESET_ADD_ROUTE_FORM: 'Template/RESET_ADD_ROUTE_FORM',
    RESET_ASSIGN_FRAGMENT_FORM: 'Template/RESET_ASSIGN_FRAGMENT_FORM',
    SET_TAB_INDEX: 'Template/SET_TAB_INDEX',

    SET_FRAGMENT_TO_ASSIGN_ROUTE: 'Template/SET_FRAGMENT_TO_ASSIGN_ROUTE',
    SET_FRAGMENT_TO_ASSIGN_ROUTE_REQUEST: 'Template/SET_FRAGMENT_TO_ASSIGN_ROUTE_REQUEST',
    SET_FRAGMENT_TO_ASSIGN_ROUTE_SUCCESS: 'Template/SET_FRAGMENT_TO_ASSIGN_ROUTE_SUCCESS',
    SET_FRAGMENT_TO_ASSIGN_ROUTE_FAILURE: 'Template/SET_FRAGMENT_TO_ASSIGN_ROUTE_FAILURE',

    FETCH_RESET_PAGEBLE_TEMPLATE: 'Template/FETCH_RESET_PAGEBLE_TEMPLATE',
    FETCH_RESET_PAGEBLE_TEMPLATE_REQUEST: 'Template/FETCH_RESET_PAGEBLE_TEMPLATE_REQUEST',
    FETCH_RESET_PAGEBLE_TEMPLATE_SUCCESS: 'Template/FETCH_RESET_PAGEBLE_TEMPLATE_SUCCESS',
    FETCH_RESET_PAGEBLE_TEMPLATE_FAILURE: 'Template/FETCH_RESET_PAGEBLE_TEMPLATE_FAILURE',

    FETCH_CURRENT_ASSOCIATION: 'FETCH_CURRENT_ASSOCIATION',
    FETCH_CURRENT_ASSOCIATION_REQUEST: 'FETCH_CURRENT_ASSOCIATION_REQUEST',
    FETCH_CURRENT_ASSOCIATION_SUCCESS: 'FETCH_CURRENT_ASSOCIATION_SUCCESS',
    FETCH_CURRENT_ASSOCIATION_FAILURE: 'FETCH_CURRENT_ASSOCIATION_FAILURE',
    CLEAR_TEMPLATE_DETAILS_REDUCER: 'Template/CLEAR_TEMPLATE_DETAILS_REDUCER'
};

export const fetchTemplates = (data) => action(types.FETCH_TEMPLATES, { data });

export const deleteTemplate = (data, page, size, count) => action(types.DELETE_TEMPLATE, { data, page, size, count });

export const saveTemplate = (data) => action(types.SAVE_TEMPLATE, { data });

export const fetchTemplateDetailsById = (data) => action(types.FETCH_TEMPLATE_BY_ID, { data });

export const fetchTemplateTypes = () => action(types.FETCH_TEMPLATE_TYPE);

export const assignFragmentsToTemplate = (data) => action(types.ASSIGN_FRAGMENT_TEMPLATE, { data });

export const deleteAssignedFragment = (id, templateId) => action(types.DELETE_ASSIGNED_FRAGMENT, { id, templateId });

export const fetchAllFragments = (data) => action(types.FETCH_ALL_FRAGMENTS, { data });

export const fetchFragmentsByTemplate = (data) => action(types.FETCH_FRAGMENTS_BY_TEMPLATE, { data });

export const saveTemplateRoutes = (data) => action(types.SAVE_TEMPLATE_ROUTES, { data });

export const resetAddTemplateForm = () => action(types.RESET_ADD_TEMPLATE_FORM);

export const setTabIndex = (data) => action(types.SET_TAB_INDEX, { data });

export const fetchTemplateRouteById = (id, fragmentId) => action(types.FETCH_ROUTES_FROM_TEMPLATE, { id, fragmentId });

export const fetchFragmentsByFragmentId = (data) => action(types.FETCH_FRAGMENTS_BY_FRAGMENT_ID, { data });

export const resetAddRouteForm = () => action(types.RESET_ADD_ROUTE_FORM);

//fetch Single fragment Assigned to a template by fragment id and template id
export const fetchAssignedFragment = (data) => action(types.FETCH_ASSIGNED_FRAGMENT, { data });

// reset Add/Edit fragment form
export const resetAddFragmentForm = () => action(types.RESET_ASSIGN_FRAGMENT_FORM);

export const setSelectedFragmentDetails = (data) => action(types.SET_FRAGMENT_TO_ASSIGN_ROUTE, { data });

export const fetchInitialTemplates = () => action(types.FETCH_RESET_PAGEBLE_TEMPLATE);

export const fetchCurrentAssociation = (data) => action(types.FETCH_CURRENT_ASSOCIATION, { data });

export const clearStateReducer = () => action(types.CLEAR_TEMPLATE_DETAILS_REDUCER);

export const fetchRoutesByTemplate = (data) => action(types.FETCH_ROUTES_BY_TEMPLATE, { data });


