import { action } from '../../common';

export const types = {
    LIST_ADMINISTRATION_TYPE: 'AdministrationType/LIST_ADMINISTRATION_TYPE',
    LIST_ADMINISTRATION_TYPE_REQUEST: 'AdministrationType/LIST_ADMINISTRATION_TYPE_REQUEST',
    LIST_ADMINISTRATION_TYPE_SUCCESS: 'AdministrationType/LIST_ADMINISTRATION_TYPE_SUCCESS',
    LIST_ADMINISTRATION_TYPE_FAILURE: 'AdministrationType/LIST_ADMINISTRATION_TYPE_FAILURE',

    SENT_ADMINISTRATION_TYPE: 'AdministrationType/SENT_ADMINISTRATION_TYPE',
    SENT_ADMINISTRATION_TYPE_REQUEST: 'AdministrationType/SENT_ADMINISTRATION_TYPE_REQUEST',
    SENT_ADMINISTRATION_TYPE_SUCCESS: 'AdministrationType/SENT_ADMINISTRATION_TYPE_SUCCESS',
    SENT_ADMINISTRATION_TYPE_FAILURE: 'AdministrationType/SENT_ADMINISTRATION_TYPE_FAILURE',

    EDIT_ADMINISTRATION_TYPE: 'AdministrationType/EDIT_ADMINISTRATION_TYPE',
    EDIT_ADMINISTRATION_TYPE_REQUEST: 'AdministrationType/EDIT_ADMINISTRATION_TYPE_REQUEST',
    EDIT_ADMINISTRATION_TYPE_SUCCESS: 'AdministrationType/EDIT_ADMINISTRATION_TYPE_SUCCESS',
    EDIT_ADMINISTRATION_TYPE_FAILURE: 'AdministrationType/EDIT_ADMINISTRATION_TYPE_FAILURE',

    GET_ADMINISTRATION_TYPE_BY_ID: 'AdministrationType/GET_ADMINISTRATION_TYPE_BY_ID',
    GET_ADMINISTRATION_TYPE_BY_ID_REQUEST: 'AdministrationType/GET_ADMINISTRATION_TYPE_BY_ID_REQUEST',
    GET_ADMINISTRATION_TYPE_BY_ID_SUCCESS: 'AdministrationType/GET_ADMINISTRATION_TYPE_BY_ID_SUCCESS',
    GET_ADMINISTRATION_TYPE_BY_ID_FAILURE: 'AdministrationType/GET_ADMINISTRATION_TYPE_BY_ID_FAILRUE',
    DELETE_ADMINISTRATION_TYPE: 'AdministrationType/DELETE_ADMINISTRATION_TYPE',
    DELETE_ADMINISTRATION_TYPE_REQUEST: 'AdministrationType/DELETE_ADMINISTRATION_TYPE_REQUEST',
    DELETE_ADMINISTRATION_TYPE_SUCCESS: 'AdministrationType/DELETE_ADMINISTRATION_TYPE_SUCCESS',
    DELETE_ADMINISTRATION_TYPE_FAILURE: 'AdministrationType/DELETE_ADMINISTRATION_TYPE_FAILURE',
    RESET_SERVICE_FORM: 'AdministrationType/RESET_SERVICE_FORM'

};

export const listAdministrationType = (data) => action(types.LIST_ADMINISTRATION_TYPE, { data });

export const sentAdministrationType = (data) => action(types.SENT_ADMINISTRATION_TYPE, { data });
export const editAdministrationType = (id, data) => action(types.EDIT_ADMINISTRATION_TYPE, { id, data });


export const getAdministrationTypeById = (id) => action(types.GET_ADMINISTRATION_TYPE_BY_ID, { id });

export const deleteAdministrationType = (data, page, size, count) => action(types.DELETE_ADMINISTRATION_TYPE, { data, page, size, count });

export const resetAdministrationTypeForm = () => action(types.RESET_SERVICE_FORM);

