const STATE_REDUCER_KEY = 'administrationType';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };

export const TABLE_IDS = {
    LIST_ADMINISTRATION_TYPE: 'LIST_ADMINISTRATION_TYPE'
};
