const STATE_REDUCER_KEY = 'serviceConfig';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_SERVICE_CONFIG: 'LIST_SERVICE_CONFIG'
};
