const STATE_REDUCER_KEY = 'shopType';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };

export const TABLE_IDS = {
    LIST_SHOP_TYPE: 'LIST_SHOP_TYPE'
};
