export const STATE_REDUCER_KEY = 'customers';

export const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};

export const TEMPLATE_FOR_API = [
    1
];

export const EMPTY_VALUE = '-';

export const QUESTION_TYPES = {
    DROPDOWN: 'DROPDOWN',
    MULTI_DROPDOWN: 'MULTI_DROPDOWN',
    OPTION: 'OPTION',
    IMAGE: 'IMAGE',
    QR_CODE: 'QR_CODE',
    LOCATION: 'LOCATION',
    WARD: 'WARD',
    RESIDENTIAL_ASSOCIATION: 'RESIDENTIAL_ASSOCIATION',
    TRADING_TYPE: 'TRADING_TYPE',
    SHOP_TYPE: 'SHOP_TYPE',
    BUILDING_TYPE: 'BUILDING_TYPE',
    OPTION_WITH_ICON: 'OPTION_WITH_ICON',
    DATE_TIME: 'DATETIME',
    DATE: 'DATE',
    ASSOCIATION_TYPE: 'ASSOCIATION_TYPE',
    TEXT: 'TEXT'
};

export const DROPDOWN_TYPES = [
    QUESTION_TYPES.DROPDOWN,
    QUESTION_TYPES.MULTI_DROPDOWN,
    QUESTION_TYPES.OPTION,
    QUESTION_TYPES.OPTION_WITH_ICON,
    QUESTION_TYPES.WARD,
    QUESTION_TYPES.RESIDENTIAL_ASSOCIATION,
    QUESTION_TYPES.TRADING_TYPE,
    QUESTION_TYPES.ASSOCIATION_TYPE
];

export const IMAGE_TYPES = [QUESTION_TYPES.IMAGE];

export const DISPLAY_NULL_VALUES = false;

export const COLUMN_ORDER = {
    CUSTOMER_NUMBER: 'customer_number',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_NAME: 'building_owner_name',
    DISTRICT: 'district',
    ORGANIZATION: 'organization',
    ENROLLMENT_CUSTOMER_WARD: 'ward',
    QR_CODE: 'qr_code',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'building_name',
    ENROLLMENT_CUSTOMER_PROPERTY_TYPE: 'building_type',
    ENROLLMENT_CUSTOMER_TRADING_TYPE: 'trading_type',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'door_status',
    ENROLLMENT_CUSTOMER_PROPERTY_NUMBER: 'building_number',
    ENROLLMENT_CUSTOMER_ASSOCIATION_NAME: 'association_name',
    ENROLLMENT_CUSTOMER_ASSOCIATION_NUMBER: 'association_number',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER: 'lead_person_phone',
    SURVEYOR: 'surveyor',
    SURVEY_DATE: 'enrollment_date_time'
};

export const KEYS_FOR_API = Object.keys(COLUMN_ORDER).toString();

export const TABLE_IDS = {
    LIST_SUBSCRIPTIONS: 'LIST_SUBSCRIPTIONS',
    LIST_CUSTOMERS: 'LIST_CUSTOMERS'
};

export const BASE64_APPEND = 'data:image/*;base64,';
