import { action } from '../../common';
export const types = {
    FETCH_CUSTOMER_DETAILS: 'FETCH_CUSTOMER_DETAILS',
    FETCH_CUSTOMER_DETAILS_REQUEST: 'FETCH_CUSTOMER_DETAILS_REQUEST',
    FETCH_CUSTOMER_DETAILS_SUCCESS: 'FETCH_CUSTOMER_DETAILS_SUCCESS',
    FETCH_CUSTOMER_DETAILS_FAILURE: 'FETCH_CUSTOMER_DETAILS_FAILURE',

    CLEAR_CUSTOMER_DETAILS_REDUCER: 'CLEAR_CUSTOMER_DETAILS_REDUCER',
    SET_FILTER_VALUES: 'SET_FILTER_VALUES',
    RESET_FILTER_VALUES: 'RESET_FILTER_VALUES',

    LIST_JSON_DATA_FOR_CUSTOMER_FILTER: 'LIST_JSON_DATA_FOR_CUSTOMER_FILTER',
    LIST_JSON_DATA_FOR_CUSTOMER_FILTER_REQUEST: 'LIST_JSON_DATA_FOR_CUSTOMER_FILTER_REQUEST',
    LIST_JSON_DATA_FOR_CUSTOMER_FILTER_SUCCESS: 'LIST_JSON_DATA_FOR_CUSTOMER_FILTER_SUCCESS',
    LIST_JSON_DATA_FOR_CUSTOMER_FILTER_FAILURE: 'LIST_JSON_DATA_FOR_CUSTOMER_FILTER_FAILURE',
    STORE_JSON_DATA_FOR_CUSTOMER: 'STORE_JSON_DATA_FOR_CUSTOMER',
    ADD_CUSTOMER_IDS_TO_REDUCER: 'ADD_CUSTOMER_IDS_TO_REDUCER',

    VIEW_CUSTOMER_ENROLLMENT_DETAILS: 'VIEW_CUSTOMER_ENROLLMENT_DETAILS',
    VIEW_CUSTOMER_ENROLLMENT_DETAILS_SUCESS: 'VIEW_CUSTOMER_ENROLLMENT_DETAILS_SUCCESS',
    VIEW_CUSTOMER_ENROLLMENT_DETAILS_REQUEST: 'VIEW_CUSTOMER_ENROLLMENT_DETAILS_REQUEST',
    VIEW_CUSTOMER_ENROLLMENT_DETAILS_FAILURE: 'VIEW_CUSTOMER_ENROLLMENT_DETAILS_FAILURE',

    VIEW_CUSTOMER_CONFLICT_DETAILS: 'VIEW_CUSTOMER_CONFLICT_DETAILS',
    VIEW_CUSTOMER_CONFLICT_DETAILS_SUCESS: 'VIEW_CUSTOMER_CONFLICT_DETAILS_SUCESS',
    VIEW_CUSTOMER_CONFLICT_DETAILS_REQUEST: 'VIEW_CUSTOMER_CONFLICT_DETAILS_REQUEST',
    VIEW_CUSTOMER_CONFLICT_DETAILS_FAILURE: 'VIEW_CUSTOMER_CONFLICT_DETAILS_FAILURE'


};
export const fetchCustomerDetails = (data) => action(types.FETCH_CUSTOMER_DETAILS, { data });
export const clearCustomerReducer = () => action(types.CLEAR_CUSTOMER_DETAILS_REDUCER);

export const setFilter = (data) => action(types.SET_FILTER_VALUES, { data });
export const resetFilter = () => action(types.RESET_FILTER_VALUES);
export const listJsonDataForCustomer = (searchValue, searchKey, columnName) => action(types.LIST_JSON_DATA_FOR_CUSTOMER_FILTER, { searchValue, searchKey, columnName });
export const storeJsonDataForCustomer = (data) => action(types.STORE_JSON_DATA_FOR_CUSTOMER, { data });
export const addCustomerIdsToREducer = (data) => action(types.ADD_CUSTOMER_IDS_TO_REDUCER, { data });
export const customerViewDetailsWithEnrollmentId = (data) => action(types.VIEW_CUSTOMER_ENROLLMENT_DETAILS, { data });
export const customerViewDetailsWithConflictId = (data) => action(types.VIEW_CUSTOMER_CONFLICT_DETAILS, { data });

