import { action } from '../../common';

export const types = {
    FETCH_DISTRICT_PANCHAYATH_DETAILS: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_DETAILS',
    FETCH_DISTRICT_PANCHAYATH_DETAILS_REQUEST: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_DETAILS_REQUEST',
    FETCH_DISTRICT_PANCHAYATH_DETAILS_SUCCESS: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_DETAILS_SUCCESS',
    FETCH_DISTRICT_PANCHAYATH_DETAILS_FAILURE: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_DETAILS_FAILURE',

    DELETE_DISTRICT_PANCHAYATH: 'BasicConfig/DELETE_DISTRICT_PANCHAYATH',
    DELETE_DISTRICT_PANCHAYATH_REQUEST: 'BasicConfig/DELETE_DISTRICT_PANCHAYATH_REQUEST',
    DELETE_DISTRICT_PANCHAYATH_SUCCESS: 'BasicConfig/DELETE_DISTRICT_PANCHAYATH_SUCCESS',
    DELETE_DISTRICT_PANCHAYATH_FAILURE: 'BasicConfig/DELETE_DISTRICT_PANCHAYATH_FAILURE',

    FETCH_DISTRICT_PANCHAYATH_BY_ID: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_BY_ID',
    FETCH_DISTRICT_PANCHAYATH_BY_ID_REQUEST: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_BY_ID_REQUEST',
    FETCH_DISTRICT_PANCHAYATH_BY_ID_SUCCESS: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_BY_ID_SUCCESS',
    FETCH_DISTRICT_PANCHAYATH_BY_ID_FAILURE: 'BasicConfig/FETCH_DISTRICT_PANCHAYATH_BY_ID_FAILURE',

    SAVE_DISTRICT_PANCHAYATH: 'BasicConfig/SAVE_DISTRICT_PANCHAYATH',
    SAVE_DISTRICT_PANCHAYATH_REQUEST: 'BasicConfig/SAVE_DISTRICT_PANCHAYATH_REQUEST',
    SAVE_DISTRICT_PANCHAYATH_SUCCESS: 'BasicConfig/SAVE_DISTRICT_PANCHAYATH_SUCCESS',
    SAVE_DISTRICT_PANCHAYATH_FAILURE: 'BasicConfig/SAVE_DISTRICT_PANCHAYATH_FAILURE',

    UPDATE_DISTRICT_PANCHAYATH: 'BasicConfig/UPDATE_DISTRICT_PANCHAYATH',
    UPDATE_DISTRICT_PANCHAYATH_REQUEST: 'BasicConfig/UPDATE_DISTRICT_PANCHAYATH_REQUEST',
    UPDATE_DISTRICT_PANCHAYATH_SUCCESS: 'BasicConfig/UPDATE_DISTRICT_PANCHAYATH_SUCCESS',
    UPDATE_DISTRICT_PANCHAYATH_FAILURE: 'BasicConfig/UPDATE_DISTRICT_PANCHAYATH_FAILURE',

    LIST_DISTRICT_PANCHAYATH_DISTRICT: 'BasicConfig/LIST_DISTRICT_PANCHAYATH_DISTRICT',
    LIST_DISTRICT_PANCHAYATH_DISTRICT_REQUEST: 'BasicConfig/LIST_DISTRICT_PANCHAYATH_DISTRICT_REQUEST',
    LIST_DISTRICT_PANCHAYATH_DISTRICT_SUCCESS: 'BasicConfig/LIST_DISTRICT_PANCHAYATH_DISTRICT_SUCCESS',
    LIST_DISTRICT_PANCHAYATH_DISTRICT_FAILURE: 'BasicConfig/LIST_DISTRICT_PANCHAYATH_DISTRICT_FAILURE',

    CLEAR_DISTRICT_PANCHAYATH_DETAILS_REDUCER: 'BasicConfig/CLEAR_DISTRICT_PANCHAYATH_DETAILS_REDUCER',

    CLEAR_STATE_DETAILS_REDUCER: 'BasicConfig/CLEAR_STATE_DETAILS_REDUCER'
};

export const fetchDistrictPanchayathDetails = (data) => action(types.FETCH_DISTRICT_PANCHAYATH_DETAILS, { data });
export const deleteDistrictPanchayathData = (data, size, page) => action(types.DELETE_DISTRICT_PANCHAYATH, { data, size, page });
export const fetchDistrictPanchayathById = (data) => action(types.FETCH_DISTRICT_PANCHAYATH_BY_ID, { data });
export const saveDistrictPanchayathData = (data) => action(types.SAVE_DISTRICT_PANCHAYATH, { data });
export const updateDistrictPanchayathData = (id, data) => action(types.UPDATE_DISTRICT_PANCHAYATH, { id, data });
export const fetchDistrictList = (data) => action(types.LIST_DISTRICT_PANCHAYATH_DISTRICT, { data });
export const clearReducer = () => action(types.CLEAR_DISTRICT_PANCHAYATH_DETAILS_REDUCER);
