import { action } from '../../common';
export const types = {
    FETCH_STOCK_IN_DETAILS: 'Mcf/FETCH_STOCK_IN_DETAILS',
    FETCH_STOCK_IN_DETAILS_REQUEST: 'Mcf/FETCH_STOCK_IN_DETAILS_REQUEST',
    FETCH_STOCK_IN_DETAILS_SUCCESS: 'Mcf/FETCH_STOCK_IN_DETAILS_SUCCESS',
    FETCH_STOCK_IN_DETAILS_FAILURE: 'Mcf/FETCH_STOCK_IN_DETAILS_FAILURE',

    FETCH_STOCK_TRANSFER_DETAILS: 'Mcf/FETCH_STOCK_TRANSFER_DETAILS',
    FETCH_STOCK_TRANSFER_REQUEST: 'Mcf/FETCH_STOCK_TRANSFER_REQUEST',
    FETCH_STOCK_TRANSFER_SUCCESS: 'Mcf/FETCH_STOCK_TRANSFER_SUCCESS',
    FETCH_STOCK_TRANSFER_FAILURE: 'Mcf/FETCH_STOCK_TRANSFER_FAILURE',

    FETCH_STOCK_SALE_DETAILS: 'Mcf/FETCH_STOCK_SALE_DETAILS',
    FETCH_STOCK_SALE_REQUEST: 'Mcf/FETCH_STOCK_SALE_REQUEST',
    FETCH_STOCK_SALE_SUCCESS: 'Mcf/FETCH_STOCK_SALE_SUCCESS',
    FETCH_STOCK_SALE_FAILURE: 'Mcf/FETCH_STOCK_SALE_FAILURE',

    FETCH_STOCK_ITEMS: 'Mcf/FETCH_STOCK_ITEMS',
    FETCH_STOCK_ITEMS_REQUEST: 'Mcf/FETCH_STOCK_ITEMS_REQUEST',
    FETCH_STOCK_ITEMS_SUCCESS: 'Mcf/FETCH_STOCK_ITEMS_SUCCESS',
    FETCH_STOCK_ITEMS_FAILURE: 'Mcf/FETCH_STOCK_ITEMS_FAILURE',

    FETCH_MCF_SEGGRATION: 'Mcf/FETCH_MCF_SEGGRATION',
    FETCH_MCF_SEGGRATION_REQUEST: 'Mcf/FETCH_MCF_SEGGRATION_REQUEST',
    FETCH_MCF_SEGGRATION_SUCCESS: 'Mcf/FETCH_MCF_SEGGRATION_SUCCESS',
    FETCH_MCF_SEGGRATION_FAILURE: 'Mcf/FETCH_MCF_SEGGRATION_FAILURE'
};
export const fetchStockInDetails = (data) => action(types.FETCH_STOCK_IN_DETAILS, { data });

export const fetchMcfSeggregationDetails = (data) => action(types.FETCH_MCF_SEGGRATION, { data });

export const fetchStockTransferDetails = (data) => action(types.FETCH_STOCK_TRANSFER_DETAILS, { data });

export const fetchStockSaleDetails = (data) => action(types.FETCH_STOCK_SALE_DETAILS, { data });

export const fetchStockItems = (data) => action(types.FETCH_STOCK_ITEMS, { data });


