import { action } from '../../common';

export const types = {
    LIST_SERVICE: 'Organization/LIST_SERVICE',
    LIST_SERVICE_REQUEST: 'Organization/LIST_SERVICE_REQUEST',
    LIST_SERVICE_SUCCESS: 'Organization/LIST_SERVICE_SUCCESS',
    LIST_SERVICE_FAILURE: 'Organization/LIST_SERVICE_FAILURE',


    GET_USER_BY_ROLE_ID: 'Organizations/GET_USER_BY_ROLE_ID',
    GET_USER_BY_ROLE_ID_REQUEST: 'Organizations/GET_USER_BY_ROLE_ID_REQUEST',
    GET_USER_BY_ROLE_ID_SUCCESS: 'Organizations/GET_USER_BY_ROLE_ID_SUCCESS',
    GET_USER_BY_ROLE_ID_FAILURE: 'Organizations/GET_USER_BY_ROLE_ID_FAILURE',

    RESET_ORGANIZATION_ROLE_FORM_ASSIGN: 'Organization/RESET_ORGANIZATION_ROLE_FORM_ASSIGN',

    GET_ALL_USER_UNDER_ORG_FOR_SP: 'Organizations/GET_ALL_USER_UNDER_ORG_FOR_SP',
    GET_ALL_USER_UNDER_ORG_FOR_SP_REQUEST: 'Organizations/GET_ALL_USER_UNDER_ORG_FOR_SP_REQUEST',
    GET_ALL_USER_UNDER_ORG_FOR_SP_SUCCESS: 'Organizations/GET_ALL_USER_UNDER_ORG_FOR_SP_SUCCESS',
    GET_ALL_USER_UNDER_ORG_FOR_SP_FAILURE: 'Organizations/GET_ALL_USER_UNDER_ORG_FOR_SP_FAILURE',

    UPDATE_ALL_USER_UNDER_ORG: 'Organizations/UPDATE_ALL_USER_UNDER_ORG',
    UPDATE_ALL_USER_UNDER_ORG_REQUEST: 'Organizations/UPDATE_ALL_USER_UNDER_ORG_REQUEST',
    UPDATE_ALL_USER_UNDER_ORG_SUCCESS: 'Organizations/UPDATE_ALL_USER_UNDER_ORG_SUCCESS',
    UPDATE_ALL_USER_UNDER_ORG_FAILURE: 'Organizations/UPDATE_ALL_USER_UNDER_ORG_FAILURE',

    GET_ASSIGNED_LOCATIONS: 'Organizations/GET_ASSIGNED_LOCATIONS',
    GET_ASSIGNED_LOCATIONS_SUCCESS: 'Organizations/GET_ASSIGNED_LOCATIONS_SUCCESS',
    GET_ASSIGNED_LOCATIONS_REQUEST: 'Organizations/GET_ASSIGNED_LOCATIONS_REQUEST',
    GET_ASSIGNED_LOCATIONS_FAILURE: 'Organizations/GET_ASSIGNED_LOCATIONS_FAILURE',

    GET_ASSIGNED_SERVICE_ADMIN: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN',
    GET_ASSIGNED_SERVICE_ADMIN_REQUEST: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_REQUEST',
    GET_ASSIGNED_SERVICE_ADMIN_SUCCESS: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_SUCCESS',
    GET_ASSIGNED_SERVICE_ADMIN_FAILURE: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_FAILURE',

    GET_ASSIGNED_SERVICE_ADMIN_DROP_DOWN: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_DROP_DOWN',
    GET_ASSIGNED_SERVICE_ADMIN_REQUEST_DROP_DOWN: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_REQUEST_DROP_DOWN',
    GET_ASSIGNED_SERVICE_ADMIN_SUCCESS_DROP_DOWN: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_SUCCESS_DROP_DOWN',
    GET_ASSIGNED_SERVICE_ADMIN_FAILURE_DROP_DOWN: 'Organizations/GET_ASSIGNED_SERVICE_ADMIN_FAILURE_DROP_DOWN',

    GET_LOCATIONS_UNDER_USER: 'Organizations/GET_LOCATIONS_UNDER_USER',
    GET_LOCATIONS_UNDER_USER_REQUEST: 'Organizations/GET_LOCATIONS_UNDER_USER_REQUEST',
    GET_LOCATIONS_UNDER_USER_SUCCESS: 'Organizations/GET_LOCATIONS_UNDER_USER_SUCCESS',
    GET_LOCATIONS_UNDER_USER_FAILURE: 'Organizations/GET_LOCATIONS_UNDER_USER_FAILURE',

    UPDATE_ASSIGNED_WORKER_LOCATION: 'Organizations/UPDATE_ASSIGNED_WORKER_LOCATION',
    UPDATE_ASSIGNED_WORKER_LOCATION_REQUEST: 'Organizations/UPDATE_ASSIGNED_WORKER_LOCATION_REQUEST',
    UPDATE_ASSIGNED_WORKER_LOCATION_SUCCESS: 'Organizations/UPDATE_ASSIGNED_WORKER_LOCATION_SUCCESS',
    UPDATE_ASSIGNED_WORKER_LOCATION_FAILURE: 'Organizations/UPDATE_ASSIGNED_WORKER_LOCATION_FAILURE',

    GET_ASSIGNED_SUPER_VISOR: 'Organizations/GET_ASSIGNED_SUPER_VISOR',
    GET_ASSIGNED_SUPER_VISOR_REQUEST: 'Organizations/GET_ASSIGNED_SUPER_VISOR_REQUEST',
    GET_ASSIGNED_SUPER_VISOR_SUCCESS: 'Organizations/GET_ASSIGNED_SUPER_VISOR_SUCCESS',
    GET_ASSIGNED_SUPER_VISOR_FAILURE: 'Organizations/GET_ASSIGNED_SUPER_VISOR_FAILURE',

    GET_ASSIGNED_WORKERS: 'Organizations/GET_ASSIGNED_WORKERS',
    GET_ASSIGNED_WORKERS_REQUEST: 'Organizations/GET_ASSIGNED_WORKERS_REQUEST',
    GET_ASSIGNED_WORKERS_SUCCESS: 'Organizations/GET_ASSIGNED_WORKERS_SUCCESS',
    GET_ASSIGNED_WORKERS_FAILURE: 'Organizations/GET_ASSIGNED_WORKERS_FAILURE',

    UPDATE_ASSIGN_SERVICE_ADMIN: 'Organizations/UPDATE_ASSIGN_SERVICE_ADMIN',
    UPDATE_ASSIGN_SERVICE_ADMIN_REQUEST: 'Organizations/UPDATE_ASSIGN_SERVICE_ADMIN_REQUEST',
    UPDATE_ASSIGN_SERVICE_ADMIN_SUCCESS: 'Organizations/UPDATE_ASSIGN_SERVICE_ADMIN_SUCCESS',
    UPDATE_ASSIGN_SERVICE_ADMIN_FAILURE: 'Organizations/UPDATE_ASSIGN_SERVICE_ADMIN_SUCCESSS',

    LIST_SERVICE_PROVIDER: 'Organizations/LIST_SERVICE_PROVIDER',
    LIST_SERVICE_PROVIDER_REQUEST: 'Organizations/LIST_SERVICE_PROVIDER_REQUEST',
    LIST_SERVICE_PROVIDER_SUCCESS: 'Organizations/LIST_SERVICE_PROVIDER_SUCCESS',
    LIST_SERVICE_PROVIDER_FAILURE: 'Organizations/LIST_SERVICE_PROVIDER_FAILURE',

    GET_ASSIGNED_LOCATION: 'Organizations/GET_ASSIGNED_LOCATION',
    GET_ASSIGNED_LOCATION_REQUEST: 'Organizations/GET_ASSIGNED_LOCATION_REQUEST',
    GET_ASSIGNED_LOCATION_SUCCESS: 'Organizations/GET_ASSIGNED_LOCATION_SUCCESS',
    GET_ASSIGNED_LOCATION_FAILURE: 'Organizations/GET_ASSIGNED_LOCATION_FAILURE',


    SERVICE_PROVIDER_EDIT: 'Organizations/SERVICE_PROVIDER_EDIT',
    SERVICE_PROVIDER_EDIT_REQUEST: 'Organizations/SERVICE_PROVIDER_EDIT_REQUEST',
    SERVICE_PROVIDER_EDIT_SUCCESS: 'Organizations/SERVICE_PROVIDER_EDIT_SUCCESS',
    SERVICE_PROVIDER_EDIT_FAILURE: 'Organizations/SERVICE_PROVIDER_EDIT_FAILURE',

    GET_SERVICE_PROVIDERS_BY_ID: 'Organizations/GET_SERVICE_PROVIDERS_BY_ID',
    GET_SERVICE_PROVIDERS_BY_ID_REQUEST: 'Organizations/GET_SERVICE_PROVIDERS_BY_ID_REQUEST',
    GET_SERVICE_PROVIDERS_BY_ID_SUCCESS: 'Organizations/GET_SERVICE_PROVIDERS_BY_ID_SUCCESS',
    GET_SERVICE_PROVIDERS_BY_ID_FAILURE: 'Organizations/GET_SERVICE_PROVIDERS_BY_ID_FAILURE',

    GET_TEMPLATE_TYPES_FOR_ORG: 'Organization/GET_TEMPLATE_TYPES_FOR_ORG',
    GET_TEMPLATE_TYPES_FOR_ORG_REQUEST: 'Organization/GET_TEMPLATE_TYPES_FOR_ORG_REQUEST',
    GET_TEMPLATE_TYPES_FOR_ORG_SUCCESS: 'Organization/GET_TEMPLATE_TYPES_FOR_ORG_SUCCESS',
    GET_TEMPLATE_TYPES_FOR_ORG_FAILURE: 'Organization/GET_TEMPLATE_TYPES_FOR_ORG_FAILURE',

    GET_TEMPLATE_BY_TEMP_TYPE_ID: 'Organization/GET_TEMPLATE_BY_TEMP_TYPE_ID',
    GET_TEMPLATE_BY_TEMP_TYPE_ID_REQUEST: 'Organization/GET_TEMPLATE_BY_TEMP_TYPE_ID_REQUEST',
    GET_TEMPLATE_BY_TEMP_TYPE_ID_SUCCESS: 'Organization/GET_TEMPLATE_BY_TEMP_TYPE_ID_SUCCESS',
    GET_TEMPLATE_BY_TEMP_TYPE_ID_FAILURE: 'Organization/GET_TEMPLATE_BY_TEMP_TYPE_ID_FAILURE',

    SAVE_ORGANIZATION: 'Organization/SAVE_ORGANIZATION',
    SAVE_ORGANIZATION_REQUEST: 'Organization/SAVE_ORGANIZATION_REQUEST',
    SAVE_ORGANIZATION_SUCCESS: 'Organization/SAVE_ORGANIZATION_SUCCESS',
    SAVE_ORGANIZATION_FAILED: 'Organization/SAVE_ORGANIZATION_FAILED',

    UPDATE_ORGANIZATION: 'Organization/UPDATE_ORGANIZATION',
    UPDATE_ORGANIZATION_REQUEST: 'Organization/UPDATE_ORGANIZATION_REQUEST',
    UPDATE_ORGANIZATION_SUCCESS: 'Organization/UPDATE_ORGANIZATION_SUCCESS',
    UPDATE_ORGANIZATION_FAILED: 'Organization/UPDATE_ORGANIZATION_FAILED',

    FETCH_ORGANIZATION_DETAILS: 'Organization/FETCH_ORGANIZATION_DETAILS',
    FETCH_ORGANIZATION_DETAILS_REQUEST: 'Organization/FETCH_ORGANIZATION_DETAILS_REQUEST',
    FETCH_ORGANIZATION_DETAILS_SUCCESS: 'Organization/FETCH_ORGANIZATION_DETAILS_SUCCESS',
    FETCH_ORGANIZATION_DETAILS_FAILURE: 'Organization/FETCH_ORGANIZATION_DETAILS_FAILURE',

    FETCH_WARD_BY_ID: 'Wards/ FETCH_WARD_BY_ID',
    FETCH_WARD_BY_ID_REQUEST: 'Wards/ FETCH_WARD_BY_ID_REQUEST',
    FETCH_WARD_BY_ID_SUCCESS: 'Wards/ FETCH_WARD_BY_ID_SUCCESS',
    FETCH_WARD_BY_ID_FAILURE: 'Wards/ FETCH_WARD_BY_ID_FAILURE',

    FETCH_CHK_USER_ORGANIZATION: 'Organization/FETCH_CHK_USER_ORGANIZATION',
    FETCH_CHK_USER_ORGANIZATION_REQUEST: 'Organization/FETCH_CHK_USER_ORGANIZATION_REQUEST',
    FETCH_CHK_USER_ORGANIZATION_SUCCESS: 'Organization/FETCH_CHK_USER_ORGANIZATION_SUCCESS',
    FETCH_CHK_USER_ORGANIZATION_FAILURE: 'Organization/FETCH_CHK_USER_ORGANIZATION_FAILURE',

    LOAD_ORG_FOR_SERVICE_WORKER: 'Organization/LOAD_ORG_FOR_SERVICE_WORKER',
    LOAD_ORG_FOR_SERVICE_WORKER_REQUEST: 'Organization/LOAD_ORG_FOR_SERVICE_WORKER_REQUEST',
    LOAD_ORG_FOR_SERVICE_WORKER_SUCCESS: 'Organization/LOAD_ORG_FOR_SERVICE_WORKER_SUCCESS',
    LOAD_ORG_FOR_SERVICE_WORKER_FAILURE: 'Organization/LOAD_ORG_FOR_SERVICE_WORKER_FAILURE',

    UPDATE_CHK_USER_ORGANIZATION: 'Organization/UPDATE_CHK_USER_ORGANIZATION',
    UPDATE_CHK_USER_ORGANIZATION_REQUEST: 'Organization/UPDATE_CHK_USER_ORGANIZATION_REQUEST',
    UPDATE_CHK_USER_ORGANIZATION_SUCCESS: 'Organization/UPDATE_CHK_USER_ORGANIZATION_SUCCESS',
    UPDATE_CHK_USER_ORGANIZATION_FAILURE: 'Organization/UPDATE_CHK_USER_ORGANIZATION_FAILURE',

    UPDATE_CHK_USER_ORGANIZATION_ROLE: 'Organization/UPDATE_CHK_USER_ORGANIZATION_ROLE',
    UPDATE_CHK_USER_ORGANIZATION_ROLE_REQUEST: 'Organization/UPDATE_CHK_USER_ORGANIZATION_ROLE_REQUEST',
    UPDATE_CHK_USER_ORGANIZATION_ROLE_SUCCESS: 'Organization/UPDATE_CHK_USER_ORGANIZATION_ROLE_SUCCESS',
    UPDATE_CHK_USER_ORGANIZATION_ROLE_FAILURE: 'Organization/UPDATE_CHK_USER_ORGANIZATION_ROLE_FAILURE',

    LIST_ORGANISATION: 'Organization/LIST_ORGANISATION',
    LIST_ORGANISATION_REQUEST: 'Organization/LIST_ORGANISATION_REQUEST',
    LIST_ORGANISATION_SUCCESS: 'Organization/LIST_ORGANISATION_SUCCESS',
    LIST_ORGANISATION_FAILURE: 'Organization/LIST_ORGANISATION_FAILURE',

    DELETE_ORGANISATION: 'Organization/DELETE_ORGANISATION',
    DELETE_ORGANISATION_REQUEST: 'Organization/DELETE_ORGANISATION_REQUEST',
    DELETE_ORGANISATION_SUCCESS: 'Organization/DELETE_ORGANISATION_SUCCESS',
    DELETE_ORGANISATION_FAILURE: 'Organization/DELETE_ORGANISATION_FAILURE',

    DELETE_SERVICE_PROVIDER: 'Organization/DELETE_SERVICE_PROVIDER',
    DELETE_SERVICE_PROVIDER_REQUEST: 'Organization/DELETE_SERVICE_PROVIDER_REQUEST',
    DELETE_SERVICE_PROVIDER_SUCCESS: 'Organization/DELETE_SERVICE_PROVIDER_SUCCESS',
    DELETE_SERVICE_PROVIDER_FAILURE: 'Organization/DELETE_SERVICE_PROVIDER_FAILURE',


    DELETE_SERVICE: 'Organization/DELETE_PROVIDER',
    DELETE_SERVICE_REQUEST: 'Organization/DELETE_PROVIDER_REQUEST',
    DELETE_SERVICE_SUCCESS: 'Organization/DELETE_PROVIDER_SUCCESS',
    DELETE_SERVICE_FAILURE: 'Organization/DELETE_PROVIDER_FAILURE',


    UPDATE_CURRENT_ORGANIZATION: 'Organization/UPDATE_CURRENT_ORGANIZATION',
    UPDATE_CURRENT_ORGANIZATION_REQUEST: 'Organization/UPDATE_CURRENT_ORGANIZATION_REQUEST',
    UPDATE_CURRENT_ORGANIZATION_SUCCESS: 'Organization/UPDATE_CURRENT_ORGANIZATION_SUCCESS',
    UPDATE_CURRENT_ORGANIZATION_FAILED: 'Organization/UPDATE_CURRENT_ORGANIZATION_FAILED',

    LOAD_API_PROVIDERS: 'Organization/LOAD_API_PROVIDERS',
    LOAD_API_PROVIDERS_REQUEST: 'Organization/LOAD_API_PROVIDERS_REQUEST',
    LOAD_API_PROVIDERS_SUCCESS: 'Organization/LOAD_API_PROVIDERS_SUCCESS',
    LOAD_API_PROVIDERS_FAILED: 'Organization/LOAD_API_PROVIDERS_FAILED',

    LOAD_PARENT_ORGANIZATIONS: 'Organization/LOAD_PARENT_ORGANIZATIONS',
    LOAD_PARENT_ORGANIZATIONS_REQUEST: 'Organization/LOAD_PARENT_ORGANIZATIONS_REQUEST',
    LOAD_PARENT_ORGANIZATIONS_SUCCESS: 'Organization/LOAD_PARENT_ORGANIZATIONS_SUCCESS',
    LOAD_PARENT_ORGANIZATIONS_FAILED: 'Organization/LOAD_PARENT_ORGANIZATIONS_FAILED',

    LOAD_ORGANIZATION_TYPES: 'Organization/LOAD_ORGANIZATION_TYPES',
    LOAD_ORGANIZATION_TYPES_REQUEST: 'Organization/LOAD_ORGANIZATION_TYPES_REQUEST',
    LOAD_ORGANIZATION_TYPES_SUCCESS: 'Organization/LOAD_ORGANIZATION_TYPES_SUCCESS',
    LOAD_ORGANIZATION_TYPES_FAILED: 'Organization/LOAD_ORGANIZATION_TYPES_FAILED',

    LOAD_ORGANIZATION_ROLE_TYPES: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES',
    LOAD_ORGANIZATION_ROLE_TYPES_REQUEST: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_REQUEST',
    LOAD_ORGANIZATION_ROLE_TYPES_SUCCESS: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_SUCCESS',
    LOAD_ORGANIZATION_ROLE_TYPES_FAILED: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_FAILED',
    SET_ORGANIZATION_ROLE_TYPES: 'Organization/SET_ORGANIZATION_ROLE_TYPES',


    CHK_LOAD_USER_GROUP_ASSIGN_LIST: 'Organization/CHK_LOAD_USER_GROUP_ASSIGN_LIST',
    CHK_LOAD_USER_GROUP_ASSIGN_LIST_REQUEST: 'Organization/CHK_LOAD_USER_GROUP_ASSIGN_LIST_REQUEST',
    CHK_LOAD_USER_GROUP_ASSIGN_LIST_SUCCESS: 'Organization/CHK_LOAD_USER_GROUP_ASSIGN_LIST_SUCCESS',
    CHK_LOAD_USER_GROUP_ASSIGN_LIST_FAILED: 'Organization/CHK_LOAD_USER_GROUP_ASSIGN_LIST_FAILED',

    LOAD_ORGANIZATION_API_PROVIDERS: 'Organization/LOAD_ORGANIZATION_API_PROVIDERS',
    LOAD_ORGANIZATION_API_PROVIDERS_REQUEST: 'Organization/LOAD_ORGANIZATION_API_PROVIDERS_REQUEST',
    LOAD_ORGANIZATION_API_PROVIDERS_SUCCESS: 'Organization/LOAD_ORGANIZATION_API_PROVIDERS_SUCCESS',
    LOAD_ORGANIZATION_API_PROVIDERS_FAILED: 'Organization/LOAD_ORGANIZATION_API_PROVIDERS_FAILED',

    SAVE_ORGANIZATION_API_PROVIDERS: 'Organization/SAVE_ORGANIZATION_API_PROVIDERS',
    SAVE_ORGANIZATION_API_PROVIDERS_REQUEST: 'Organization/SAVE_ORGANIZATION_API_PROVIDERS_REQUEST',
    SAVE_ORGANIZATION_API_PROVIDERS_SUCCESS: 'Organization/SAVE_ORGANIZATION_API_PROVIDERS_SUCCESS',
    SAVE_ORGANIZATION_API_PROVIDERS_FAILED: 'Organization/SAVE_ORGANIZATION_API_PROVIDERS_FAILED',

    UPDATE_ORGANIZATION_API_PROVIDERS_REQUEST: 'Organization/UPDATE_ORGANIZATION_API_PROVIDERS_REQUEST',
    UPDATE_ORGANIZATION_API_PROVIDERS_SUCCESS: 'Organization/UPDATE_ORGANIZATION_API_PROVIDERS_SUCCESS',
    UPDATE_ORGANIZATION_API_PROVIDERS_FAILURE: 'Organization/UPDATE_ORGANIZATION_API_PROVIDERS_FAILURE',

    SET_FILTER: 'Organization/SET_FILTER',

    GET_EMAIL_API_PROVIDER: 'Organization/GET_EMAIL_API_PROVIDER',
    GET_EMAIL_API_PROVIDER_REQUEST: 'Organization/GET_EMAIL_API_PROVIDER_REQUEST',
    GET_EMAIL_API_PROVIDER_SUCCESS: 'Organization/GET_EMAIL_API_PROVIDER_SUCCESS',
    GET_EMAIL_API_PROVIDER_FAILURE: 'Organization/GET_EMAIL_API_PROVIDER_FAILURE',

    GET_SMS_API_PROVIDER: 'Organization/GET_SMS_API_PROVIDER',
    GET_SMS_API_PROVIDER_REQUEST: 'Organization/GET_SMS_API_PROVIDER_REQUEST',
    GET_SMS_API_PROVIDER_SUCCESS: 'Organization/GET_SMS_API_PROVIDER_SUCCESS',
    GET_SMS_API_PROVIDER_FAILURE: 'Organization/GET_SMS_API_PROVIDER_FAILURE',


    GET_NOTIFICATION_API_PROVIDER: 'Organization/GET_NOTIFICATION_API_PROVIDER',
    GET_NOTIFICATION_API_PROVIDER_REQUEST: 'Organization/GET_NOTIFICATION_API_PROVIDER_REQUEST',
    GET_NOTIFICATION_API_PROVIDER_SUCCESS: 'Organization/GET_NOTIFICATION_API_PROVIDER_SUCCESS',
    GET_NOTIFICATION_API_PROVIDER_FAILURE: 'Organization/GET_NOTIFICATION_API_PROVIDER_FAILURE',

    GET_PAYMENT_API_PROVIDER: 'Organization/GET_PAYMENT_API_PROVIDER',
    GET_PAYMENT_API_PROVIDER_REQUEST: 'Organization/GET_PAYMENT_API_PROVIDER_REQUEST',
    GET_PAYMENT_API_PROVIDER_SUCCESS: 'Organization/GET_PAYMENT_API_PROVIDER_SUCCESS',
    GET_PAYMENT_API_PROVIDER_FAILURE: 'Organization/GET_PAYMENT_API_PROVIDER_FAILURE',

    UPDATE_API_PROVIDER: 'Organization/UPDATE_API_PROVIDER',
    UPDATE_API_PROVIDER_REQUEST: 'Organization/UPDATE_API_PROVIDER_REQUEST',
    UPDATE_API_PROVIDER_SUCCESS: 'Organization/UPDATE_API_PROVIDER_SUCCESS',
    UPDATE_API_PROVIDER_FAILURE: 'Organization/UPDATE_API_PROVIDER_FAILURE',

    POST_API_PROVIDER: 'Organization/POST_API_PROVIDER',
    POST_API_PROVIDER_REQUEST: 'Organization/POST_API_PROVIDER_REQUEST',
    POST_API_PROVIDER_SUCCESS: 'Organization/POST_API_PROVIDER_SUCCESS',
    POST_API_PROVIDER_FAILURE: 'Organization/POST_API_PROVIDER_FAILURE',
    // module
    FETCH_MODULES_FOR_CHK: 'Organization/FETCH_MODULES_FOR_CHK',
    FETCH_MODULES_FOR_CHK_REQUEST: 'Organization/FETCH_MODULES_FOR_CHK_REQUEST',
    FETCH_MODULES_FOR_CHK_SUCCESS: 'Organization/FETCH_MODULES_FOR_CHK_SUCCESS',
    FETCH_MODULES_FOR_CHK_FAILURE: 'Organization/FETCH_MODULES_FOR_CHK_FAILURE',

    SAVE_MODULES_FOR_CHK: 'Organization/SAVE_MODULES_FOR_CHK',
    SAVE_MODULES_FOR_CHK_REQUEST: 'Organization/SAVE_MODULES_FOR_CHK_REQUEST',
    SAVE_MODULES_FOR_CHK_SUCCESS: 'Organization/SAVE_MODULES_FOR_CHK_SUCCESS',
    SAVE_MODULES_FOR_CHK_FAILURE: 'Organization/SAVE_MODULES_FOR_CHK_FAILURE',

    SAVE_MODULES_FOR_CHK_IN_LOCATION: 'Organization/SAVE_MODULES_FOR_CHK_IN_LOCATION',
    SAVE_MODULES_FOR_CHK_REQUEST_IN_LOCATION: 'Organization/SAVE_MODULES_FOR_CHK_REQUEST_IN_LOCATION',
    SAVE_MODULES_FOR_CHK_SUCCESS_IN_LOCATION: 'Organization/SAVE_MODULES_FOR_CHK_SUCCESS_IN_LOCATION',
    SAVE_MODULES_FOR_CHK_FAILURE_IN_LOCATION: 'Organization/SAVE_MODULES_FOR_CHK_FAILURE_IN_LOCATION',

    FETCH_ROLESLIST_FOR_MODULE: 'Organization/FETCH_ROLESLIST_FOR_MODULE',
    FETCH_ROLESLIST_FOR_MODULE_REQUEST: 'Organization/FETCH_ROLESLIST_FOR_MODULE_REQUEST',
    FETCH_ROLESLIST_FOR_MODULE_SUCCESS: 'Organization/FETCH_ROLESLIST_FOR_MODULE_SUCCESS',
    FETCH_ROLESLIST_FOR_MODULE_FAILURE: 'Organization/FETCH_ROLESLIST_FOR_MODULE_FAILURE',

    FETCH_ASSIGNED_MODULES_FOR_CHK: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK',
    FETCH_ASSIGNED_MODULES_FOR_CHK_REQUEST: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_REQUEST',
    FETCH_ASSIGNED_MODULES_FOR_CHK_SUCCESS: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_SUCCESS',
    FETCH_ASSIGNED_MODULES_FOR_CHK_FAILURE: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_FAILURE',

    SAVE_ASSIGNED_MODULES: 'Organization/SAVE_ASSIGNED_MODULES',
    SAVE_ASSIGNED_MODULES_REQUEST: 'Organization/SAVE_ASSIGNED_MODULES_REQUEST',
    SAVE_ASSIGNED_MODULES_SUCCESS: 'Organization/SAVE_ASSIGNED_MODULES_SUCCESS',
    SAVE_ASSIGNED_MODULES_FAILURE: 'Organization/SAVE_ASSIGNED_MODULES_FAILURE',

    CLEAR_ASSIGNED_CHECKED_LIST: 'Organization/CLEAR_ASSIGNED_CHECKED_LIST',
    // template
    FETCH_TEMPLATE_FOR_LST: 'FETCH_TEMPLATE_FOR_LST',
    FETCH_TEMPLATE_FOR_LST_REQUEST: 'FETCH_TEMPLATE_FOR_LST_REQUEST',
    FETCH_TEMPLATE_FOR_LST_SUCCESS: 'FETCH_TEMPLATE_FOR_LST_SUCCESS',
    FETCH_TEMPLATE_FOR_LST_FAILURE: 'FETCH_TEMPLATE_FOR_LST_FAILURE',

    FETCH_SELECTED_TEMPLATE_FOR_LST: 'FETCH_SELECTED_TEMPLATE_FOR_LST',
    FETCH_SELECTED_TEMPLATE_FOR_LST_REQUEST: 'FETCH_SELECTED_TEMPLATE_FOR_LST_REQUEST',
    FETCH_SELECTED_TEMPLATE_FOR_LST_SUCCESS: 'FETCH_SELECTED_TEMPLATE_FOR_LST_SUCCESS',
    FETCH_SELECTED_TEMPLATE_FOR_LST_FAILURE: 'FETCH_SELECTED_TEMPLATE_FOR_LST_FAILURE',

    SAVE_TEMPLATE_IN_LIST: 'SAVE_TEMPLATE_IN_LIST',
    SAVE_TEMPLATE_IN_LIST_REQUEST: 'SAVE_TEMPLATE_IN_LIST_REQUEST',
    SAVE_TEMPLATE_IN_LIST_SUCCESS: 'SAVE_TEMPLATE_IN_LIST_SUCCESS',
    SAVE_TEMPLATE_IN_LIST_FAILURE: 'SAVE_TEMPLATE_IN_LIST_FAILURE',

    GET_SERVICE_PROVIDER: 'Organization/GET_SERVICE_PROVIDER',
    GET_SERVICE_PROVIDER_REQUEST: 'Organization/GET_SERVICE_PROVIDER_REQUEST',
    GET_SERVICE_PROVIDER_SUCCESS: 'Organization/GET_SERVICE_PROVIDER_SUCCESS',
    GET_SERVICE_PROVIDER_FAILURE: 'Organization/GET_SERVICE_PROVIDER_FAILURE',

    POST_SERVICE_PROVIDERS: 'Organization/POST_SERVICE_PROVIDERS',
    POST_SERVICE_PROVIDERS_REQUEST: 'Organization/POST_SERVICE_PROVIDERS_REQUEST',
    POST_SERVICE_PROVIDERS_SUCCESS: 'Organization/POST_SERVICE_PROVIDERS_SUCCESS',
    POST_SERVICE_PROVIDERS_FAILURE: 'Organization/POST_SERVICE_PROVIDERS_FAILURE',
    SAVE_TEMPLATE_ROUTES: 'Template/SAVE_TEMPLATE_ROUTES',
    SAVE_TEMPLATE_ROUTES_REQUEST: 'Organizations/SAVE_TEMPLATE_ROUTES_REQUEST',
    SAVE_TEMPLATE_ROUTES_SUCCESS: 'Organizations/SAVE_TEMPLATE_ROUTES_SUCCESS',
    SAVE_TEMPLATE_ROUTES_FAILURE: 'Organizations/SAVE_TEMPLATE_ROUTES_FAILURE',
    SET_TAB_INDEX: 'Organizations/SET_TAB_INDEX',
    SET_TAB_INDEX_FOR_SERVICE_PROVIDER: 'Organizations/SET_TAB_INDEX_FOR_SERVICE_PROVIDER',

    GET_ALL_ROLES: 'Organizations/GET_ALL_ROLES',
    GET_ALL_ROLES_REQUEST: 'Organizations/GET_ALL_ROLES_REQUEST',
    GET_ALL_ROLES_SUCCESS: 'Organizations/GET_ALL_ROLES_SUCCESS',
    GET_ALL_ROLES_FAILURE: 'Organizations/GET_ALL_ROLES_FAILURE',

    GET_USER_BASED_ON_ROLE_ID: 'GET_USER_BASED_ON_ROLE_ID',
    GET_USER_BASED_ON_ROLE_ID_REQUEST: 'GET_USER_BASED_ON_ROLE_ID_REQUEST',
    GET_USER_BASED_ON_ROLE_ID_SUCCESS: 'GET_USER_BASED_ON_ROLE_ID_SUCCESS',
    GET_USER_BASED_ON_ROLE_ID_FAILURE: 'GET_USER_BASED_ON_ROLE_ID_FAILURE',

    GET_ASSIGNED_WORKERS_ONLY: 'Organizations/GET_ASSIGNED_WORKERS_ONLY',
    GET_ASSIGNED_WORKERS_ONLY_REQUEST: 'Organizations/GET_ASSIGNED_WORKERS_ONLY_REQUEST',
    GET_ASSIGNED_WORKERS_ONLY_SUCCESS: 'Organizations/GET_ASSIGNED_WORKERS_ONLY_SUCCESS',
    GET_ASSIGNED_WORKERS_ONLY_FAILURE: 'Organizations/GET_ASSIGNED_WORKERS_ONLY_FAILURE',

    GET_LOCATION_BASED_ON_WORKER: 'Organizations/GET_LOCATION_BASED_ON_WORKER',
    GET_LOCATION_BASED_ON_WORKER_REQUEST: 'Organizations/GET_LOCATION_BASED_ON_WORKER_REQUEST',
    GET_LOCATION_BASED_ON_WORKER_SUCCESS: 'Organizations/GET_LOCATION_BASED_ON_WORKER_SUCCESS',
    GET_LOCATION_BASED_ON_WORKER_FAILURE: 'Organizations/GET_LOCATION_BASED_ON_WORKER_FAILURE',

    GET_OLD_SUPER_VISOR: 'Organizations/GET_OLD_SUPER_VISOR',
    GET_OLD_SUPER_VISOR_REQUEST: 'Organizations/GET_OLD_SUPER_VISOR_REQUEST',
    GET_OLD_SUPER_VISOR_SUCCESS: 'Organizations/GET_OLD_SUPER_VISOR_SUCCESS',
    GET_OLD_SUPER_VISOR_FAILURE: 'Organizations/GET_OLD_SUPER_VISOR_FAILURE',

    GET_NEW_SUPER_VISOR: 'Organizations/GET_NEW_SUPER_VISOR',
    GET_NEW_SUPER_VISOR_REQUEST: 'Organizations/GET_NEW_SUPER_VISOR_REQUEST',
    GET_NEW_SUPER_VISOR_SUCCESS: 'Organizations/GET_NEW_SUPER_VISOR_SUCCESS',
    GET_NEW_SUPER_VISOR_FAILURE: 'Organizations/GET_NEW_SUPER_VISOR_FAILURE',

    UPDATE_ASSIGNED_LOCATIONS: 'Organizations/UPDATE_ASSIGNED_LOCATIONS',
    UPDATE_ASSIGNED_LOCATIONS_REQUEST: 'Organizations/UPDATE_ASSIGNED_LOCATIONS_REQUEST',
    UPDATE_ASSIGNED_LOCATIONS_SUCCESS: 'Organizations/UPDATE_ASSIGNED_LOCATIONS_SUCCESS',
    UPDATE_ASSIGNED_LOCATIONS_FAILURE: 'Organizations/UPDATE_ASSIGNED_LOCATIONS_FAILURE',

    //reset
    RESET_SERVICE_ADMIN_FORM: 'Organizations/RESET_SERVICE_ADMIN_FORM',
    RESET_ASSIGN_WORKER_FORM: 'Organizations/RESET_SERVICE_ADMIN_FORM',
    RESET_SUPER_VISOR_TO_WORKER_FORM: 'Organizations/RESET_SUPER_VISOR_TO_WORKER_FORM',

    FETCH_INITIAL_ORGANIZATIONS: 'Organizations/FETCH_INITIAL_ORGANIZATIONS',
    FETCH_INITIAL_ORGANIZATIONS_REQUEST: 'Organizations/FETCH_INITIAL_ORGANIZATIONS_REQUEST',
    FETCH_INITIAL_ORGANIZATIONS_SUCCESS: 'Organizations/FETCH_INITIAL_ORGANIZATIONS_SUCCESS',
    FETCH_INITIAL_ORGANIZATIONS_FAILURE: 'Organizations/FETCH_INITIAL_ORGANIZATIONS_FAILURE',
    RESET_CHECKBOX_WORKER_LOCATION_ARRAY: 'Organizations/RESET_CHECKBOX_WORKER_LOCATION_ARRAY',
    RESET_CHECKBOX_SUPERVISOR_TO_WORKER_LOCATION_ARRAY: 'Organizations/RESET_CHECKBOX_SUPERVISOR_TO_WORKER_LOCATION_ARRAY',

    SET_FILTER_VALUES_FOR_ORGS: 'Organizations/SET_FILTER_VALUES_FOR_ORGS',
    RESET_FILTER_VALUES_FOR_ORGS: 'Organizations/RESET_FILTER_VALUES_FOR_ORGS',

    LIST_JSON_DATA_FOR_ORG_FILTER: 'Organizations/LIST_JSON_DATA_FOR_ORG_FILTER',
    LIST_JSON_DATA_FOR_ORG_FILTER_REQUEST: 'Organizations/LIST_JSON_DATA_FOR_ORG_FILTER_REQUEST',
    LIST_JSON_DATA_FOR_ORG_FILTER_SUCCESS: 'Organizations/LIST_JSON_DATA_FOR_ORG_FILTER_SUCCESS',
    LIST_JSON_DATA_FOR_ORG_FILTER_FAILURE: 'Organizations/LIST_JSON_DATA_FOR_ORG_FILTER_FAILURE',

    STORE_JSON_DATA_FOR_ORGS: 'Organizations/STORE_JSON_DATA_FOR_ORGS',
    FETCH_SERVICE_PROVIDER_LIST: 'Organization/FETCH_SERVICE_PROVIDER_LIST',
    FETCH_SERVICE_PROVIDER_LIST_REQUEST: 'Organization/FETCH_SERVICE_PROVIDER_LIST_REQUEST',
    FETCH_SERVICE_PROVIDER_LIST_SUCCESS: 'Organization/FETCH_SERVICE_PROVIDER_LIST_SUCCESS',
    FETCH_SERVICE_PROVIDER_LIST_FAILURE: 'Organization/FETCH_SERVICE_PROVIDER_LIST_FAILURE',

    LIST_JSON_DATA_FOR_SERVICE_FILTER: 'Organizations/LIST_JSON_DATA_FOR_SERVIC_FILTER',
    LIST_JSON_DATA_FOR_SERVICE_FILTER_REQUEST: 'Organizations/LIST_JSON_DATA_FOR_SERVICE_FILTER_REQUEST',
    LIST_JSON_DATA_FOR_SERVICE_FILTER_SUCCESS: 'Organizations/LIST_JSON_DATA_FOR_SERVICE_FILTER_SUCCESS',
    LIST_JSON_DATA_FOR_SERVICE_FILTER_FAILURE: 'Organizations/LIST_JSON_DATA_FOR_SERVICE_FILTER_FAILURE',

    SET_FILTER_VALUES_FOR_SERVICE: 'Organizations/SET_FILTER_VALUES_FOR_SERVICE',


    STORE_JSON_DATA_FOR_SERVICE: 'Organizations/STORE_JSON_DATA_FOR_SERVICE',

    LIST_RESIDENCE_CATEGORY: 'Organization/LIST_RESIDENCE_CATEGORY',
    LIST_RESIDENCE_CATEGORY_SUCCESS: 'Organization/LIST_RESIDENCE_CATEGORY_SUCCESS',
    LIST_RESIDENCE_CATEGORY_REQUEST: 'Organization/LIST_RESIDENCE_CATEGORY_REQUEST',
    LIST_RESIDENCE_CATEGORY_FAILURE: 'Organization/LIST_RESIDENCE_CATEGORY_FAILURE',

    LIST_SERVICE_CATEGORY: 'Organization/LIST_SERVICE_CATEGORY',
    LIST_SERVICE_CATEGORY_SUCCESS: 'Organization/LIST_SERVICE_CATEGORY_SUCCESS',
    LIST_SERVICE_CATEGORY_REQUEST: 'Organization/LIST_SERVICE_CATEGORY_REQUEST',
    LIST_SERVICE_CATEGORY_FAILURE: 'Organization/LIST_SERVICE_CATEGORY_FAILURE',


    LIST_SERVICE_TYPE: 'Organization/LIST_SERVICE_TYPE',
    LIST_SERVICE_TYPE_SUCCESS: 'Organization/LIST_SERVICE_TYPE_SUCCESS',
    LIST_SERVICE_TYPE_REQUEST: 'Organization/LIST_SERVICE_TYPE_REQUEST',
    LIST_SERVICE_TYPE_FAILURE: 'Organization/LIST_SERVICE_TYPE_FAILURE',

    LIST_PAYMENT_COLLECTION: 'Organization/LIST_PAYMENT_COLLECTION',
    LIST_PAYMENT_COLLECTION_SUCCESS: 'Organization/LIST_PAYMENT_COLLECTION_SUCCESS',
    LIST_PAYMENT_COLLECTION_REQUEST: 'Organization/ LIST_PAYMENT_COLLECTION_REQUEST',
    LIST_PAYMENT_COLLECTION_FAILURE: 'Organization/ LIST_PAYMENT_COLLECTION_FAILURE',

    LIST_PAYMENT_INTERVAL: 'Organization/LIST_PAYMENT_INTERVAL',
    LIST_PAYMENT_INTERVAL_SUCCESS: 'Organization/LIST_PAYMENT_INTERVAL_SUCCESS',
    LIST_PAYMENT_INTERVAL_REQUEST: 'Organization/ LIST_PAYMENT_INTERVAL_REQUEST',
    LIST_PAYMENT_INTERVAL_FAILURE: 'Organization/ LIST_PAYMENT_INTERVAL_FAILURE',

    LIST_RATE_TYPE: 'Organization/LIST_RATE_TYPE',
    LIST_RATE_TYPE_SUCCESS: 'Organization/LIST_RATE_TYPE_SUCCESS',
    LIST_RATE_TYPE_REQUEST: 'Organization/LIST_RATE_TYPE_REQUEST',
    LIST_RATE_TYPE_FAILURE: 'Organization/LIST_RATE_TYPE_FAILURE',

    LIST_SERVICE_INTERVEL: 'Organization/LIST_SERVICE_INTERVEL',
    LIST_SERVICE_INTERVEL_REQUEST: 'Organization/LIST_SERVICE_INTERVEL_REQUEST',
    LIST_SERVICE_INTERVEL_SUCCESS: 'Organization/LIST_SERVICE_INTERVEL_SUCCESS',
    LIST_SERVICE_INTERVEL_FAILURE: 'Organization/LIST_SERVICE_INTERVEL_FAILURE',

    LIST_BUNDLED_OR_SERVICE_CONFIG: 'Organization/LIST_BUNDLED_OR_SERVICE_CONFIG',
    LIST_BUNDLED_OR_SERVICE_CONFIG_REQUEST: 'Organization/LIST_BUNDLED_OR_SERVICE_CONFIG_REQUEST',
    LIST_BUNDLED_OR_SERVICE_CONFIG_SUCCESS: 'Organization/LIST_BUNDLED_OR_SERVICE_CONFIG_SUCCESS',
    LIST_BUNDLED_OR_SERVICE_CONFIG_FAILURE: 'Organization/LIST_BUNDLED_OR_SERVICE_CONFIG_FAILURE',

    LIST_BUNDLED__SERVICE_CONFIG: 'Organization/LIST_BUNDLED__SERVICE_CONFIG',
    LIST_BUNDLED__SERVICE_CONFIG_REQUEST: 'Organization/LIST_BUNDLED__SERVICE_CONFIG_REQUEST',
    LIST_BUNDLED__SERVICE_CONFIG_SUCCESS: 'Organization/LIST_BUNDLED__SERVICE_CONFIG_SUCCESS',
    LIST_BUNDLED__SERVICE_CONFIG_FAILURE: 'Organization/LIST_BUNDLED__SERVICE_CONFIG_FAILURE',

    LIST__SERVICE_CONFIG: 'Organization/LIST__SERVICE_CONFIG',
    LIST__SERVICE_CONFIG_REQUEST: 'Organization/LIST__SERVICE_CONFIG_REQUEST',
    LIST__SERVICE_CONFIG_SUCCESS: 'Organization/LIST__SERVICE_CONFIG_SUCCESS',
    LIST__SERVICE_CONFIG_FAILURE: 'Organization/LIST__SERVICE_CONFIG_FAILURE',

    LIST_RESET_BUNDLED_SERVICE_CONFIG: 'Organization/LIST_RESET_BUNDLED_SERVICE_CONFIG',

    LIST_SERVICE_CHARGE_SLAB: 'Organization/LIST_SERVICE_CHARGE_SLAB',
    LIST_SERVICE_CHARGE_SLAB_REQUEST: 'Organization/LIST_SERVICE_CHARGE_SLAB_REQUEST',
    LIST_SERVICE_CHARGE_SLAB_SUCCESS: 'Organization/LIST_SERVICE_CHARGE_SLAB_SUCCESS',
    LIST_SERVICE_CHARGE_SLAB_FAILURE: 'Organization/LIST_SERVICE_CHARGE_SLAB_FAILURE',

    SENT_OBJECT_FOR_SERVICE: 'Organization/SENT_OBJECT_FOR_SERVICE',
    SENT_OBJECT_FOR_SERVICE_REQUEST: 'Organization/SENT_OBJECT_FOR_SERVICE_REQUEST',
    SENT_OBJECT_FOR_SERVICE_SUCCESS: 'Organization/SENT_OBJECT_FOR_SERVICE_SUCCESS',
    SENT_OBJECT_FOR_SERVICE_FAILURE: 'Organization/SENT_OBJECT_FOR_SERVICE_FAILURE',

    EDIT_OBJECT_FOR_SERVICE: 'Organization/EDIT_OBJECT_FOR_SERVICE',
    EDIT_OBJECT_FOR_SERVICE_REQUEST: 'Organization/EDIT_OBJECT_FOR_SERVICE_REQUEST',
    EDIT_OBJECT_FOR_SERVICE_SUCCESS: 'Organization/EDIT_OBJECT_FOR_SERVICE_SUCCESS',
    EDIT_OBJECT_FOR_SERVICE_FAILURE: 'Organization/EDIT_OBJECT_FOR_SERVICE_FAILURE',

    LIST_SERVICE_BY_ID: 'Organization/LIST_SERVICE_BY_ID',
    LIST_SERVICE_BY_ID_REQUEST: 'Organization/LIST_SERVICE_BY_ID_REQUEST',
    LIST_SERVICE_BY_ID_SUCCESS: 'Organization/LIST_SERVICE_BY_ID_SUCCESS',
    LIST_SERVICE_BY_ID_FAILURE: 'Organization/LIST_SERVICE_BY_ID_FAILURE',

    RESET_SERVICE: 'Organization/RESET_SERVICE',
    CLEAR_ORGANIZATION_REDUCER: 'Organization/CLEAR_ORGANIZATION_REDUCER',
    //when ratetype changed
    EMPTY_SLAB_ARRAY: 'Organization/EMPTY_SLAB_ARRAY',

    SET_STATE_OR_DISTRICT: 'Organization/SET_STATE_OR_DISTRICT',
    SET_ROLE_USER: 'Organization/SET_ROLE_USER',
    SET_WORKER_SUPERWISER: 'Organization/SET_WORKER_SUPERWISER',

    GET_WARDS_UNDER_SERVICE_PROVIDER_ID: 'Organization/GET_WARDS_UNDER_SERVICE_PROVIDER_ID',
    GET_WARDS_UNDER_SERVICE_PROVIDER_ID_REQUEST: 'Organization/GET_WARDS_UNDER_SERVICE_PROVIDER_ID_REQUEST',
    GET_WARDS_UNDER_SERVICE_PROVIDER_ID_SUCCESS: 'Organization/GET_WARDS_UNDER_SERVICE_PROVIDER_ID_SUCCESS',
    GET_WARDS_UNDER_SERVICE_PROVIDER_ID_FAILURE: 'Organization/GET_WARDS_UNDER_SERVICE_PROVIDER_ID_FAILURE',

    GET_GT_BASED_ON_WARD_ID: 'Organization/GET_GT_BASED_ON_WARD_ID',
    GET_GT_BASED_ON_WARD_ID_REQUEST: 'Organization/GET_GT_BASED_ON_WARD_ID_REQUEST',
    GET_GT_BASED_ON_WARD_ID_SUCCESS: 'Organization/GET_GT_BASED_ON_WARD_ID_SUCCESS',
    GET_GT_BASED_ON_WARD_ID_FAILURE: 'Organization/GET_GT_BASED_ON_WARD_ID_FAILURE',

    GET_UUID_OF_CUSTOMERS: 'Organization/GET_UUID_OF_CUSTOMERS',
    RESET_ORG_USER: 'Organization/RESET_ORG_USER',
    GET_CUSTOMERS_BASED_ON_GT_ID: 'Organization/GET_CUSTOMERS_BASED_ON_GT_ID',
    GET_CUSTOMERS_BASED_ON_GT_ID_REQUEST: 'Organization/GET_CUSTOMERS_BASED_ON_GT_ID_REQUEST',
    GET_CUSTOMERS_BASED_ON_GT_ID_SUCCESS: 'Organization/GET_CUSTOMERS_BASED_ON_GT_ID_SUCCESS',
    GET_CUSTOMERS_BASED_ON_GT_ID_FAILURE: 'Organization/GET_CUSTOMERS_BASED_ON_GT_ID_FAILURE',

    GET_SUPER_VISORS: 'Organization/GET_SUPER_VISORS',
    GET_SUPER_VISORS_REQUEST: 'Organization/GET_SUPER_VISORS_REQUEST',
    GET_SUPER_VISORS_SUCCESS: 'Organization/GET_SUPER_VISORS_SUCCESS',
    GET_SUPER_VISORS_FAILURE: 'Organization/GET_SUPER_VISORS_FAILURE',

    GET_TO_GT_WITH_SUPER_VISOR_ID: 'Organization/GET_TO_GT_WITH_SUPER_VISOR_ID',
    GET_TO_GT_WITH_SUPER_VISOR_ID_REQUEST: 'Organization/GET_TO_GT_WITH_SUPER_VISOR_ID_REQUEST',
    GET_TO_GT_WITH_SUPER_VISOR_ID_SUCCESS: 'Organization/GET_TO_GT_WITH_SUPER_VISOR_ID_SUCCESS',
    GET_TO_GT_WITH_SUPER_VISOR_ID_FAILURE: 'Organization/GET_TO_GT_WITH_SUPER_VISOR_ID_FAILURE',

    POST_RE_ASSIGN_GT: 'Organization/POST_RE_ASSIGN_GT',
    POST_RE_ASSIGN_GT_REQUEST: 'Organization/POST_RE_ASSIGN_GT_REQUEST',
    POST_RE_ASSIGN_GT_SUCCESS: 'Organization/POST_RE_ASSIGN_GT_SUCCESS',
    POST_RE_ASSIGN_GT_FAILURE: 'Organization/POST_RE_ASSIGN_GT_FAILURE',

    UPDATE_RE_ASSIGN_SUPER_VISOR: 'Organization/UPDATE_RE_ASSIGN_SUPER_VISOR',
    UPDATE_RE_ASSIGN_SUPER_VISOR_REQUEST: 'Organization/UPDATE_RE_ASSIGN_SUPER_VISOR_REQUEST',
    UPDATE_RE_ASSIGN_SUPER_VISOR_SUCCESS: 'Organization/UPDATE_RE_ASSIGN_SUPER_VISOR_SUCCESS',
    UPDATE_RE_ASSIGN_SUPER_VISOR_FAILURE: 'Organization/UPDATE_RE_ASSIGN_SUPER_VISOR_FAILURE',

    RESET_RE_ASSIGN_GT: 'Organization/RESET_RE_ASSIGN_GT',
    SET_FROM_GT: 'Organization/SET_FROM_GT',
    SET_TO_GT: 'Organization/SET_TO_GT',

    TOGGLE_STATUS: 'Organization/TOGGLE_STATUS',
    TOGGLE_STATUS_REQUEST: 'Organization/TOGGLE_STATUS_REQUEST',
    TOGGLE_STATUS_SUCCESS: 'Organization/TOGGLE_STATUS_SUCCESS',
    TOGGLE_STATUS_FAILURE: 'Organization/TOGGLE_STATUS_FAILURE',

    LOAD_TEMPLATES: 'Organization/LOAD_TEMPLATES',
    LOAD_TEMPLATES_REQUEST: 'Organization/LOAD_TEMPLATES_REQUEST',
    LOAD_TEMPLATES_SUCCESS: 'Organization/LOAD_TEMPLATES_SUCCESS',
    LOAD_TEMPLATES_FAILURE: 'Organization/LOAD_TEMPLATES_FAILURE',

    LOAD_SERVICES: 'Organization/LOAD_SERVICES',
    LOAD_SERVICES_REQUEST: 'Organization/LOAD_SERVICES_REQUEST',
    LOAD_SERVICES_SUCCESS: 'Organization/LOAD_SERVICES_SUCCESS',
    LOAD_SERVICES_FAILURE: 'Organization/LOAD_SERVICES_FAILURE',

    FETCH_ORGANIZATION_ASSIGN_USERS: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS',
    FETCH_ORGANIZATION_ASSIGN_USERS_REQUEST: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_REQUEST',
    FETCH_ORGANIZATION_ASSIGN_USERS_SUCCESS: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_SUCCESS',
    FETCH_ORGANIZATION_ASSIGN_USERS_FAILURE: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_FAILURE',
    GET_SW_SUPERVISOR_FOR_WARD: 'Organization/GET_SW_SUPERVISOR_FOR_WARD',
    GET_SW_SUPERVISOR_FOR_WARD_REQUEST: 'Organization/GET_SW_SUPERVISOR_FOR_WARD_REQUEST',
    GET_SW_SUPERVISOR_FOR_WARD_SUCCESS: 'Organnization/GET_SW_SUPERVISOR_FOR_WARD_SUCCESS',
    GET_SW_SUPERVISOR_FOR_WARD_FAILURE: 'Organnization/GET_SW_SUPERVISOR_FOR_WARD_FAILURE',

    GET_SERVICE_WORKER_FROM_SW_SUPERVISOR: 'Organization/GET_SERVICE_WORKER_FROM_SW_SUPERVISOR',
    GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_REQUEST: 'Organization/GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_REQUEST',
    GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_SUCCESS: 'Organization/GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_SUCCESS',
    GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_FAILURE: 'Organization/GET_SERVICE_WORKER_FROM_SW_SUPERVISOR_FAILURE',

    SUBMIT_RE_ASSIGN_SUPERVISOR_DATA: 'organization/SUBMIT_RE_ASSIGN_SUPERVISOR_DATA',
    SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_REQUEST: 'organization/SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_REQUEST',
    SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_SUCCESS: 'organization/SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_SUCCESS',
    SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_FAILURE: 'organization/SUBMIT_RE_ASSIGN_SUPERVISOR_DATA_FAILURE',

    SUBMIT_RE_ASSIGN_WORKER_DATA: 'organization/SUBMIT_RE_ASSIGN_WORKER_DATA',
    SUBMIT_RE_ASSIGN_WORKER_DATA_REQUEST: 'organization/SUBMIT_RE_ASSIGN_WORKER_DATA_REQUEST',
    SUBMIT_RE_ASSIGN_WORKER_DATA_SUCCESS: 'organization/SUBMIT_RE_ASSIGN_WORKER_DATA_SUCCESS',
    SUBMIT_RE_ASSIGN_WORKER_DATA_FAILURE: 'organization/SUBMIT_RE_ASSIGN_WORKER_DATA_FAILURE',

    FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER: 'Organization/FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER',
    FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_REQUEST: 'Organization/FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_REQUEST',
    FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_SUCCESS: 'Organization/FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_SUCCESS',
    FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_FAILURE: 'Organization/FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER_FAILURE',

    SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER: 'Organization/SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER',
    SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_REQUEST: 'Organization/SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_REQUEST',
    SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_SUCCESS: 'Organization/SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_SUCCESS',
    SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_FAILURE: 'Organization/SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER_FAILURE',

    FETCH_VENDOR_DETAILS: 'Organization/FETCH_VENDOR_DETAILS',
    FETCH_VENDOR_DETAILS_REQUEST: 'Organization/FETCH_VENDOR_DETAILS_REQUEST',
    FETCH_VENDOR_DETAILS_SUCCESS: 'Organization/FETCH_VENDOR_DETAILS_SUCCESS',
    FETCH_VENDOR_DETAILS_FAILURE: 'Organization/FETCH_VENDOR_DETAILS_FAILURE',

    CLEAR_ORGANIZATION_TYPE: 'Organization/CLEAR_ORGANIZATION_TYPE',
    SERVICE_PROVIDER_CONTACT_FORM: 'Organiation/SERVICE_PROVIDER_CONTACT_FORM',
    SERVICE_PROVIDER_CONTACT_FORM_LOAD_FLAG: 'Organiation/SERVICE_PROVIDER_CONTACT_FORM_LOAD_FLAG',

    CLEAN_ASSIGN_CUSTOMER_TO_SERVICE_WORKER: 'Organiation/CLEAN_ASSIGN_CUSTOMER_TO_SERVICE_WORKER',
    CLEAR_VENDOR_DETAILS_REDUCER: 'Organiation/CLEAR_VENDOR_DETAILS_REDUCER',

    FETCH_VENDOR_DETAILS_BY_ID: 'Organization/FETCH_VENDOR_DETAILS_BY_ID',
    FETCH_VENDOR_DETAILS_BY_ID_REQUEST: 'Organization/FETCH_VENDOR_DETAILS_BY_ID_REQUEST',
    FETCH_VENDOR_DETAILS_BY_ID_SUCCESS: 'Organization/FETCH_VENDOR_DETAILS_BY_ID_SUCCESS',
    FETCH_VENDOR_DETAILS_BY_ID_FAILURE: 'Organization/FETCH_VENDOR_DETAILS_BY_ID_FAILURE',

    SAVE_VENDOR_DETAILS: 'Organization/SAVE_VENDOR_DETAILS',
    SAVE_VENDOR_DETAILS_REQUEST: 'Organization/SAVE_VENDOR_DETAILS_REQUEST',
    SAVE_VENDOR_DETAILS_SUCCESS: 'Organization/SAVE_VENDOR_DETAILS_SUCCESS',
    SAVE_VENDOR_DETAILS_FAILURE: 'Organization/SAVE_VENDOR_DETAILS_FAILURE',

    UPDATE_VENDOR_DETAILS: 'Organization/UPDATE_VENDOR_DETAILS',
    UPDATE_VENDOR_DETAILS_REQUEST: 'Organization/UPDATE_VENDOR_DETAILS_REQUEST',
    UPDATE_VENDOR_DETAILS_SUCCESS: 'Organization/UPDATE_VENDOR_DETAILS_SUCCESS',
    UPDATE_VENDOR_DETAILS_FAILURE: 'Organization/UPDATE_VENDOR_DETAILS_FAILURE',

    DELETE_VENDOR_DETAILS: 'Organization/DELETE_VENDOR_DETAILS',
    DELETE_VENDOR_DETAILS_REQUEST: 'Organization/DELETE_VENDOR_DETAILS_REQUEST',
    DELETE_VENDOR_DETAILS_SUCCESS: 'Organization/DELETE_VENDOR_DETAILS_SUCCESS',
    DELETE_VENDOR_DETAILS_FAILURE: 'Organization/DELETE_VENDOR_DETAILS_FAILURE',

    GET_ALL_ITEM_FOR_ASSIGN_VENDOR: 'Organization/GET_ALL_ITEM_FOR_ASSIGN_VENDOR',
    GET_ALL_ITEM_FOR_ASSIGN_VENDOR_REQUEST: 'Organization/GET_ALL_ITEM_FOR_ASSIGN_VENDOR_EQUEST',
    GET_ALL_ITEM_FOR_ASSIGN_VENDOR_SUCCESS: 'Organization/GET_ALL_ITEM_FOR_ASSIGN_VENDOR_SUCCESS',
    GET_ALL_ITEM_FOR_ASSIGN_VENDOR_FAILURE: 'Organization/GET_ALL_ITEM_FOR_ASSIGN_VENDOR_FAILURE',

    GET_ALL_ITEM_TYPE_FOR_ASSIGN_VENDOR: 'Organization/GET_ALL_ITEM__TYPE_FOR_ASSIGN_VENDOR',
    GET_ALL_ITEM_TYPE_FOR_ASSIGN_VENDOR_REQUEST: 'Organization/GET_ALL_ITEM__TYPE_FOR_ASSIGN_VENDOR_EQUEST',
    GET_ALL_ITEM_TYPE_FOR_ASSIGN_VENDOR_SUCCESS: 'Organization/GET_ALL_ITEM__TYPE_FOR_ASSIGN_VENDOR_SUCCESS',
    GET_ALL_ITEM_TYPE_FOR_ASSIGN_VENDOR_FAILURE: 'Organization/GET_ALL_ITEM__TYPE_FOR_ASSIGN_VENDOR_FAILURE',

    FETCH_ADDITIONAL_BASIC_DETAILS: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS',
    FETCH_ADDITIONAL_BASIC_DETAILS_REQUEST: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_REQUEST',
    FETCH_ADDITIONAL_BASIC_DETAILS_SUCCESS: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_SUCCESS',
    FETCH_ADDITIONAL_BASIC_DETAILS_FAILURE: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_FAILURE',

    SAVE_ADDITIONAL_BASIC_DETAILS: 'Organization/SAVE_ADDITIONAL_BASIC_DETAILS',
    SAVE_ADDITIONAL_BASIC_DETAILS_REQUEST: 'Organization/SAVE_ADDITIONAL_BASIC_DETAILS_REQUEST',
    SAVE_ADDITIONAL_BASIC_DETAILS_SUCCESS: 'Organization/SAVE_ADDITIONAL_BASIC_DETAILS_SUCCESS',
    SAVE_ADDITIONAL_BASIC_DETAILS_FAILURE: 'Organization/SAVE_ADDITIONAL_BASIC_DETAILS_FAILURE',

    FETCH_ADDITIONAL_BASIC_DETAILS_WARDS: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_WARDS',
    FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_REQUEST: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_REQUEST',
    FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_SUCCESS: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_SUCCESS',
    FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_FAILURE: 'Organization/FETCH_ADDITIONAL_BASIC_DETAILS_WARDS_FAILURE',

    FETCH_ASSIGN_ORGANIZATION: 'Organization/FETCH_ASSIGN_ORGANIZATION',
    FETCH_ASSIGN_ORGANIZATION_REQUEST: 'Organization/FETCH_ASSIGN_ORGANIZATION_REQUEST',
    FETCH_ASSIGN_ORGANIZATION_SUCCESS: 'Organization/FETCH_ASSIGN_ORGANIZATION_SUCCESS',
    FETCH_ASSIGN_ORGANIZATION_FAILURE: 'Organization/FETCH_ASSIGN_ORGANIZATION_FAILURE',

    SUBMIT_ASSIGN_ORGANIZATION: 'Organization/SUBMIT_ASSIGN_ORGANIZATION',
    SUBMIT_ASSIGN_ORGANIZATION_REQUEST: 'Organization/SUBMIT_ASSIGN_ORGANIZATION_REQUEST',
    SUBMIT_ASSIGN_ORGANIZATION_SUCCESS: 'Organization/SUBMIT_ASSIGN_ORGANIZATION_SUCCESS',
    SUBMIT_ASSIGN_ORGANIZATION_FAILURE: 'Organization/SUBMIT_ASSIGN_ORGANIZATION_FAILURE',

    UPDATE_CHK_ASSIGN_ORGANIZATION: 'Organization/UPDATE_CHK_ASSIGN_ORGANIZATION',
    UPDATE_CHK_ASSIGN_ORGANIZATION_REQUEST: 'Organization/UPDATE_CHK_ASSIGN_ORGANIZATION_REQUEST',
    UPDATE_CHK_ASSIGN_ORGANIZATION_SUCCESS: 'Organization/UPDATE_CHK_ASSIGN_ORGANIZATION_SUCCESS',
    UPDATE_CHK_ASSIGN_ORGANIZATION_FAILURE: 'Organization/UPDATE_CHK_ASSIGN_ORGANIZATION_FAILURE',

    FETCH_ASSIGN_ROLE_IN_ORG: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG',
    FETCH_ASSIGN_ROLE_IN_ORG_REQUEST: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_REQUEST',
    FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS',
    FETCH_ASSIGN_ROLE_IN_ORG_FAILURE: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_FAILURE',

    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_REQUEST: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_REQUEST',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_FAILURE: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_FAILURE',
    // complaint escalation matrix
    COMPLAINT_EM_LIST: 'Organization/COMPLAINT_ESCALATION_MATRIX_LIST',
    COMPLAINT_EM_LIST_REQUEST: 'Organization/COMPLAINT_ESCALATION_MATRIX_LIST_REQUEST',
    COMPLAINT_EM_LIST_SUCCESS: 'Organization/COMPLAINT_ESCALATION_MATRIX_LIST_SUCCESS',
    COMPLAINT_EM_LIST_FAILED: 'Organization/COMPLAINT_ESCALATION_MATRIX_LIST_FAILED',

    COMPLAINT_EM_DELETE: 'Organization/DELETE_COMPLAINT_ESCALATION_MATRIX',
    COMPLAINT_EM_DELETE_REQUEST: 'Organization/DELETE_COMPLAINT_ESCALATION_MATRIX_REQUEST',
    COMPLAINT_EM_DELETE_SUCCESS: 'Organization/DELETE_COMPLAINT_ESCALATION_MATRIX_SUCCESS',
    COMPLAINT_EM_DELETE_FAILED: 'Organization/DELETE_COMPLAINT_ESCALATION_MATRIX_FAILED',

    COMPLAINT_EM_GET_BY_ID: 'Organization/COMPLAINT_EM_GET_BY_ID',
    COMPLAINT_EM_GET_BY_ID_REQUEST: 'Organization/COMPLAINT_EM_GET_BY_ID_REQUEST',
    COMPLAINT_EM_GET_BY_ID_SUCCESS: 'Organization/COMPLAINT_EM_GET_BY_ID_SUCCESS',
    COMPLAINT_EM_GET_BY_ID_FAILED: 'Organization/COMPLAINT_EM_GET_BY_ID_FAILED',

    COMPLAINT_EM_SAVE: 'Organization/COMPLAINT_ESCALATION_MATRIX_SAVE',
    COMPLAINT_EM_SAVE_REQUEST: 'Organization/COMPLAINT_ESCALATION_MATRIX_SAVE_REQUEST',
    COMPLAINT_EM_SAVE_SUCCESS: 'Organization/COMPLAINT_ESCALATION_MATRIX_SAVE_SUCCESS',
    COMPLAINT_EM_SAVE_FAILED: 'Organization/COMPLAINT_ESCALATION_MATRIX_SAVE_FAILED',

    COMPLAINT_EM_UPDATE: 'Organization/COMPLAINT_ESCALATION_MATRIX_UPDATE',
    COMPLAINT_EM_UPDATE_REQUEST: 'Organization/COMPLAINT_ESCALATION_MATRIX_UPDATE_REQUEST',
    COMPLAINT_EM_UPDATE_SUCCESS: 'Organization/COMPLAINT_ESCALATION_MATRIX_UPDATE_SUCCESS',
    COMPLAINT_EM_UPDATE_FAILED: 'Organization/COMPLAINT_ESCALATION_MATRIX_UPDATE_FAILED',
    // Complaint, Role, Template Type, Template

    COMPLAINT_LIST: 'Organization/COMPLAINT_LIST',
    COMPLAINT_LIST_REQUEST: 'Organization/COMPLAINT_LIST_REQUEST',
    COMPLAINT_LIST_SUCCESS: 'Organization/COMPLAINT_LIST_SUCCESS',
    COMPLAINT_LIST_FAILED: 'Organization/COMPLAINT_LIST_FAILED',

    ROLE_LIST: 'Organization/ROLE_LIST',
    ROLE_LIST_REQUEST: 'Organization/ROLE_LIST_REQUEST',
    ROLE_LIST_SUCCESS: 'Organization/ROLE_LIST_SUCCESS',
    ROLE_LIST_FAILED: 'Organization/ROLE_LIST_FAILED',

    TEMPLATE_TYPE_LIST: 'Organization/TEMPLATE_TYPE_LIST',
    TEMPLATE_TYPE_LIST_REQUEST: 'Organization/TEMPLATE_TYPE_LIST_REQUEST',
    TEMPLATE_TYPE_LIST_SUCCESS: 'Organization/TEMPLATE_TYPE_LIST_SUCCESS',
    TEMPLATE_TYPE_LIST_FAILED: 'Organization/TEMPLATE_TYPE_LIST_FAILED',

    TEMPLATE_LIST: 'Organization/TEMPLATE_LIST',
    TEMPLATE_LIST_REQUEST: 'Organization/TEMPLATE_LIST_REQUEST',
    TEMPLATE_LIST_SUCCESS: 'Organization/TEMPLATE_LIST_SUCCESS',
    TEMPLATE_LIST_FAILED: 'Organization/TEMPLATE_LIST_FAILED',

    ALL_SERVICE_PROVIDER_DROPDOWN: 'Organization/ALL_SERVICE_PROVIDER_DROPDOWN',
    ALL_SERVICE_PROVIDER_DROPDOWN_REQUEST: 'Organization/ALL_SERVICE_PROVIDER_DROPDOWN_REQUEST',
    ALL_SERVICE_PROVIDER_DROPDOWN_SUCCESS: 'Organization/ALL_SERVICE_PROVIDER_DROPDOWN_SUCCESS',
    ALL_SERVICE_PROVIDER_DROPDOWN_FAILURE: 'Organization/ALL_SERVICE_PROVIDER_DROPDOWN_FAILURE',

    RESET_COMPLAINT_ESCALATION_FORM: 'Organization/RESET_COMPLAINT_ESCALATION_FORM',
    RESET_ORG_TAB_INDEX: 'Organization/RESET_ORG_TAB_INDEX'

};

export const hierarchyTypes = {
    ORGANIZATION_COMMON_STATE_REQUEST: 'Organization/COMMON_STATE_REQUEST',
    ORGANIZATION_COMMON_STATE_SUCCESS: 'Organization/COMMON_STATE_SUCCESS',
    ORGANIZATION_COMMON_STATE_FAILED: 'Organization/COMMON_STATE_FAILED',

    ORGANIZATION_COMMON_DISTRICT_REQUEST: 'Organization/COMMON_DISTRICT_REQUEST',
    ORGANIZATION_COMMON_DISTRICT_SUCCESS: 'Organization/COMMON_DISTRICT_SUCCESS',
    ORGANIZATION_COMMON_DISTRICT_FAILED: 'Organization/COMMON_DISTRICT_FAILED',

    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_REQUEST: 'Organization/COMMON_DISTRICT_PANCHAYATH_REQUEST',
    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_SUCCESS: 'Organization/COMMON_DISTRICT_PANCHAYATH_SUCCESS',
    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_FAILED: 'Organization/COMMON_DISTRICT_PANCHAYATH_FAILED',

    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_REQUEST: 'Organization/COMMON_BLOCK_PANCHAYATH_REQUEST',
    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_SUCCESS: 'Organization/COMMON_BLOCK_PANCHAYATH_SUCCESS',
    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_FAILED: 'Organization/COMMON_BLOCK_PANCHAYATH_FAILED',

    ORGANIZATION_COMMON_LSGI_REQUEST: 'Organization/COMMON_LSGI_REQUEST',
    ORGANIZATION_COMMON_LSGI_SUCCESS: 'Organization/COMMON_LSGI_SUCCESS',
    ORGANIZATION_COMMON_LSGI_FAILED: 'Organization/COMMON_LSGI_FAILED'


};

export const listOrganization = (data) => action(types.LIST_ORGANISATION, { data });
//function for delete organisation
export const deleteOrganization = (data, page, size, count) => action(types.DELETE_ORGANISATION, { data, page, size, count });

export const deleteService = (data, page, size, count, providerId) => action(types.DELETE_SERVICE, { data, page, size, count, providerId });

export const saveOrganization = (data) => data.organizationId ? action(types.UPDATE_ORGANIZATION, { data }) : action(types.SAVE_ORGANIZATION, { data });
export const updateCurrentOrganizatioDetails = (data) => action(types.UPDATE_CURRENT_ORGANIZATION, { data });
export const loadAPIProviders = () => action(types.LOAD_API_PROVIDERS);
export const loadParentOrganizations = () => action(types.LOAD_PARENT_ORGANIZATIONS);
export const loadOrganizationTypes = () => action(types.LOAD_ORGANIZATION_TYPES);
export const loadOrganizationRoleTypes = (data) => action(types.LOAD_ORGANIZATION_ROLE_TYPES, { data });
export const loadUserGroupAssignUsersList = (roleId, orgId) => action(types.CHK_LOAD_USER_GROUP_ASSIGN_LIST, { roleId, orgId });

export const setFilters = (data) => action(types.SET_FILTER, { data });

export const setFilterValuesForService = (data) => action(types.SET_FILTER_VALUES_FOR_SERVICE, { data });

export const loadOrganizationAPIProviders = (id) => action(types.LOAD_ORGANIZATION_API_PROVIDERS, { id });
export const saveOrganizationAPIProviders = (data) => action(types.SAVE_ORGANIZATION_API_PROVIDERS, { data });
// export const setOrganization = (data) => action(types.SET_ORGANIZATION_DETAILS, { data });
export const fetchOrganizationDetails = (data) => action(types.FETCH_ORGANIZATION_DETAILS, { data });
export const loadUsersOrganizationList = (data) => action(types.FETCH_CHK_USER_ORGANIZATION, { data });
export const updateUserOrganizationMapping = (data) => action(types.UPDATE_CHK_USER_ORGANIZATION, { data });
export const updateUserOrganizationRole = (data, id, roleId) => action(types.UPDATE_CHK_USER_ORGANIZATION_ROLE, { data, id, roleId });

export const getEmailApiProvider = (id, emailApiType) => action(types.GET_EMAIL_API_PROVIDER, { id, emailApiType });
export const getSmsApiProvider = (id, smsApiType) => action(types.GET_SMS_API_PROVIDER, { id, smsApiType });
export const getNotificationApiProvider = (id, notificationApiType) => action(types.GET_NOTIFICATION_API_PROVIDER, { id, notificationApiType });
export const getPaymentApiProvider = (id, paymentApiType) => action(types.GET_PAYMENT_API_PROVIDER, { id, paymentApiType });
export const sentApiProviderKey = (id, data) => action(types.UPDATE_API_PROVIDER, { id, data });
export const sentApiProviderKeyForPost = (id, data) => action(types.POST_API_PROVIDER, { id, data });
//modules
export const fetchModulesforChk = (data) => action(types.FETCH_MODULES_FOR_CHK, { data });
export const fetchAssignedModulesforChk = (data) => action(types.FETCH_ASSIGNED_MODULES_FOR_CHK, { data });
export const saveModulesinOrgChk = (data) => action(types.SAVE_MODULES_FOR_CHK, { data });
export const saveModulesinOrgChkInLocation = (data) => action(types.SAVE_MODULES_FOR_CHK_IN_LOCATION, { data });

export const saveAssignedModulesinOrgChk = (data) => action(types.SAVE_ASSIGNED_MODULES, { data });
export const fetchRolesforListBox = (data) => action(types.FETCH_ROLESLIST_FOR_MODULE, { data });
export const clearCheckListInReducer = () => action(types.CLEAR_ASSIGNED_CHECKED_LIST);
//template
export const fetchTemplatesForList = () => action(types.FETCH_TEMPLATE_FOR_LST);
//AssignTemplate
export const fetchSelectedTemplatesForList = (data) => action(types.FETCH_SELECTED_TEMPLATE_FOR_LST, { data });

export const saveTemplatesInList = (data) => action(types.SAVE_TEMPLATE_IN_LIST, { data });

export const getTemplateTypes = () => action(types.GET_TEMPLATE_TYPES_FOR_ORG);

export const getTemplatesBasedOnTempTypeId = (id) => action(types.GET_TEMPLATE_BY_TEMP_TYPE_ID, { id });

export const getServiceProvider = () => action(types.GET_SERVICE_PROVIDER);

export const setTabIndex = (data) => action(types.SET_TAB_INDEX, { data });

export const setTabIndexForServiceProvider = (data) => action(types.SET_TAB_INDEX_FOR_SERVICE_PROVIDER, { data });


export const postServiceProviders = (data, id) => action(types.POST_SERVICE_PROVIDERS, { data, id });

export const listServiceProvider = (data, id) => action(types.LIST_SERVICE_PROVIDER, { data, id });

export const getServiceProviderById = (id, orgId) => action(types.GET_SERVICE_PROVIDERS_BY_ID, { id, orgId });

export const editServiceProviders = (data, id, providerId) => action(types.SERVICE_PROVIDER_EDIT, { data, id, providerId });

export const getAssignedLocations = (orgId, providerId) => action(types.GET_ASSIGNED_LOCATION, { orgId, providerId });

export const loadAllRoles = () => action(types.GET_ALL_ROLES);

export const fetchUserBasedOnRoleId = (roleId, orgId) => action(types.GET_USER_BASED_ON_ROLE_ID, { roleId, orgId });

export const updateAssignServiceAdmin = (data, id, providerId, roleId) => action(types.UPDATE_ASSIGN_SERVICE_ADMIN, { data, id, providerId, roleId });

export const getAssignServiceAdmin = (id, providerId, roleId) => action(types.GET_ASSIGNED_SERVICE_ADMIN, { id, providerId, roleId });

export const getAssignSuperVisor = (id) => action(types.GET_ASSIGNED_SUPER_VISOR, { id });

export const getAssignWorkers = (id) => action(types.GET_ASSIGNED_WORKERS, { id });
export const getAssignedWorkersOnly = (id) => action(types.GET_ASSIGNED_WORKERS_ONLY, { id });

export const getLocationBasedOnWorker = (id) => action(types.GET_LOCATION_BASED_ON_WORKER, { id });
export const getoldSuperVisor = () => action(types.GET_OLD_SUPER_VISOR);
export const getNewSuperVisor = () => action(types.GET_NEW_SUPER_VISOR);

export const fetchLocationForOrganisation = (orgId, providerId) => action(types.GET_ASSIGNED_LOCATIONS, { orgId, providerId });

export const updateAssignedLOcations = (data, orgId, providerId) => action(types.UPDATE_ASSIGNED_LOCATIONS, { data, orgId, providerId });

export const getAllUsersUnderRoleId = (orgId, providerId, roleId) => action(types.GET_USER_BY_ROLE_ID, { orgId, providerId, roleId });


export const getAssignServiceAdminDropDown = (type, id, providerId, roleId) => action(types.GET_ASSIGNED_SERVICE_ADMIN_DROP_DOWN, { type, id, providerId, roleId });

export const getAllLocationUnderUser = (id, providerId, userId, roleId) => action(types.GET_LOCATIONS_UNDER_USER, { id, providerId, userId, roleId });

export const updateAssignedWorkerLocation = (data, orgId, providerId, roleId, userId) => action(types.UPDATE_ASSIGNED_WORKER_LOCATION, { data, orgId, providerId, roleId, userId });

export const getAllUserUnderOrgSp = (id, providerId, userId, roleId) => action(types.GET_ALL_USER_UNDER_ORG_FOR_SP, { id, providerId, userId, roleId });

export const updateAllUserUnderOrg = (data, id, providerId, roleId, userId) => action(types.UPDATE_ALL_USER_UNDER_ORG, { data, id, providerId, roleId, userId });

export const resetServiceAdminForm = () => action(types.RESET_SERVICE_ADMIN_FORM);
export const resetAssignWorkerLocation = () => action(types.RESET_SERVICE_ADMIN_FORM);

export const resetSuperVisorToWorker = () => action(types.RESET_SUPER_VISOR_TO_WORKER_FORM);

export const resetCheckBoxSupervisorToWorker = () => action(types.RESET_CHECKBOX_SUPERVISOR_TO_WORKER_LOCATION_ARRAY);

export const fetchInitialOrganization = () => action(types.FETCH_INITIAL_ORGANIZATIONS);

export const resetOrgFormRole = () => action(types.RESET_ORGANIZATION_ROLE_FORM_ASSIGN);

export const deleteServiceProvider = (orgId, id) => action(types.DELETE_SERVICE_PROVIDER, { orgId, id });
export const resetCheckboxWorkerArray = () => action(types.RESET_CHECKBOX_WORKER_LOCATION_ARRAY);
export const resetCheckboxArrayForServiceToWorker = () => action(types.RESET_CHECKBOX_WORKER_LOCATION_ARRAY);

export const setFilter = (data) => action(types.SET_FILTER_VALUES_FOR_ORGS, { data });
export const resetFilter = () => action(types.RESET_FILTER_VALUES_FOR_ORGS);


export const storeJsonDataForOrgs = (data) => action(types.STORE_JSON_DATA_FOR_ORGS, { data });

export const storeJsonDataForService = (data) => action(types.STORE_JSON_DATA_FOR_SERVICE, { data });

export const listJsonDataForOrgs = (searchValue, searchKey, columnName) => action(types.LIST_JSON_DATA_FOR_ORG_FILTER, { searchValue, searchKey, columnName });

export const fetchServiceProviderDetails = (data) => action(types.FETCH_SERVICE_PROVIDER_LIST, { data });

export const listJsonDataForService = (searchValue, searchKey, columnName) => action(types.LIST_JSON_DATA_FOR_SERVICE_FILTER, { searchValue, searchKey, columnName });


export const getResidentialCategory = () => action(types.LIST_RESIDENCE_CATEGORY);
export const getServiceCategory = () => action(types.LIST_SERVICE_CATEGORY);
export const getServiceType = () => action(types.LIST_SERVICE_TYPE);
export const getPaymentCollection = () => action(types.LIST_PAYMENT_COLLECTION);
export const getPaymentIntervalDetails = () => action(types.LIST_PAYMENT_INTERVAL);
export const getRateType = () => action(types.LIST_RATE_TYPE);

export const getServiceInterval = () => action(types.LIST_SERVICE_INTERVEL);

export const fetchBundledOrServiceConfig = (data) => action(types.LIST_BUNDLED_OR_SERVICE_CONFIG, { data });

export const resetbundledServiceConfig = (data) => action(types.LIST_RESET_BUNDLED_SERVICE_CONFIG, { data });
export const getServiceChargeSlab = () => action(types.LIST_SERVICE_CHARGE_SLAB);
export const sentObjectForService = (data, id, providerId) => action(types.SENT_OBJECT_FOR_SERVICE, { data, id, providerId });

export const editObjectForService = (data, id, providerId, serviceId) => action(types.EDIT_OBJECT_FOR_SERVICE, { data, id, providerId, serviceId });


export const listService = (data) => action(types.LIST_SERVICE, { data });

export const getServiceById = (serviceId) => action(types.LIST_SERVICE_BY_ID, { serviceId });

export const resetService = () => action(types.RESET_SERVICE);

export const clearReducer = () => action(types.CLEAR_ORGANIZATION_REDUCER);
//fn will work when rate type is changed from slab array
export const emptySlabArray = () => action(types.EMPTY_SLAB_ARRAY);
//to get wards under providerId
export const getWardsUnderProviderId = (orgId, providerId) => action(types.GET_WARDS_UNDER_SERVICE_PROVIDER_ID, { orgId, providerId });
export const getGtBasedOnWardId = (providerId, wardId) => action(types.GET_GT_BASED_ON_WARD_ID, { providerId, wardId });

export const getUuidsOfCustomers = (uuidArray, customerArray) => action(types.GET_UUID_OF_CUSTOMERS, { uuidArray, customerArray });
export const setData = (data) => action(types.SET_STATE_OR_DISTRICT, { data });
export const setRoleAndUser = (data) => action(types.SET_ROLE_USER, { data });
export const setWorkerAndSuperwiser = (data) => action(types.SET_WORKER_SUPERWISER, { data });


export const getCustomersBasedOnGt = (data) => action(types.GET_CUSTOMERS_BASED_ON_GT_ID, { data });

export const getSuperVisors = (orgId, providerId) => action(types.GET_SUPER_VISORS, { orgId, providerId });
export const getToGt = (orgId, providerId, superVisorId) => action(types.GET_TO_GT_WITH_SUPER_VISOR_ID, { orgId, providerId, superVisorId });
export const postReassignGt = (data, fromGtId, toGtId) => action(types.POST_RE_ASSIGN_GT, { data, fromGtId, toGtId });
export const updateReAssignSuperVisor = (data, currentSuperVisorId, newSupervisorId, id, providerId) => action(types.UPDATE_RE_ASSIGN_SUPER_VISOR, { data, currentSuperVisorId, newSupervisorId, id, providerId });
export const loadUsersOrganizationListForServiceWorker = (orgId) => action(types.LOAD_ORG_FOR_SERVICE_WORKER, { orgId });
export const resetOrgUser = () => action(types.RESET_ORG_USER);
export const setOrgRoleType = (data) => action(types.SET_ORGANIZATION_ROLE_TYPES, { data });
export const resetReAssignGt = () => action(types.RESET_RE_ASSIGN_GT);
export const setFromGT = (data) => action(types.SET_FROM_GT, { data });
export const setToGT = (data) => action(types.SET_TO_GT, { data });
export const toggleStatus = (data) => action(types.TOGGLE_STATUS, { data });
export const loadTemplates = (data) => action(types.LOAD_TEMPLATES, { data });
export const loadServices = (data) => action(types.LOAD_SERVICES, { data });
export const fetchOrganizationAssignUsers = (data) => action(types.FETCH_ORGANIZATION_ASSIGN_USERS, { data });

export const getSwSuperVisorForWard = (data) => action(types.GET_SW_SUPERVISOR_FOR_WARD, { data });

export const getServiceWorkerFromSWSuperVisor = (data) => action(types.GET_SERVICE_WORKER_FROM_SW_SUPERVISOR, { data });

export const submitReAssignSuperVisorData = (data) => action(types.SUBMIT_RE_ASSIGN_SUPERVISOR_DATA, { data });

export const submitReAssignWorkerData = (data) => action(types.SUBMIT_RE_ASSIGN_WORKER_DATA, { data });

export const fetchOrganizationAssignGT = () => action(types.FETCH_ORGANIZATION_ASSIGN_CUSTOMER_TO_SERVICE_WORKER);

export const submitcustomerNumbers = (data) => action(types.SUBMIT_CUSTOMER_NUMBER_FOR_CUSTOMER_TO_SERVICE_WORKER, { data });

export const cleanAssignServiceWorkerToSupervisor = () => action(types.CLEAN_ASSIGN_CUSTOMER_TO_SERVICE_WORKER);

export const fetchVendorDetails = (data) => action(types.FETCH_VENDOR_DETAILS, { data });

export const clearVendorReducer = () => action(types.CLEAR_VENDOR_DETAILS_REDUCER);

export const fetchVendorById = (data) => action(types.FETCH_VENDOR_DETAILS_BY_ID, { data });

export const saveVendorData = (data) => action(types.SAVE_VENDOR_DETAILS, { data });

export const updatesVendorData = (data) => action(types.UPDATE_VENDOR_DETAILS, { data });

export const deleteVendorData = (data) => action(types.DELETE_VENDOR_DETAILS, { data });

export const getAllItems = () => action(types.GET_ALL_ITEM_FOR_ASSIGN_VENDOR, {});
export const getAllItemType = () => action(types.GET_ALL_ITEM_TYPE_FOR_ASSIGN_VENDOR, {});

export const clearOrganizationType = () => action(types.CLEAR_ORGANIZATION_TYPE);

export const serviceProviderContactDetails = (data) => action(types.SERVICE_PROVIDER_CONTACT_FORM, { data });
export const serviceProviderContactDetailsTemplateLoadFlag = (data) => action(types.SERVICE_PROVIDER_CONTACT_FORM_LOAD_FLAG, { data });

export const fetchAdditionalBasicDetails = (data) => action(types.FETCH_ADDITIONAL_BASIC_DETAILS, { data });

export const fetchAdditionalBasicDetailsWards = (data) => action(types.FETCH_ADDITIONAL_BASIC_DETAILS_WARDS, { data });

export const fetchAssignOrganization = (data) => action(types.FETCH_ASSIGN_ORGANIZATION, { data });

export const submitAssignOrganization = (data) => action(types.SUBMIT_ASSIGN_ORGANIZATION, { data });
export const updateAssignOrganizationMapping = (data) => action(types.UPDATE_CHK_ASSIGN_ORGANIZATION, { data });

export const saveAdditionalBasicDetails = (data) => action(types.SAVE_ADDITIONAL_BASIC_DETAILS, { data });

export const fetchAssignRoleInOrg = (data) => action(types.FETCH_ASSIGN_ROLE_IN_ORG, { data });
export const submitAssignRole = (data) => action(types.SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG, { data });

// ComplaintEscalationMatrix

export const listComplaintEscalation = (data) => action(types.COMPLAINT_EM_LIST, { data });
export const deleteComplaintEscalation = (cemId, id) => action(types.COMPLAINT_EM_DELETE, { cemId, id });
export const saveComplaintEscalation = (orgId, data) => action(types.COMPLAINT_EM_SAVE, { orgId, data });
export const updateComplaintEscalation = (orgId, cemId, data) => action(types.COMPLAINT_EM_UPDATE, { orgId, cemId, data });
export const getComplaintEscalationById = (orgId, cemId) => action(types.COMPLAINT_EM_GET_BY_ID, { orgId, cemId });
export const resetComplaintEscalationForm = () => action(types.RESET_COMPLAINT_ESCALATION_FORM);


export const listComplaints = () => action(types.COMPLAINT_LIST);
export const listRoles = () => action(types.ROLE_LIST);
export const listTemplateType = () => action(types.TEMPLATE_TYPE_LIST);
export const listTemplate = () => action(types.TEMPLATE_LIST);

export const getAllServiceProviderUnderOrg = (data) => action(types.ALL_SERVICE_PROVIDER_DROPDOWN, { data });

export const resetTabIndex = () => action(types.RESET_ORG_TAB_INDEX, {});
