const STATE_REDUCER_KEY = 'buildingType';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_BUILDING_TYPE: 'LIST_BUILDING_TYPE'
};
