import { action } from '../../common';

export const types = {
    LIST_RESIDENCE_CATEGORY: 'RESIDENCECategory/LIST_RESIDENCE_CATEGORY',
    LIST_RESIDENCE_CATEGORY_REQUEST: 'RESIDENCECategory/LIST_RESIDENCE_CATEGORY_REQUEST',
    LIST_RESIDENCE_CATEGORY_SUCCESS: 'RESIDENCECategory/LIST_RESIDENCE_CATEGORY_SUCCESS',
    LIST_RESIDENCE_CATEGORY_FAILURE: 'RESIDENCECategory/LIST_RESIDENCE_CATEGORY_FAILURE',

    SENT_RESIDENCE_CATEGORY: 'RESIDENCECategory/SENT_RESIDENCE_CATEGORY',
    SENT_RESIDENCE_CATEGORY_REQUEST: 'RESIDENCECategory/SENT_RESIDENCE_CATEGORY_REQUEST',
    SENT_RESIDENCE_CATEGORY_SUCCESS: 'RESIDENCECategory/SENT_RESIDENCE_CATEGORY_SUCCESS',
    SENT_RESIDENCE_CATEGORY_FAILURE: 'RESIDENCECategory/SENT_RESIDENCE_CATEGORY_FAILURE',

    EDIT_RESIDENCE_CATEGORY: 'RESIDENCECategory/EDIT_RESIDENCE_CATEGORY',
    EDIT_RESIDENCE_CATEGORY_REQUEST: 'RESIDENCECategory/EDIT_RESIDENCE_CATEGORY_REQUEST',
    EDIT_RESIDENCE_CATEGORY_SUCCESS: 'RESIDENCECategory/EDIT_RESIDENCE_CATEGORY_SUCCESS',
    EDIT_RESIDENCE_CATEGORY_FAILURE: 'RESIDENCECategory/EDIT_RESIDENCE_CATEGORY_FAILURE',

    GET_RESIDENCE_CATEGORY_BY_ID: 'RESIDENCECategory/GET_RESIDENCE_CATEGORY_BY_ID',
    GET_RESIDENCE_CATEGORY_BY_ID_REQUEST: 'RESIDENCECategory/GET_RESIDENCE_CATEGORY_BY_ID_REQUEST',
    GET_RESIDENCE_CATEGORY_BY_ID_SUCCESS: 'RESIDENCECategory/GET_RESIDENCE_CATEGORY_BY_ID_SUCCESS',
    GET_RESIDENCE_CATEGORY_BY_ID_FAILURE: 'RESIDENCECategory/GET_RESIDENCE_CATEGORY_BY_ID_FAILRUE',
    DELETE_RESIDENCE_CATEGORY: 'RESIDENCECategory/DELETE_RESIDENCE_CATEGORY',
    DELETE_RESIDENCE_CATEGORY_REQUEST: 'RESIDENCECategory/DELETE_RESIDENCE_CATEGORY_REQUEST',
    DELETE_RESIDENCE_CATEGORY_SUCCESS: 'RESIDENCECategory/DELETE_RESIDENCE_CATEGORY_SUCCESS',
    DELETE_RESIDENCE_CATEGORY_FAILURE: 'RESIDENCECategory/DELETE_RESIDENCE_CATEGORY_FAILURE',
    RESET_RESIDENCE_FORM: 'RESIDENCECategory/RESET_RESIDENCE_FORM'

};

export const listResidenceCategories = (data) => action(types.LIST_RESIDENCE_CATEGORY, { data });

export const sentResidenceCategory = (data) => action(types.SENT_RESIDENCE_CATEGORY, { data });
export const editResidenceCategory = (id, data) => action(types.EDIT_RESIDENCE_CATEGORY, { id, data });


export const getResidenceCategoryById = (id) => action(types.GET_RESIDENCE_CATEGORY_BY_ID, { id });

export const deleteResidenceCategory = (data, page, size, count) => action(types.DELETE_RESIDENCE_CATEGORY, { data, page, size, count });

export const resetResidenceCreationForm = () => action(types.RESET_RESIDENCE_FORM);

