const STATE_REDUCER_KEY = 'residenceCategory';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };

export const TABLE_IDS = {
    LIST_RESIDENCE_CATEGORY: 'LIST_RESIDENCE_CATEGORY'
};
