import { action } from '../../common';

export const types = {
    LOAD_LANGUAGES_FOR_FRAGMENTS: 'LOAD_LANGUAGES_FOR_FRAGMENTS',
    LOAD_LANGUAGES_FOR_FRAGMENTS_REQUEST: 'LOAD_LANGUAGES_FOR_FRAGMENTS_REQUEST',
    LOAD_LANGUAGES_FOR_FRAGMENTS_SUCCESS: 'LOAD_LANGUAGES_FOR_FRAGMENTS_SUCCESS',
    LOAD_LANGUAGES_FOR_FRAGMENTS_FAILURE: 'LOAD_LANGUAGES_FOR_FRAGMENTS_FAILURE',

    LIST_FRAGMENT_PAGEBALE: 'LIST_FRAGMENT_PAGEBALE',
    LIST_FRAGMENT_PAGEBALE_REQUEST: 'LIST_FRAGMENT_PAGEBALE_REQUEST',
    LIST_FRAGMENT_PAGEBALE_SUCCESS: 'LIST_FRAGMENT_PAGEBALE_SUCCESS',
    LIST_FRAGMENT_PAGEBALE_FAILURE: 'LIST_FRAGMENT_PAGEBALE_FAILURE',

    LOAD_TITLES_FOR_FRAGMENT: 'LOAD_TITLES_FOR_FRAGMENT',
    LOAD_TITLES_FOR_FRAGMENT_REQUEST: 'LOAD_TITLES_FOR_FRAGMENT_REQUEST',
    LOAD_TITLES_FOR_FRAGMENT_SUCCESS: 'LOAD_TITLES_FOR_FRAGMENT_SUCCESS',
    LOAD_TITLES_FOR_FRAGMENT_FAILURE: 'LOAD_TITLES_FOR_FRAGMENT_FAILURE',

    SENT_FRAGMENT_FOR_POST: 'SENT_FRAGMENT_FOR_POST',
    SENT_FRAGMENT_FOR_POST_REQUEST: 'SENT_FRAGMENT_FOR_POST_REQUEST',
    SENT_FRAGMENT_FOR_POST_SUCCESS: 'SENT_FRAGMENT_FOR_POST_SUCCESS',
    SENT_FRAGMENT_FOR_POST_FAILURE: 'SENT_FRAGMENT_FOR_POST_FAILURE',

    GET_BASIC_DETAILS_OF_FRAGMENTS: 'GET_BASIC_DETAILS_OF_FRAGMENTS',
    GET_BASIC_DETAILS_OF_FRAGMENTS_REQUEST: 'GET_BASIC_DETAILS_OF_FRAGMENTS_REQUEST',
    GET_BASIC_DETAILS_OF_FRAGMENTS_SUCCESS: 'GET_BASIC_DETAILS_OF_FRAGMENTS_SUCCESS',
    GET_BASIC_DETAILS_OF_FRAGMENTS_FAILURE: 'GET_BASIC_DETAILS_OF_FRAGMENTS_FAILURE',

    EDIT_FRAGMENT_BASIC_DETAILS: 'EDIT_FRAGMENT_BASIC_DETAILS',
    EDIT_FRAGMENT_BASIC_DETAILS_REQUEST: 'EDIT_FRAGMENT_BASIC_DETAILS_REQUEST',
    EDIT_FRAGMENT_BASIC_DETAILS_SUCCESS: 'EDIT_FRAGMENT_BASIC_DETAILS_SUCCESS',
    EDIT_FRAGMENT_BASIC_DETAILS_FAILURE: 'EDIT_FRAGMENT_BASIC_DETAILS_FAILURE',

    GET_TITLES_FOR_DROP_DOWN: 'GET_TITLES_FOR_DROP_DOWN',
    GET_TITLES_FOR_DROP_DOWN_REQUEST: 'GET_TITLES_FOR_DROP_DOWN_REQUEST',
    GET_TITLES_FOR_DROP_DOWN_SUCCESS: 'GET_TITLES_FOR_DROP_DOWN_SUCCESS',
    GET_TITLES_FOR_DROP_DOWN_FAILURE: 'GET_TITLES_FOR_DROP_DOWN_FAILURE',

    EDIT_FRAGMENT_TITLE_ASSOCIATION: 'EDIT_FRAGMENT_TITLE_ASSOCIATION',
    EDIT_FRAGMENT_TITLE_ASSOCIATION_REQUEST: 'EDIT_FRAGMENT_TITLE_ASSOCIATION_REQUEST',
    EDIT_FRAGMENT_TITLE_ASSOCIATION_SUCCESS: 'EDIT_FRAGMENT_TITLE_ASSOCIATION_SUCCESS',
    EDIT_FRAGMENT_TITLE_ASSOCIATION_FAILURE: 'EDIT_FRAGMENT_TITLE_ASSOCIATION_FAILURE',

    GET_TITLE_FRAGMENT_ASSOCIATION: 'GET_TITLE_FRAGMENT_ASSOCIATION',
    GET_TITLE_FRAGMENT_ASSOCIATION_REQUEST: 'GET_TITLE_FRAGMENT_ASSOCIATION_REQUEST',
    GET_TITLE_FRAGMENT_ASSOCIATION_SUCCESS: 'GET_TITLE_FRAGMENT_ASSOCIATION_SUCCESS',
    GET_TITLE_FRAGMENT_ASSOCIATION_FAILURE: 'GET_TITLE_FRAGMENT_ASSOCIATION_FAILURE',

    DELETE_FRAGMENT: 'FRAGMENT/DELETE_FRAGMENT',
    DELETE_FRAGMENT_REQUEST: 'FRAGMENT/DELETE_FRAGMENT_REQUEST',
    DELETE_FRAGMENT_SUCCESS: 'FRAGMENT/DELETE_FRAGMENT_SUCCESS',
    DELETE_FRAGMENT_FAILURE: 'FRAGMENT/DELETE_FRAGMENT_FAILURE',

    GET_TITLE_BASED_ON_FRAGMENT_ID: 'FRAGMENT/GET_TITLE_BASED_ON_FRAGMENT_ID',
    GET_TITLE_BASED_ON_FRAGMENT_ID_REQUEST: 'FRAGMENT/GET_TITLE_BASED_ON_FRAGMENT_ID_REQUEST',
    GET_TITLE_BASED_ON_FRAGMENT_ID_SUCCESS: 'FRAGMENT/GET_TITLE_BASED_ON_FRAGMENT_ID_SUCCESS',
    GET_TITLE_BASED_ON_FRAGMENT_ID_FAILURE: 'FRAGMENT/GET_TITLE_BASED_ON_FRAGMENT_ID_FAILURE',

    GET_QUESTIONS_BASED_ON_TITLE_ID: 'FRAGMENT/GET_QUESTIONS_BASED_ON_TITLE_ID',
    GET_QUESTIONS_BASED_ON_TITLE_ID_REQUEST: 'FRAGMENT/GET_QUESTIONS_BASED_ON_TITLE_ID_REQUEST',
    GET_QUESTIONS_BASED_ON_TITLE_ID_SUCCESS: 'FRAGMENT/GET_QUESTIONS_BASED_ON_TITLE_ID_SUCCESS',
    GET_QUESTIONS_BASED_ON_TITLE_ID_FAILURE: 'FRAGMENT/GET_QUESTIONS_BASED_ON_TITLE_ID_FAILURE',

    GET_ALL_FRAGMENTS_FOR_DROPDOWN: 'FRAGMENT/GET_ALL_FRAGMENTS_FOR_DROPDOWN',
    GET_ALL_FRAGMENTS_FOR_DROPDOWN_REQUEST: 'FRAGMENT/GET_ALL_FRAGMENTS_FOR_DROPDOWN_REQUEST',
    GET_ALL_FRAGMENTS_FOR_DROPDOWN_SUCCESS: 'FRAGMENT/GET_ALL_FRAGMENTS_FOR_DROPDOWN_SUCCESS',
    GET_ALL_FRAGMENTS_FOR_DROPDOWN_FAILURE: 'FRAGMENT/GET_ALL_FRAGMENTS_FOR_DROPDOWN_FAILURE',

    GET_FRAGMENT_QUESTION_LOOP_BY_ID: 'FRAGMENT/GET_FRAGMENT_QUESTION_LOOP_BY_ID',
    GET_FRAGMENT_QUESTION_LOOP_BY_ID_REQUEST: 'FRAGMENT/GET_FRAGMENT_QUESTION_LOOP_BY_ID_REQUEST',
    GET_FRAGMENT_QUESTION_LOOP_BY_ID_SUCCESS: 'FRAGMENT/GET_FRAGMENT_QUESTION_LOOP_BY_ID_SUCCESS',
    GET_FRAGMENT_QUESTION_LOOP_BY_ID_FAILURE: 'FRAGMENT/GET_FRAGMENT_QUESTION_LOOP_BY_ID_FAILURE',

    UPDATE_FRAGMENT_QUESTION_TITLE_LOOP: 'FRAGMENT/UPDATE_FRAGMENT_QUESTION_TITLE_LOOP',
    UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_REQUEST: 'FRAGMENT/UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_REQUEST',
    UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_SUCCESS: 'FRAGMENT/UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_SUCCESS',
    UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_FAILURE: 'FRAGMENT/UPDATE_FRAGMENT_QUESTION_TITLE_LOOP_FAILURE',

    FETCH_INITIAL_PAGEBLE_FRAGMENT: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT',
    FETCH_INITIAL_PAGEBLE_FRAGMENT_REQUEST: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_REQUEST',
    FETCH_INITIAL_PAGEBLE_FRAGMENT_SUCCESS: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_SUCCESS',
    FETCH_INITIAL_PAGEBLE_FRAGMENT_FAILURE: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_FAILURE',

    FETCH_CURRENT_ASSOCIATION_FRAGMENT: 'FRAGMENT/FETCH_CURRENT_ASSOCIATION_FRAGMENT',
    FETCH_CURRENT_ASSOCIATION_FRAGMENT_REQUEST: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_REQUEST',
    FETCH_CURRENT_ASSOCIATION_FRAGMENT_SUCCESS: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_SUCCESS',
    FETCH_CURRENT_ASSOCIATION_FRAGMENT_FAILURE: 'FRAGMENT/FETCH_INITIAL_PAGEBLE_FRAGMENT_FAILURE',

    CLEAR_FRAGMENT_DETAILS_REDUCER: 'FRAGMENT/CLEAR_FRAGMENT_DETAILS_REDUCER',
    STORE_JSON_DATA_FOR_FRAGMENT: 'FRAGMENT/STORE_JSON_DATA_FOR_FRAGMENT',
    SET_FRAGMENT_TAB_INDEX: 'FRAGMENT/SET_FRAGMENT_TAB_INDEX'

};


export const listFragment = (data) => action(types.LIST_FRAGMENT_PAGEBALE, { data });
export const loadLanguagesForFragment = () => action(types.LOAD_LANGUAGES_FOR_FRAGMENTS);
export const loadTitlesForFragments = () => action(types.LOAD_TITLES_FOR_FRAGMENT);
export const sentFragment = (fragmentArray) => action(types.SENT_FRAGMENT_FOR_POST, { fragmentArray });
export const getBasicDetailsOfTitle = (id) => action(types.GET_BASIC_DETAILS_OF_FRAGMENTS, { id });
export const editFragmentBasicDetail = (id, fragmentObject) => action(types.EDIT_FRAGMENT_BASIC_DETAILS, { id, fragmentObject });

export const getTitlesForDropDown = () => action(types.GET_TITLES_FOR_DROP_DOWN);

export const sentFragmentTitleAssociationForEdit = (id, titleAssociationObject) => action(types.EDIT_FRAGMENT_TITLE_ASSOCIATION, { id, titleAssociationObject });

export const getFragmentTitleAssociation = (id) => action(types.GET_TITLE_FRAGMENT_ASSOCIATION, { id });

export const deleteFragment = (id, page, size, count) => action(types.DELETE_FRAGMENT, { id, page, size, count });

export const getTitleBasedOnFragment = (id) => action(types.GET_TITLE_BASED_ON_FRAGMENT_ID, { id });

export const getQuestionsBasedOnTitleId = (id) => action(types.GET_QUESTIONS_BASED_ON_TITLE_ID, { id });

export const getAllFragments = () => action(types.GET_ALL_FRAGMENTS_FOR_DROPDOWN);

export const getFragmentQuestionLoopById = (id) => action(types.GET_FRAGMENT_QUESTION_LOOP_BY_ID, { id });
export const sentFragmentTitleQuestionLoop = (id, data) => action(types.UPDATE_FRAGMENT_QUESTION_TITLE_LOOP, { id, data });

// export const fetchInitialFragments = () => action(types.FETCH_INITIAL_PAGEBLE_FRAGMENT);
export const fetchFragmentCurrentAssociation = (id) => action(types.FETCH_CURRENT_ASSOCIATION_FRAGMENT, { id });


export const clearStateReducer = () => action(types.CLEAR_FRAGMENT_DETAILS_REDUCER);
export const storeJsonDataForUser = (data) => action(types.STORE_JSON_DATA_FOR_FRAGMENT, { data });
export const setTabIndex = (data) => action(types.SET_FRAGMENT_TAB_INDEX, { data });

