const STATE_REDUCER_KEY = 'tradingType';

const REQUEST_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
};
export { STATE_REDUCER_KEY, REQUEST_STATUS };
export const TABLE_IDS = {
    LIST_TRADING_TYPE: 'LIST_TRADING_TYPE'
};
